### ISSUE TITLE
 scout[10638] ERROR objectstorage.py L17: Failed to get Object Storage namespace: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by Aditya21jan** [nccgroup/ScoutSuite#1153]
**Describe the bug**

Please provide:

Hi Team,

While using scoutSuite tool with Oracle Cloud Infra Structure, We are facing below error, Could you please help us in resolving this.

############################
##########################

(venv) [root@def-linux-jboxsrv02 ScoutSuite]#
(venv) [root@def-linux-jboxsrv02 ScoutSuite]#
(venv) [root@def-linux-jboxsrv02 ScoutSuite]# python --version
Python 3.6.12
(venv) [root@def-linux-jboxsrv02 ScoutSuite]#
(venv) [root@def-linux-jboxsrv02 ScoutSuite]# uname -a
Linux def-linux-jboxsrv02 5.4.17-2036.102.0.2.el7uek.x86_64 #2 SMP Tue Jan 5 12:41:34 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
(venv) [root@def-linux-jboxsrv02 ScoutSuite]#
(venv) [root@def-linux-jboxsrv02 ScoutSuite]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.9 (Maipo)
(venv) [root@def-linux-jboxsrv02 ScoutSuite]#
(venv) [root@def-linux-jboxsrv02 ScoutSuite]# python scout.py oci --profile default --debug
2021-03-04 13:38:36 def-linux-jboxsrv02 scout[11962] INFO Launching Scout
2021-03-04 13:38:36 def-linux-jboxsrv02 scout[11962] INFO Authenticating to cloud provider
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] INFO Gathering data from APIs
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] INFO Fetching resources for the Identity service
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] INFO Fetching resources for the Object Storage service
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] INFO Fetching resources for the KMS service
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] ERROR objectstorage.py L17: Failed to get Object Storage namespace: 'str' object has no attribute 'items'
Traceback (most recent call last):
  File "/cloudtool/ScoutSuite/ScoutSuite/providers/oci/facade/objectstorage.py", line 17, in get_namespace
    lambda: list_call_get_all_results(self._client.get_namespace))
  File "/cloudtool/ScoutSuite/ScoutSuite/providers/utils.py", line 25, in run_concurrently
    return await run_function_concurrently(function)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/cloudtool/ScoutSuite/ScoutSuite/providers/oci/facade/objectstorage.py", line 17, in <lambda>
    lambda: list_call_get_all_results(self._client.get_namespace))
  File "/cloudtool/ScoutSuite/venv/lib/python3.6/site-packages/oci/pagination/pagination_utils.py", line 218, in list_call_get_all_results
    else aggregated_results.extend(call_result.data.items)
AttributeError: 'str' object has no attribute 'items'
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] ERROR objectstorage.py L37: Failed to get Object Storage buckets: Parameter namespaceName cannot be None, whitespace or empty string
Traceback (most recent call last):
  File "/cloudtool/ScoutSuite/ScoutSuite/providers/oci/facade/objectstorage.py", line 37, in get_buckets
    lambda: list_call_get_all_results(self._client.list_buckets, namespace, self._credentials.get_scope()))
  File "/cloudtool/ScoutSuite/ScoutSuite/providers/utils.py", line 25, in run_concurrently
    return await run_function_concurrently(function)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/cloudtool/ScoutSuite/ScoutSuite/providers/oci/facade/objectstorage.py", line 37, in <lambda>
    lambda: list_call_get_all_results(self._client.list_buckets, namespace, self._credentials.get_scope()))
  File "/cloudtool/ScoutSuite/venv/lib/python3.6/site-packages/oci/pagination/pagination_utils.py", line 205, in list_call_get_all_results
    for response in list_call_get_all_results_generator(list_func_ref, 'response', *list_func_args, **list_func_kwargs):
  File "/cloudtool/ScoutSuite/venv/lib/python3.6/site-packages/oci/pagination/pagination_utils.py", line 274, in list_call_get_all_results_generator
    call_result = retry.DEFAULT_RETRY_STRATEGY.make_retrying_call(list_func_ref, *list_func_args, **list_func_kwargs)
  File "/cloudtool/ScoutSuite/venv/lib/python3.6/site-packages/oci/retry/retry.py", line 272, in make_retrying_call
    return func_ref(*func_args, **func_kwargs)
  File "/cloudtool/ScoutSuite/venv/lib/python3.6/site-packages/oci/object_storage/object_storage_client.py", line 2660, in list_buckets
    raise ValueError('Parameter {} cannot be None, whitespace or empty string'.format(k))
ValueError: Parameter namespaceName cannot be None, whitespace or empty string
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] INFO Running pre-processing engine
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] INFO Running rule engine
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] DEBUG Loading ruleset /cloudtool/ScoutSuite/ScoutSuite/providers/oci/rules/rulesets/default.json
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] DEBUG Processing Identity rule "Minimum Password Length Too Short" (identity-password-policy-minimum-length.json)
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] DEBUG Processing Identity rule "Password Policy Lacks Lowercase Requirement" (identity-password-policy-no-lowercase-required.json)
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] DEBUG Processing Identity rule "Password Policy Lacks Number Requirement" (identity-password-policy-no-number-required.json)
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] DEBUG Processing Identity rule "Password Policy Lacks Symbol Requirement" (identity-password-policy-no-symbol-required.json)
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] DEBUG Processing Identity rule "Password Policy Lacks Uppercase Requirement" (identity-password-policy-no-uppercase-required.json)
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] DEBUG Processing Identity rule "Policy Affects User" (identity-policy-affects-user.json)
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] DEBUG Processing Identity rule "User with Multiple API Keys" (identity-user-with-multiple-api-keys.json)
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] DEBUG Processing KMS rule "KMS Keys Are Not Being Rotated" (kms-no-key-rotation.json)
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] DEBUG Processing Object Storage rule "Buckets Lacking KMS Encryption" (objectstorage-bucket-lacking-kms-encryption.json)
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] DEBUG Processing Object Storage rule "Public Buckets" (objectstorage-public-bucket.json)
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] INFO Applying display filters
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] DEBUG Loading ruleset /cloudtool/ScoutSuite/ScoutSuite/providers/oci/rules/rulesets/filters.json
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] INFO Running post-processing engine
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_results_oracle-ocid1.tenancy.oc1..aaaaaaaaopxdqo6ypmjgwoiw7hix4xsuybae4lwurwh34qbnnuxvt445bp3q.js
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_exceptions_oracle-ocid1.tenancy.oc1..aaaaaaaaopxdqo6ypmjgwoiw7hix4xsuybae4lwurwh34qbnnuxvt445bp3q.js
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_errors_oracle-ocid1.tenancy.oc1..aaaaaaaaopxdqo6ypmjgwoiw7hix4xsuybae4lwurwh34qbnnuxvt445bp3q.json
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] INFO Creating scoutsuite-report/oracle-ocid1.tenancy.oc1..aaaaaaaaopxdqo6ypmjgwoiw7hix4xsuybae4lwurwh34qbnnuxvt445bp3q.html
2021-03-04 13:38:38 def-linux-jboxsrv02 scout[11962] INFO Opening the HTML report
(venv) [root@def-linux-jboxsrv02 ScoutSuite]#
(venv) [root@def-linux-jboxsrv02 ScoutSuite]#
(venv) [root@def-linux-jboxsrv02 ScoutSuite]#

Br,
Aditya Singh.

**Comment by danielpops** [comment]
4 years later I ran in to the same bug. AFAICT it's a bug in https://github.com/oracle/oci-python-sdk/ which doesn't handle the fact that the API returns a string and not a list.

I worked around it quick and dirty in my local environment with the following patch in https://github.com/oracle/oci-python-sdk/blob/5eb36cda5bc7a03ee23c3c2fed2333955fd8535d/src/oci/pagination/pagination_utils.py#L217:

```
$ diff -u pagination/pagination_utils.py pagination/pagination_utils.py.patched
--- pagination/pagination_utils.py      2025-02-28 17:03:43
+++ pagination/pagination_utils.py.patched      2025-02-28 17:03:39
@@ -215,7 +215,8 @@
                 list_objects_prefixes.update(call_result.data.prefixes)
         else:
             aggregated_results.extend(call_result.data) if isinstance(call_result.data, list) \
-                else aggregated_results.extend(call_result.data.items)
+                else aggregated_results.extend([call_result.data]) if isinstance(call_result.data, str) \
+                    else aggregated_results.extend(call_result.data.items)

     if is_dns_record_collection:
         final_response = Response(

```
