### ISSUE TITLE
Azure: Failed to retrieve users: Insufficient privileges to complete the operation

### ISSUE THREAD

**Issue by estemendoza** [nccgroup/ScoutSuite#1182]
Running scout on an azure subscription using a service account

The service account that I am using has:

 - Directory.Read.All Graph API permissions
 - Reader + Security Role role on the subscription level

Similar as #831 , except that I don't have the tenant_id issue, but still getting these errors:

```
2021-03-15 18:11:40 39f1837b13e4 scout[19] ERROR aad.py L27: Failed to retrieve users: Insufficient privileges to complete the operation.
2021-03-15 18:11:40 39f1837b13e4 scout[19] ERROR aad.py L41: Failed to retrieve groups: Insufficient privileges to complete the operation.
2021-03-15 18:11:40 39f1837b13e4 scout[19] ERROR aad.py L65: Failed to retrieve applications: Insufficient privileges to complete the operation.
2021-03-15 18:11:41 39f1837b13e4 scout[19] ERROR aad.py L58: Failed to retrieve service principals: Insufficient privileges to complete the operation.
```

**To Reproduce**

`scout azure --service-principal --client-id {} --client-secret {}  --tenant {} --subscriptions {}`

**Comment by j4v** [comment]
Are you sure the service principal has Azure AD Graph permissions, and not Microsoft Graph permissions (as per https://github.com/nccgroup/ScoutSuite/wiki/Azure#permissions)?

We're in the process of migrating to the identity API, but currently we're using the AD Graph one.

**Comment by estemendoza** [comment]
Thanks for the reply. I checked and the permissions were wrong, but I configured the proper permissions using AD Graph and I still get the same errors.

**Comment by j4v** [comment]
Please post the `--debug` output, most likely this is a configuration issue on your end.

**Comment by estemendoza** [comment]
This is the clipped debug message, this error is displayed 4 times with the same format for users, groups, applications and service principals:

```
2021-03-17 11:06:01 0de23dace82c scout[20] ERROR aad.py L58: Failed to retrieve service principals: Insufficient privileges to complete the operation.
Traceback (most recent call last):
  File "/app/scout/ScoutSuite/providers/azure/facade/aad.py", line 58, in get_service_principals
    return await run_concurrently(lambda: list(self.get_client().service_principals.list()))
  File "/app/scout/ScoutSuite/providers/utils.py", line 25, in run_concurrently
    return await run_function_concurrently(function)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/scout/ScoutSuite/providers/azure/facade/aad.py", line 58, in <lambda>
    return await run_concurrently(lambda: list(self.get_client().service_principals.list()))
  File "/usr/local/lib/python3.6/site-packages/msrest-0.6.21-py3.6.egg/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/usr/local/lib/python3.6/site-packages/msrest-0.6.21-py3.6.egg/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/usr/local/lib/python3.6/site-packages/azure_graphrbac-0.61.1-py3.6.egg/azure/graphrbac/operations/service_principals_operations.py", line 159, in internal_paging
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error_py3.GraphErrorException: Insufficient privileges to complete the operation.
```

And this is for specific users:

```
2021-03-17 11:07:23 0de23dace82c scout[20] ERROR aad.py L34: Failed to retrieve user XXXXXXXXXXXXXXXXX: Insufficient privileges to complete the operation.
Traceback (most recent call last):
  File "/app/scout/ScoutSuite/providers/azure/facade/aad.py", line 34, in get_user
    return await run_concurrently(lambda: self.get_client().users.get(user_id))
  File "/app/scout/ScoutSuite/providers/utils.py", line 25, in run_concurrently
    return await run_function_concurrently(function)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/scout/ScoutSuite/providers/azure/facade/aad.py", line 34, in <lambda>
    return await run_concurrently(lambda: self.get_client().users.get(user_id))
  File "/usr/local/lib/python3.6/site-packages/azure_graphrbac-0.61.1-py3.6.egg/azure/graphrbac/operations/users_operations.py", line 218, in get
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error_py3.GraphErrorException: Insufficient privileges to complete the operation.
```

Let me know if this helps

**Comment by j4v** [comment]
Looks like a permission issue, not something to do with Scout.

**Comment by estemendoza** [comment]
How can I make sure of this? I followed the guidelines on the wiki and configured both roles and the AD permission, how can I check that the service principal has the proper permissions?

**Comment by j4v** [comment]
If you've followed the guidance I'm guessing it's either that you've missed a step, or there's something else configured in your account that's disallowing you from making the requests. 

Closing as this is not a Scout issue.
