### ISSUE TITLE
Running against Azure - ARMPipelineClient object has no attribute config

### ISSUE THREAD

**Issue by lavermil** [nccgroup/ScoutSuite#1287]
I am not sure why I am getting these messages. I am authenticated within venv via az and can run commands via az just fine. I have tried using --user-account, --cli, --user-account-browser, and even tried just a single service network but still get the same problem. The ARMPipelineClient message seems to be from az but I am guessing something is not working quite right. I see data in the report for AAD, and SQL. The network section does however say it found 1 item for Network Watcher not being enabled but it is, in fact enabled in 3 regions. I have the roles as specified assigned (reader and security reader) at the subscription and global reader for AAD.

Version: Scout Suite 5.10.2

2021-04-17 01:41:34 localhost.localdomain scout[51226] INFO Launching Scout
2021-04-17 01:41:34 localhost.localdomain scout[51226] INFO Authenticating to cloud provider
2021-04-17 01:41:35 localhost.localdomain scout[51226] INFO Running against subscription <removed>
2021-04-17 01:41:35 localhost.localdomain scout[51226] INFO Gathering data from APIs
2021-04-17 01:41:35 localhost.localdomain scout[51226] INFO Fetching resources for the Azure Active Directory service
2021-04-17 01:41:35 localhost.localdomain scout[51226] INFO Fetching resources for the Azure RBAC service
2021-04-17 01:41:35 localhost.localdomain scout[51226] INFO Fetching resources for the Security Center service
2021-04-17 01:41:35 localhost.localdomain scout[51226] INFO Fetching resources for the SQL Database service
2021-04-17 01:41:35 localhost.localdomain scout[51226] INFO Fetching resources for the Storage Accounts service
2021-04-17 01:41:35 localhost.localdomain scout[51226] INFO Fetching resources for the Key Vault service
2021-04-17 01:41:35 localhost.localdomain scout[51226] INFO Fetching resources for the Network service
2021-04-17 01:41:35 localhost.localdomain scout[51226] INFO Fetching resources for the Virtual Machines service
2021-04-17 01:41:35 localhost.localdomain scout[51226] INFO Fetching resources for the App Services service
2021-04-17 01:41:35 localhost.localdomain scout[51226] ERROR storageaccounts.py L24: Failed to retrieve storage accounts: 'ARMPipelineClient' object has no attribute 'config'
Traceback (most recent call last):
  File "/home/user1/venv/lib/python3.8/site-packages/ScoutSuite/providers/azure/facade/storageaccounts.py", line 24, in get_storage_accounts
    client = self.get_client(subscription_id)
  File "/home/user1/venv/lib/python3.8/site-packages/ScoutSuite/providers/azure/facade/storageaccounts.py", line 19, in get_client
    client._client.config.add_user_agent(get_user_agent())
AttributeError: 'ARMPipelineClient' object has no attribute 'config'
2021-04-17 01:41:35 localhost.localdomain scout[51226] ERROR keyvault.py L21: Failed to retrieve key vaults: 'ARMPipelineClient' object has no attribute 'config'
Traceback (most recent call last):
  File "/home/user1/venv/lib/python3.8/site-packages/ScoutSuite/providers/azure/facade/keyvault.py", line 21, in get_key_vaults
    client = self.get_client(subscription_id)
  File "/home/user1/venv/lib/python3.8/site-packages/ScoutSuite/providers/azure/facade/keyvault.py", line 16, in get_client
    client._client.config.add_user_agent(get_user_agent())
AttributeError: 'ARMPipelineClient' object has no attribute 'config'
2021-04-17 01:41:35 localhost.localdomain scout[51226] ERROR network.py L51: Failed to retrieve virtual networks: 'ARMPipelineClient' object has no attribute 'config'
Traceback (most recent call last):
  File "/home/user1/venv/lib/python3.8/site-packages/ScoutSuite/providers/azure/facade/network.py", line 51, in get_virtual_networks
    client = self.get_client(subscription_id)
  File "/home/user1/venv/lib/python3.8/site-packages/ScoutSuite/providers/azure/facade/network.py", line 16, in get_client
    client._client.config.add_user_agent(get_user_agent())
AttributeError: 'ARMPipelineClient' object has no attribute 'config'

Thanks in advance for any help.
-Lance

**Comment by lowSoA** [comment]
Could you check if this is related to https://github.com/Azure/azure-cli/issues/15461, and if so, try out https://github.com/Azure/azure-cli/issues/13995#issuecomment-663353202?

**Comment by ngkogkos** [comment]
I was just having the same issue as well using ScoutSuite's docker image. Thanks for pointing us at those links @lowSoA.

Basically the issue is because python `azure-mgmt-*` packages installed with `az-cli` are of higher version.

Since I was using the docker image, here's what I think are the steps to resolve this:

* Make new virtual python env
* Grab ScoutSuite's Azure requirements in (or the ones that are causing issues) https://github.com/nccgroup/ScoutSuite/blob/master/requirements.txt 
* `pip install -r requirements.txt --force-reinstall` 

Based on `azure-cli` version you may see it moan about using lower versions of packages, but if you are using ScoutSuite docker you shouldn't need to worry about other tools/AZ actions I guess.

**Comment by lavermil** [comment]
Running "pip install -r requirements.txt --force-reinstall" worked like a charm in venv, thx! However there are lots of complaints. The current azure core version 2.12.0 is back from Sep 2020. I would like to think that the use of the libraries would updated to a few months back not 6-7 months behind in compatibility. At minimum it would be good to add your nice command to the install instructions. :)

Thx again though. :)

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
oci 2.36.0 requires cryptography==3.2.1, but you have cryptography 3.4.7 which is incompatible.
oci 2.36.0 requires pyOpenSSL<=19.1.0,>=17.5.0, but you have pyopenssl 20.0.1 which is incompatible.
azure-identity 1.5.0 requires msal<2.0.0,>=1.6.0, but you have msal 1.0.0 which is incompatible.
azure-identity 1.5.0 requires msal-extensions~=0.3.0, but you have msal-extensions 0.1.3 which is incompatible.
azure-cli 2.22.1 requires azure-cli-core==2.22.1, but you have azure-cli-core 2.12.0 which is incompatible.
azure-cli 2.22.1 requires azure-graphrbac~=0.60.0, but you have azure-graphrbac 0.61.1 which is incompatible.
azure-cli 2.22.1 requires azure-mgmt-authorization~=0.61.0, but you have azure-mgmt-authorization 0.60.0 which is incompatible.
azure-cli 2.22.1 requires azure-mgmt-compute~=20.0.0, but you have azure-mgmt-compute 5.0.0 which is incompatible.
azure-cli 2.22.1 requires azure-mgmt-keyvault==8.0.0, but you have azure-mgmt-keyvault 1.1.0 which is incompatible.
azure-cli 2.22.1 requires azure-mgmt-monitor~=2.0.0, but you have azure-mgmt-monitor 0.5.2 which is incompatible.
azure-cli 2.22.1 requires azure-mgmt-network~=18.0.0, but you have azure-mgmt-network 2.5.1 which is incompatible.
azure-cli 2.22.1 requires azure-mgmt-redis~=7.0.0rc1, but you have azure-mgmt-redis 6.0.0 which is incompatible.
azure-cli 2.22.1 requires azure-mgmt-resource==12.1.0, but you have azure-mgmt-resource 10.2.0 which is incompatible.
azure-cli 2.22.1 requires azure-mgmt-security~=0.6.0, but you have azure-mgmt-security 0.4.1 which is incompatible.
azure-cli 2.22.1 requires azure-mgmt-sql~=0.26.0, but you have azure-mgmt-sql 0.11.0 which is incompatible.
azure-cli 2.22.1 requires azure-mgmt-storage~=17.0.0, but you have azure-mgmt-storage 7.1.0 which is incompatible.
azure-cli 2.22.1 requires azure-mgmt-web~=0.48.0, but you have azure-mgmt-web 0.47.0 which is incompatible.
azure-cli 2.22.1 requires pytz==2019.1, but you have pytz 2021.1 which is incompatible.

**Comment by lavermil** [comment]
> Could you check if this is related to [Azure/azure-cli#15461](https://github.com/Azure/azure-cli/issues/15461), and if so, try out [Azure/azure-cli#13995 (comment)](https://github.com/Azure/azure-cli/issues/13995#issuecomment-663353202)?

I don't think they are the same. I am not well versed in this software though. It appears ScoutSuite is calling Azure CLI modules/etc directly but ScoutSuite appears to not be up to the current usage requirements of the Azure CLI modules/etc.

**Comment by Popvlvs** [comment]
Hi,

The issue comes from:

`scoutsuite 5.10.2 requires azure-mgmt-keyvault==1.1.0, but you have azure-mgmt-keyvault 9.0.0 which is incompatible.`

You can solve it by installing the suggested version. However, this is a very old package (https://docs.microsoft.com/en-us/python/api/azure-mgmt-keyvault/azure.mgmt.keyvault.v2016_10_01.keyvaultmanagementclient?view=azure-python), so basically it is not possible to fetch some data such as Secret Keys.

Is there any possibility of making Scout Suite compatible with the latest version of azure-mgmt-keyvault?

**Comment by OlivierLaflamme** [comment]
after having ran 
```
az login --allow-no-subscriptions --use-device-code
```
running `python3 scout.py azure --cli` results in 

```
2021-12-08 21:38:58 python-sandbox scout[862645] INFO Launching Scout
2021-12-08 21:38:58 python-sandbox scout[862645] INFO Authenticating to cloud provider
2021-12-08 21:38:58 python-sandbox scout[862645] ERROR __main__.py L212: Initialization failure: 'ARMPipelineClient' object has no attribute 'config'
```
is scoutsuite simply not able to follow all the az updates. has anyone been able to resolve this for azure? 

cheers,

**Comment by Cobey-Errett** [comment]
Has anyone got any resolution to this issue?

**Comment by fernando-gallego** [comment]
Hi,

This has been fixed in the develop branch by updating the authentication libraries and functions to use the new SDK versions.

Changes have not yet made it to master; please give it a try with the develop branch to see if the error persists. Also check the new **requirements.txt** file which contains updated versions for multiple packages. These will be needed for the upgraded authentication scheme to work as expected.
