### ISSUE TITLE
Failed to retrieve regulatory compliance standards: 400 Client Error

### ISSUE THREAD

**Issue by zaidozaid** [nccgroup/ScoutSuite#1339]
Command run: python scout.py azure --cli --debug
Scout Suite 5.10.2

ERROR:

`
2021-09-01 08:02:02 LinuxBox scout[980] INFO Launching Scout
2021-09-01 08:02:02 LinuxBox scout[980] INFO Authenticating to cloud provider
2021-09-01 08:02:04 LinuxBox scout[980] INFO Running against subscription XXXXXX.XXXXXX.XXXXXX.XXXXX
2021-09-01 08:02:04 LinuxBox scout[980] INFO Gathering data from APIs
2021-09-01 08:02:04 LinuxBox scout[980] INFO Fetching resources for the Azure Active Directory service
2021-09-01 08:02:04 LinuxBox scout[980] INFO Fetching resources for the Azure RBAC service
2021-09-01 08:02:04 LinuxBox scout[980] INFO Fetching resources for the Security Center service
2021-09-01 08:02:04 LinuxBox scout[980] INFO Fetching resources for the SQL Database service
2021-09-01 08:02:04 LinuxBox scout[980] INFO Fetching resources for the Storage Accounts service
2021-09-01 08:02:04 LinuxBox scout[980] INFO Fetching resources for the Key Vault service
2021-09-01 08:02:04 LinuxBox scout[980] INFO Fetching resources for the Network service
2021-09-01 08:02:04 LinuxBox scout[980] INFO Fetching resources for the Virtual Machines service
2021-09-01 08:02:04 LinuxBox scout[980] INFO Fetching resources for the App Services service
2021-09-01 08:02:05 LinuxBox scout[980] ERROR securitycenter.py L99: Failed to retrieve regulatory compliance standards: 400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/305ae9c0-f4f6-4870-91e2-4c2f10d10ddd/providers/Microsoft.Security/regulatoryComplianceStandards?api-version=2019-01-01-preview
Traceback (most recent call last):
  File "/home/azureuser/git/ScoutSuite/ScoutSuite/providers/azure/facade/securitycenter.py", line 99, in get_regulatory_compliance_results
    lambda: list(client.regulatory_compliance_standards.list())
  File "/home/azureuser/git/ScoutSuite/ScoutSuite/providers/utils.py", line 25, in run_concurrently
    return await run_function_concurrently(function)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/azureuser/git/ScoutSuite/ScoutSuite/providers/azure/facade/securitycenter.py", line 99, in <lambda>
    lambda: list(client.regulatory_compliance_standards.list())
  File "/home/azureuser/git/ScoutSuite/venv/venv/lib/python3.6/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/home/azureuser/git/ScoutSuite/venv/venv/lib/python3.6/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/home/azureuser/git/ScoutSuite/venv/venv/lib/python3.6/site-packages/azure/mgmt/security/operations/_regulatory_compliance_standards_operations.py", line 99, in internal_paging
    raise exp
msrestazure.azure_exceptions.CloudError: 400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/XXXXXXX.XXXXX.XXXX.XXXX/providers/Microsoft.Security/regulatoryComplianceStandards?api-version=2019-01-01-preview

**Comment by fernando-gallego** [comment]
Hi @zaidozaid , this should have been fixed in version 5.12.0. Can you confirm if you are still experiencing this issue?
