### ISSUE TITLE
Unable to list accessible Projects Using --service-account option on GCP

### ISSUE THREAD

**Issue by shpml** [nccgroup/ScoutSuite#1388]
I'm trying to run scout against a GCP project with the `--service-account` option but I get the below error. I don't get this error using the `--user-account` option. The error appears multiple times, I assume due to a retry.

> base.py L115: Unable to list accessible Projects: Cloud Resource Manager API has not been used in project xxxxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=xxxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

I installed scout via pip and the command I'm running is `scout gcp --debug --service-account ./key.json --project-id my-project`

I created a service account with the following [GCP pre-defined roles](https://cloud.google.com/iam/docs/understanding-roles?hl=en#predefined) which I hope match up to the ones in the [docs](https://github.com/nccgroup/ScoutSuite/wiki/Google-Cloud-Platform#permissions), but I'm not 100%.

- `roles/viewer`
- `roles/securitycenter.findingsViewer`
- `roles/stackdriver.accounts.viewer`

Full debug output is:
```
2022-01-05 17:02:35 local.local scout[49892] ERROR base.py L115: Unable to list accessible Projects: Cloud Resource Manager API has not been used in project xxxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=xxxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ScoutSuite/providers/gcp/facade/base.py", line 115, in _get_projects_recursively
    project_response = await GCPFacadeUtils.get_all('projects', request, projects_group)
  File "/usr/local/lib/python3.9/site-packages/ScoutSuite/providers/gcp/facade/utils.py", line 17, in get_all
    await GCPFacadeUtils._get_all(resources, resource_key, request, resources_group)
  File "/usr/local/lib/python3.9/site-packages/ScoutSuite/providers/gcp/facade/utils.py", line 8, in _get_all
    response = request.execute()
  File "/usr/local/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/googleapiclient/http.py", line 937, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://cloudresourcemanager.googleapis.com/v1/projects?filter=id%3A%22my-project%22&alt=json returned "Cloud Resource Manager API has not been used in project xxxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=xxxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.". Details: "[{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developers console API activation', 'url': 'https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=xxxx'}]}, {'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'SERVICE_DISABLED', 'domain': 'googleapis.com', 'metadata': {'service': 'cloudresourcemanager.googleapis.com', 'consumer': 'projects/xxxx'}}]">
```

The errors.json file contains the following multiple times also.
```
[
    {
        "additional_details": null,
        "exception": "Unable to list accessible Projects: Cloud Resource Manager API has not been used in project xxxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=xxxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
        "file": "base.py",
        "line": 115,
        "traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.9/site-packages/ScoutSuite/providers/gcp/facade/base.py\", line 115, in _get_projects_recursively\n    project_response = await GCPFacadeUtils.get_all('projects', request, projects_group)\n  File \"/usr/local/lib/python3.9/site-packages/ScoutSuite/providers/gcp/facade/utils.py\", line 17, in get_all\n    await GCPFacadeUtils._get_all(resources, resource_key, request, resources_group)\n  File \"/usr/local/lib/python3.9/site-packages/ScoutSuite/providers/gcp/facade/utils.py\", line 8, in _get_all\n    response = request.execute()\n  File \"/usr/local/lib/python3.9/site-packages/googleapiclient/_helpers.py\", line 131, in positional_wrapper\n    return wrapped(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/googleapiclient/http.py\", line 937, in execute\n    raise HttpError(resp, content, uri=self.uri)\ngoogleapiclient.errors.HttpError: <HttpError 403 when requesting https://cloudresourcemanager.googleapis.com/v1/projects?filter=id%3A%22my-project%22&alt=json returned \"Cloud Resource Manager API has not been used in project xxxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=xxxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.\". Details: \"[{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developers console API activation', 'url': 'https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=xxxx'}]}, {'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'SERVICE_DISABLED', 'domain': 'googleapis.com', 'metadata': {'consumer': 'projects/xxxx', 'service': 'cloudresourcemanager.googleapis.com'}}]\">\n"
    },
 ]
```

I tried adding addition resource manager roles to the service account but had no luck.
- `Error 400: Role (roles/resourcemanager.folderViewer) does not exist in the resource's hierarchy., badRequest`
- `Error 400: Role roles/resourcemanager.organizationViewer has been retired., badRequest`

**Comment by shpml** [comment]
I have the same issue with python 3.8 also

```
2022-01-05 07:37:31 407818111d7c scout[17] ERROR base.py L115: Unable to list accessible Projects: Cloud Resource Manager API has not been used in project xxxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=xxxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ScoutSuite/providers/gcp/facade/base.py", line 115, in _get_projects_recursively
    project_response = await GCPFacadeUtils.get_all('projects', request, projects_group)
  File "/usr/local/lib/python3.8/site-packages/ScoutSuite/providers/gcp/facade/utils.py", line 17, in get_all
    await GCPFacadeUtils._get_all(resources, resource_key, request, resources_group)
  File "/usr/local/lib/python3.8/site-packages/ScoutSuite/providers/gcp/facade/utils.py", line 8, in _get_all
    response = request.execute()
  File "/usr/local/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/googleapiclient/http.py", line 937, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://cloudresourcemanager.googleapis.com/v1/projects?filter=id%3A%22my-project%22&alt=json returned "Cloud Resource Manager API has not been used in project xxxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=xxxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.". Details: "[{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developers console API activation', 'url': 'https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=xxxx'}]}, {'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'SERVICE_DISABLED', 'domain': 'googleapis.com', 'metadata': {'service': 'cloudresourcemanager.googleapis.com', 'consumer': 'projects/xxxx'}}]">
```

**Comment by superpoussin22** [comment]
did you try with this branch ? : https://github.com/nccgroup/ScoutSuite/tree/develop-with-gcp-enhancements-pre-release
