### ISSUE TITLE
The security token included in the request is invalid if using me-south-1 region (and/or other regions) in AWS

### ISSUE THREAD

**Issue by malcolm061990** [nccgroup/ScoutSuite#1389]
**Describe the bug**

First of all big thanks for this great product :)
We have two AWS accounts. RoleA as EC2 instance IAM Role (accountA) assumes RoleB (accountB):
```bash
cat ~/.aws/config
[profile cis-dev]
role_arn = arn:aws:iam::AWS_ACCCOUNT_ID:role/jenkins-trusting-cis-dev
credential_source = Ec2InstanceMetadata
```
We use scoutsuite in docker (mount the ~/.aws/config from EC2 host to container):
```bash
docker run --rm -it -v ~/.aws/config:/root/.aws/config rossja/ncc-scoutsuite:0.6.0 /bin/bash

# check if authorisation works in us-east-1 - all is ok
aws --profile cis-dev --region us-east-1 sts get-caller-identity
{
    "UserId": "AWS_USER_ID:botocore-session-1641384507",
    "Account": "AWS_ACCCOUNT_ID",
    "Arn": "arn:aws:sts:: AWS_ACCCOUNT_ID:assumed-role/jenkins-trusting-cis-dev/botocore-session-1641384507"
}

# check if authorisation works in me-south-1 - all is ok
aws --profile cis-dev --region me-south-1 sts get-caller-identity
{
    "UserId": "AWS_USER_ID:botocore-session-1641384507",
    "Account": "AWS_ACCCOUNT_ID",
    "Arn": "arn:aws:sts:: AWS_ACCCOUNT_ID:assumed-role/jenkins-trusting-cis-dev/botocore-session-1641384507"
}

# run scout in us-east-1  - all is ok
scout aws -p cis-dev -r us-east-1 --services cloudwatch -f
2022-01-05 12:09:01 4b5e92c695d5 scout[29] INFO Launching Scout
2022-01-05 12:09:01 4b5e92c695d5 scout[29] INFO Authenticating to cloud provider
2022-01-05 12:09:03 4b5e92c695d5 scout[29] INFO Gathering data from APIs
2022-01-05 12:09:03 4b5e92c695d5 scout[29] INFO Fetching resources for the CloudWatch service
2022-01-05 12:09:03 4b5e92c695d5 scout[29] INFO Running pre-processing engine
2022-01-05 12:09:03 4b5e92c695d5 scout[29] INFO Running rule engine
2022-01-05 12:09:03 4b5e92c695d5 scout[29] INFO Applying display filters
2022-01-05 12:09:03 4b5e92c695d5 scout[29] INFO Running post-processing engine
2022-01-05 12:09:03 4b5e92c695d5 scout[29] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_results_aws-cis-dev.js
2022-01-05 12:09:03 4b5e92c695d5 scout[29] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_exceptions_aws-cis-dev.js
2022-01-05 12:09:03 4b5e92c695d5 scout[29] INFO Creating scoutsuite-report/aws-cis-dev.html
2022-01-05 12:09:03 4b5e92c695d5 scout[29] INFO Opening the HTML report

# run scout in us-east-1 and us-east-2 - all is ok
scout aws -p cis-dev -r us-east-1 us-east-2 --services cloudwatch -f
2022-01-05 12:09:14 4b5e92c695d5 scout[33] INFO Launching Scout
2022-01-05 12:09:14 4b5e92c695d5 scout[33] INFO Authenticating to cloud provider
2022-01-05 12:09:15 4b5e92c695d5 scout[33] INFO Gathering data from APIs
2022-01-05 12:09:15 4b5e92c695d5 scout[33] INFO Fetching resources for the CloudWatch service
2022-01-05 12:09:15 4b5e92c695d5 scout[33] INFO Running pre-processing engine
2022-01-05 12:09:15 4b5e92c695d5 scout[33] INFO Running rule engine
2022-01-05 12:09:16 4b5e92c695d5 scout[33] INFO Applying display filters
2022-01-05 12:09:16 4b5e92c695d5 scout[33] INFO Running post-processing engine
2022-01-05 12:09:16 4b5e92c695d5 scout[33] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_results_aws-cis-dev.js
2022-01-05 12:09:16 4b5e92c695d5 scout[33] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_exceptions_aws-cis-dev.js
2022-01-05 12:09:16 4b5e92c695d5 scout[33] INFO Creating scoutsuite-report/aws-cis-dev.html
2022-01-05 12:09:16 4b5e92c695d5 scout[33] INFO Opening the HTML report

# run scout in me-south-1 - NOT OK. Without specifying regions issue is the same
# here DescribeAlarms and DescribeMetricFilters can't be launched
scout aws -p cis-dev -r us-east-1 me-south-1 --services cloudwatch -f --debug
2022-01-05 12:29:25 4b5e92c695d5 scout[60] INFO Launching Scout
2022-01-05 12:29:25 4b5e92c695d5 scout[60] INFO Authenticating to cloud provider
2022-01-05 12:29:26 4b5e92c695d5 scout[60] INFO Gathering data from APIs
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the ACM service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the Lambda service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the CloudFormation service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the CloudTrail service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the Config service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the Direct Connect service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the DynamoDB service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the EC2 service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the EFS service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the ElastiCache service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the ELB service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the ELBv2 service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the EMR service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the IAM service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the KMS service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the RDS service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the RedShift service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the Route53 service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the S3 service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the SES service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the SNS service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the SQS service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the VPC service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] DEBUG Skipping the Secrets Manager service
2022-01-05 12:29:26 4b5e92c695d5 scout[60] INFO Fetching resources for the CloudWatch service
2022-01-05 12:29:27 4b5e92c695d5 scout[60] ERROR cloudwatch.py L18: Failed to get CloudWatch metric filters: An error occurred (UnrecognizedClientException) when calling the DescribeMetricFilters operation: The security token included in the request is invalid
Traceback (most recent call last):
  File "/root/scoutsuite/lib/python3.8/site-packages/ScoutSuite/providers/aws/facade/cloudwatch.py", line 18, in get_metric_filters
    return await AWSFacadeUtils.get_all_pages('logs', region, self.session, 'describe_metric_filters',
  File "/root/scoutsuite/lib/python3.8/site-packages/ScoutSuite/providers/aws/facade/utils.py", line 27, in get_all_pages
    results = await AWSFacadeUtils.get_multiple_entities_from_all_pages(
  File "/root/scoutsuite/lib/python3.8/site-packages/ScoutSuite/providers/aws/facade/utils.py", line 58, in get_multiple_entities_from_all_pages
    return await run_concurrently(lambda: AWSFacadeUtils._get_all_pages_from_paginator(paginator, entities))
  File "/root/scoutsuite/lib/python3.8/site-packages/ScoutSuite/providers/utils.py", line 25, in run_concurrently
    return await run_function_concurrently(function)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/scoutsuite/lib/python3.8/site-packages/ScoutSuite/providers/aws/facade/utils.py", line 58, in <lambda>
    return await run_concurrently(lambda: AWSFacadeUtils._get_all_pages_from_paginator(paginator, entities))
  File "/root/scoutsuite/lib/python3.8/site-packages/ScoutSuite/providers/aws/facade/utils.py", line 74, in _get_all_pages_from_paginator
    for page in paginator:
  File "/root/scoutsuite/lib/python3.8/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/root/scoutsuite/lib/python3.8/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/root/scoutsuite/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/scoutsuite/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.UnrecognizedClientException: An error occurred (UnrecognizedClientException) when calling the DescribeMetricFilters operation: The security token included in the request is invalid
2022-01-05 12:29:27 4b5e92c695d5 scout[60] ERROR cloudwatch.py L10: Failed to get CloudWatch alarms: An error occurred (InvalidClientTokenId) when calling the DescribeAlarms operation: The security token included in the request is invalid
Traceback (most recent call last):
  File "/root/scoutsuite/lib/python3.8/site-packages/ScoutSuite/providers/aws/facade/cloudwatch.py", line 10, in get_alarms
    return await AWSFacadeUtils.get_all_pages('cloudwatch', region, self.session, 'describe_alarms',
  File "/root/scoutsuite/lib/python3.8/site-packages/ScoutSuite/providers/aws/facade/utils.py", line 27, in get_all_pages
    results = await AWSFacadeUtils.get_multiple_entities_from_all_pages(
  File "/root/scoutsuite/lib/python3.8/site-packages/ScoutSuite/providers/aws/facade/utils.py", line 58, in get_multiple_entities_from_all_pages
    return await run_concurrently(lambda: AWSFacadeUtils._get_all_pages_from_paginator(paginator, entities))
  File "/root/scoutsuite/lib/python3.8/site-packages/ScoutSuite/providers/utils.py", line 25, in run_concurrently
    return await run_function_concurrently(function)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/scoutsuite/lib/python3.8/site-packages/ScoutSuite/providers/aws/facade/utils.py", line 58, in <lambda>
    return await run_concurrently(lambda: AWSFacadeUtils._get_all_pages_from_paginator(paginator, entities))
  File "/root/scoutsuite/lib/python3.8/site-packages/ScoutSuite/providers/aws/facade/utils.py", line 74, in _get_all_pages_from_paginator
    for page in paginator:
  File "/root/scoutsuite/lib/python3.8/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/root/scoutsuite/lib/python3.8/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/root/scoutsuite/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/scoutsuite/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the DescribeAlarms operation: The security token included in the request is invalid
2022-01-05 12:29:27 4b5e92c695d5 scout[60] INFO Running pre-processing engine
2022-01-05 12:29:27 4b5e92c695d5 scout[60] INFO Running rule engine
2022-01-05 12:29:27 4b5e92c695d5 scout[60] DEBUG Loading ruleset /root/scoutsuite/lib/python3.8/site-packages/ScoutSuite/providers/aws/rules/rulesets/default.json
2022-01-05 12:29:27 4b5e92c695d5 scout[60] DEBUG Processing CloudWatch rule "Alarm without Action" (cloudwatch-alarm-without-actions.json)
2022-01-05 12:29:27 4b5e92c695d5 scout[60] INFO Applying display filters
2022-01-05 12:29:27 4b5e92c695d5 scout[60] DEBUG Loading ruleset /root/scoutsuite/lib/python3.8/site-packages/ScoutSuite/providers/aws/rules/rulesets/filters.json
2022-01-05 12:29:27 4b5e92c695d5 scout[60] INFO Running post-processing engine
2022-01-05 12:29:27 4b5e92c695d5 scout[60] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_results_aws-cis-dev.js
2022-01-05 12:29:27 4b5e92c695d5 scout[60] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_exceptions_aws-cis-dev.js
2022-01-05 12:29:27 4b5e92c695d5 scout[60] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_errors_aws-cis-dev.json
2022-01-05 12:29:27 4b5e92c695d5 scout[60] INFO Creating scoutsuite-report/aws-cis-dev.html
2022-01-05 12:29:27 4b5e92c695d5 scout[60] INFO Opening the HTML report

# try to DescribeAlarms in me-south-1 - all is ok
aws --profile cis-dev --region me-south-1 cloudwatch describe-alarms --alarm-names "sdns-cpu-scale-down"
{
...some-output-here
}
```

All is ok is in:
- aws sts get-caller-identity in both regions via aws cli
- scout in us-east-1; us-east-1 and us-east-2
- DescribeAlarms in me-south-1 via aws cli

Not ok is in:
- scout in me-south-1
- without specifying regions

Issue:
why doesn't scout work in me-south-1 region (and without specifying regions), but aws cli works normally?

**Comment by Yashvendra** [comment]
Hey @malcolm061990, I think the reason you are hitting `InvalidClientTokenId` exception is because your requesting account is issuing STS tokens that are valid for default AWS regions only and `me-south-1` is a region which one has to enable manually.

As you mentioned RoleA of AccountA is assuming another RoleB in AccountB, make sure that in AccountA `Account Settings` you have this options selected 
![image](https://user-images.githubusercontent.com/23001311/156006051-295f0333-128a-4cf9-af9a-73be1bb0e4f4.png)

I think this should work.

**Comment by malcolm061990** [comment]
> Hey @malcolm061990, I think the reason you are hitting `InvalidClientTokenId` exception is because your requesting account is issuing STS tokens that are valid for default AWS regions only and `me-south-1` is a region which one has to enable manually.
> 
> As you mentioned RoleA of AccountA is assuming another RoleB in AccountB, make sure that in AccountA `Account Settings` you have this options selected ![image](https://user-images.githubusercontent.com/23001311/156006051-295f0333-128a-4cf9-af9a-73be1bb0e4f4.png)
> 
> I think this should work.

Thanks for your answer :)
Configured all AWS regions for tokens. Will share the results on the next scoutsuite execution

**Comment by Yashvendra** [comment]
Hey @malcolm061990 is the issue resolved? If yes, then I think we can close this.

**Comment by malcolm061990** [comment]
> Hey @malcolm061990 is the issue resolved? If yes, then I think we can close this.

Big thanks! Your advice solved the problem! :)
