### ISSUE TITLE
KeyError: 'CreateVolumePermissions'

### ISSUE THREAD

**Issue by newlog** [nccgroup/ScoutSuite#1391]
After executing `scout aws` and letting it run for a couple of hours, it eventually crashes with:

```
(...)
2022-01-09 19:02:35 <hostname> scout[43069] ERROR ec2.py L25: Failed to describe EC2 instance attributes: Could not connect to the endpoint URL: "https://ec2.us-east-1.amazonaws.com/"
2022-01-09 19:02:40 <hostname> scout[43069] ERROR ec2.py L25: Failed to describe EC2 instance attributes: Could not connect to the endpoint URL: "https://ec2.us-east-1.amazonaws.com/"
2022-01-09 19:02:41 <hostname> asyncio[43069] ERROR Task exception was never retrieved
future: <Task finished name='Task-2506' coro=<Snapshots.fetch_all() done, defined at /usr/local/lib/python3.9/site-packages/ScoutSuite/providers/aws/resources/ec2/snapshots.py:11> exception=KeyError('CreateVolumePermissions')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ScoutSuite/providers/aws/resources/ec2/snapshots.py", line 14, in fetch_all
    name, resource = self._parse_snapshot(raw_snapshot)
  File "/usr/local/lib/python3.9/site-packages/ScoutSuite/providers/aws/resources/ec2/snapshots.py", line 22, in _parse_snapshot
    snapshot_dict['public'] = self._is_public(raw_snapshot)
  File "/usr/local/lib/python3.9/site-packages/ScoutSuite/providers/aws/resources/ec2/snapshots.py", line 41, in _is_public
    return any([permission.get('Group') == 'all' for permission in snapshot['CreateVolumePermissions']])
KeyError: 'CreateVolumePermissions'
2022-01-09 19:02:42 <hostname> scout[43069] INFO Running pre-processing engine
2022-01-09 19:02:42 <hostname> scout[43069] ERROR __main__.py L298: Failure while running pre-processing engine: 'rules'
```

Before this final crash, there are hundreds of errors similar to:

```
ERROR ec2.py L25: Failed to describe EC2 instance attributes: Could not connect to the endpoint URL: "https://ec2.us-east-1.amazonaws.com/"
or
ERROR rds.py L134: Failed to get RDS subnet groups: Could not connect to the endpoint URL: "https://rds.us-west-2.amazonaws.com/"
```

There are no errors JSON file generated at the end of execution.

**To Reproduce**

This error will most likely be hard to reproduce at it is dependant on the AWS environment you run the command against.

- CLI Parameters

`scout aws --logfile <filename_path>`

**Additional context**

```
python3 --version
Python 3.9.9
```

```
scout --version
Scout Suite 5.10.2
```

The error is quite clear, so on my end I'll try to replace `snapshot['CreateVolumePermissions']` with `snapshot.get('CreateVolumePermissions', [])` and see if that allows for resuming successfully.

**Comment by fernando-gallego** [comment]
Hi @newlog , are you still experiencing this issue with version 5.12.0?
