### ISSUE TITLE
Azure - Boot Diagnostics error when scanning virtual machines

### ISSUE THREAD

**Issue by mfuellbier** [nccgroup/ScoutSuite#1411]
When running `scout azure --cli --subscription xxx --debug --skip securitycenter`, I receive following error:
```
2022-04-21 10:54:16 FE-C-006X8 scout[299] INFO Launching Scout
2022-04-21 10:54:16 FE-C-006X8 scout[299] INFO Authenticating to cloud provider
2022-04-21 10:54:19 FE-C-006X8 scout[299] INFO Running against subscription xxx
2022-04-21 10:54:19 FE-C-006X8 scout[299] INFO Gathering data from APIs
2022-04-21 10:54:19 FE-C-006X8 scout[299] DEBUG Skipping the Security Center service
2022-04-21 10:54:19 FE-C-006X8 scout[299] INFO Fetching resources for the Azure Active Directory service
2022-04-21 10:54:19 FE-C-006X8 scout[299] INFO Fetching resources for the Azure RBAC service
2022-04-21 10:54:19 FE-C-006X8 scout[299] INFO Fetching resources for the SQL Database service
2022-04-21 10:54:19 FE-C-006X8 scout[299] INFO Fetching resources for the Storage Accounts service
2022-04-21 10:54:19 FE-C-006X8 scout[299] INFO Fetching resources for the Key Vault service
2022-04-21 10:54:19 FE-C-006X8 scout[299] INFO Fetching resources for the Network service
2022-04-21 10:54:19 FE-C-006X8 scout[299] INFO Fetching resources for the Virtual Machines service
2022-04-21 10:54:19 FE-C-006X8 scout[299] INFO Fetching resources for the App Services service
Task exception was never retrieved
future: <Task finished name='Task-31' coro=<Instances.fetch_all() done, defined at /home/fuellbier/.local/lib/python3.8/site-packages/ScoutSuite/providers/azure/resources/virtualmachines/instances.py:14> exception=AttributeError("'NoneType' object has no attribute 'boot_diagnostics'")>
Traceback (most recent call last):
  File "/home/fuellbier/.local/lib/python3.8/site-packages/ScoutSuite/providers/azure/resources/virtualmachines/instances.py", line 16, in fetch_all
    id, instance = await self._parse_instance(raw_instance)
  File "/home/fuellbier/.local/lib/python3.8/site-packages/ScoutSuite/providers/azure/resources/virtualmachines/instances.py", line 67, in _parse_instance
    instance_dict['diagnostics_profile'] = {'Boot Diagnostics': True if raw_instance.diagnostics_profile.boot_diagnostics.enabled else None}
AttributeError: 'NoneType' object has no attribute 'boot_diagnostics'
```
It already runs for over 10 minutes and nothing else seems to happen. I am not sure if the execution is running in the background or if it stopped. Any idea how I can find that out?

**To Reproduce**

`scout azure --cli --subscription xxx --debug --skip securitycenter`

**Additional context**

```
$ python --version
Python 3.8.10
$ scout --version
Scout Suite 5.11.0
```
When I add `virtualmachines` to the `--skip` option, the exception does not happen: 
```
$ scout azure --cli --subscription xxx --skip securitycenter virtualmachines --debug
2022-04-21 11:40:59 FE-C-006X8 scout[869] INFO Launching Scout
2022-04-21 11:40:59 FE-C-006X8 scout[869] INFO Authenticating to cloud provider
2022-04-21 11:41:02 FE-C-006X8 scout[869] INFO Running against subscription xxx
2022-04-21 11:41:02 FE-C-006X8 scout[869] INFO Gathering data from APIs
2022-04-21 11:41:02 FE-C-006X8 scout[869] DEBUG Skipping the Security Center service
2022-04-21 11:41:02 FE-C-006X8 scout[869] DEBUG Skipping the Virtual Machines service
2022-04-21 11:41:02 FE-C-006X8 scout[869] INFO Fetching resources for the Azure Active Directory service
2022-04-21 11:41:02 FE-C-006X8 scout[869] INFO Fetching resources for the Azure RBAC service
2022-04-21 11:41:02 FE-C-006X8 scout[869] INFO Fetching resources for the SQL Database service
2022-04-21 11:41:02 FE-C-006X8 scout[869] INFO Fetching resources for the Storage Accounts service
2022-04-21 11:41:02 FE-C-006X8 scout[869] INFO Fetching resources for the Key Vault service
2022-04-21 11:41:02 FE-C-006X8 scout[869] INFO Fetching resources for the Network service
2022-04-21 11:41:02 FE-C-006X8 scout[869] INFO Fetching resources for the App Services service
```
Nothing happens afterwards. I don't know if it is normal that there is no progress shown or how long a scan usually takes.

**Comment by fernando-gallego** [comment]
Hi,

This has been fixed on the develop branch by handling data processing for VMs which do not have a diagnostics profile configured.

Changes have not yet made it to master; please give it a try with the develop branch to see if the error persists. Also check the new **requirements.txt** file which contains updated versions for multiple packages. These will be needed for the upgraded features to work as expected.

**Comment by timothyleung1** [comment]
having the same problem. Should the tool keep going instead of hanging?

**Comment by fernando-gallego** [comment]
Hi @timothyleung1 , does your issue still occur after following advice on my previous comment?
