### ISSUE TITLE
AWS CloudTrail collection aborts on trails with no EventSelectors

### ISSUE THREAD

**Issue by rbailey-godaddy** [nccgroup/ScoutSuite#1424]
**Describe the bug**

Existing logic assumes `EventSelectors` key always is present in `boto3.get_event_selectors()` response -- but it isn't. Consider:

```sh
$ aws cloudtrail get-event-selectors --trail-name ObfuscatedTrailName
{
    "TrailARN": "arn:aws:cloudtrail:us-west-2:111222333444:trail/ObfuscatedTrailName",
    "AdvancedEventSelectors": [
        {
            "Name": "Management events selector",
            "FieldSelectors": [
                {
                    "Field": "eventCategory",
                    "Equals": [
                        "Management"
                    ]
                }
            ]
        }
    ]
}
```
This is actual output (I have obfuscated the account id and actual trail name). BTW, I have no idea how this trail was actually created.

This results in the following failure:
```
2022-06-01 20:03:56 ip-10-115-185-40.us-west-2.compute.internal scout[22] INFO Launching Scout
2022-06-01 20:03:56 ip-10-115-185-40.us-west-2.compute.internal scout[22] INFO Authenticating to cloud provider
2022-06-01 20:03:58 ip-10-115-185-40.us-west-2.compute.internal scout[22] INFO Gathering data from APIs
2022-06-01 20:03:58 ip-10-115-185-40.us-west-2.compute.internal scout[22] INFO Fetching resources for the CloudFormation service
2022-06-01 20:03:58 ip-10-115-185-40.us-west-2.compute.internal scout[22] INFO Fetching resources for the CloudTrail service
2022-06-01 20:03:58 ip-10-115-185-40.us-west-2.compute.internal scout[22] INFO Fetching resources for the Config service
2022-06-01 20:03:59 ip-10-115-185-40.us-west-2.compute.internal scout[22] INFO Fetching resources for the EC2 service
2022-06-01 20:03:59 ip-10-115-185-40.us-west-2.compute.internal scout[22] INFO Fetching resources for the ELB service
2022-06-01 20:03:59 ip-10-115-185-40.us-west-2.compute.internal scout[22] INFO Fetching resources for the ELBv2 service
2022-06-01 20:04:00 ip-10-115-185-40.us-west-2.compute.internal scout[22] INFO Fetching resources for the IAM service
2022-06-01 20:04:00 ip-10-115-185-40.us-west-2.compute.internal scout[22] INFO Fetching resources for the RDS service
2022-06-01 20:04:00 ip-10-115-185-40.us-west-2.compute.internal scout[22] INFO Fetching resources for the RedShift service
2022-06-01 20:04:00 ip-10-115-185-40.us-west-2.compute.internal scout[22] INFO Fetching resources for the S3 service
2022-06-01 20:04:01 ip-10-115-185-40.us-west-2.compute.internal scout[22] INFO Fetching resources for the VPC service
2022-06-01 20:04:01 ip-10-115-185-40.us-west-2.compute.internal scout[22] INFO Fetching resources for the Secrets Manager service
2022-06-01 20:04:34 ip-10-115-185-40.us-west-2.compute.internal scout[22] ERROR cloudtrail.py L35: Failed to get CloudTrail event selectors: 'EventSelectors'
2022-06-01 20:04:34 ip-10-115-185-40.us-west-2.compute.internal scout[22] ERROR cloudtrail.py L35: Failed to get CloudTrail event selectors: 'EventSelectors'
2022-06-01 20:04:34 ip-10-115-185-40.us-west-2.compute.internal scout[22] ERROR cloudtrail.py L35: Failed to get CloudTrail event selectors: 'EventSelectors'
2022-06-01 20:04:34 ip-10-115-185-40.us-west-2.compute.internal scout[22] ERROR cloudtrail.py L35: Failed to get CloudTrail event selectors: 'EventSelectors'
2022-06-01 20:04:34 ip-10-115-185-40.us-west-2.compute.internal scout[22] ERROR cloudtrail.py L35: Failed to get CloudTrail event selectors: 'EventSelectors'
2022-06-01 20:05:05 ip-10-115-185-40.us-west-2.compute.internal scout[22] ERROR cloudtrail.py L35: Failed to get CloudTrail event selectors: 'EventSelectors'
2022-06-01 20:05:05 ip-10-115-185-40.us-west-2.compute.internal scout[22] ERROR cloudtrail.py L35: Failed to get CloudTrail event selectors: 'EventSelectors'
2022-06-01 20:05:05 ip-10-115-185-40.us-west-2.compute.internal scout[22] ERROR cloudtrail.py L35: Failed to get CloudTrail event selectors: 'EventSelectors'
2022-06-01 20:05:05 ip-10-115-185-40.us-west-2.compute.internal scout[22] ERROR cloudtrail.py L35: Failed to get CloudTrail event selectors: 'EventSelectors'
2022-06-01 20:05:05 ip-10-115-185-40.us-west-2.compute.internal scout[22] ERROR cloudtrail.py L35: Failed to get CloudTrail event selectors: 'EventSelectors'
2022-06-01 20:05:05 ip-10-115-185-40.us-west-2.compute.internal scout[22] ERROR cloudtrail.py L35: Failed to get CloudTrail event selectors: 'EventSelectors'
2022-06-01 20:05:05 ip-10-115-185-40.us-west-2.compute.internal scout[22] ERROR cloudtrail.py L35: Failed to get CloudTrail event selectors: 'EventSelectors'
2022-06-01 20:05:05 ip-10-115-185-40.us-west-2.compute.internal scout[22] ERROR cloudtrail.py L35: Failed to get CloudTrail event selectors: 'EventSelectors'
2022-06-01 20:05:05 ip-10-115-185-40.us-west-2.compute.internal scout[22] ERROR cloudtrail.py L35: Failed to get CloudTrail event selectors: 'EventSelectors'
2022-06-01 20:05:05 ip-10-115-185-40.us-west-2.compute.internal scout[22] ERROR cloudtrail.py L35: Failed to get CloudTrail event selectors: 'EventSelectors'
2022-06-01 20:05:05 ip-10-115-185-40.us-west-2.compute.internal scout[22] ERROR cloudtrail.py L35: Failed to get CloudTrail event selectors: 'EventSelectors'
2022-06-01 20:05:05 ip-10-115-185-40.us-west-2.compute.internal scout[22] ERROR cloudtrail.py L35: Failed to get CloudTrail event selectors: 'EventSelectors'
Task exception was never retrieved
future: <Task finished name='Task-54' coro=<Trails.fetch_all() done, defined at /app/.venv/lib/python3.8/site-packages/ScoutSuite/providers/aws/resources/cloudtrail/trails.py:13> exception=KeyError('EventSelectors')>
Traceback (most recent call last):
  File "/app/.venv/lib/python3.8/site-packages/ScoutSuite/providers/aws/resources/cloudtrail/trails.py", line 16, in fetch_all
    name, resource = self._parse_trail(raw_trail)
  File "/app/.venv/lib/python3.8/site-packages/ScoutSuite/providers/aws/resources/cloudtrail/trails.py", line 46, in _parse_trail
    trail['wildcard_data_logging'] = self.data_logging_status(trail)
  File "/app/.venv/lib/python3.8/site-packages/ScoutSuite/providers/aws/resources/cloudtrail/trails.py", line 55, in data_logging_status
    for event_selector in trail['EventSelectors']:
KeyError: 'EventSelectors'
```
This failure then proceeds to cause false `cloudtrail-not-configured` alerts.

The `scoutsuite_errors_aws-xxxx.json` file contains a bunch of entries like this:

```json
    {
        "additional_details": null,
        "exception": "Failed to get CloudTrail event selectors: 'EventSelectors'",
        "file": "cloudtrail.py",
        "line": 35,
        "traceback": "Traceback (most recent call last):\n  File \"/app/.venv/lib/python3.8/site-packages/ScoutSuite/providers/aws/facade/cloudtrail.py\", line 35, in _get_and_set_selectors\n    trail['EventSelectors'] = await run_concur
rently(\n  File \"/app/.venv/lib/python3.8/site-packages/ScoutSuite/providers/utils.py\", line 25, in run_concurrently\n    return await run_function_concurrently(function)\n  File \"/usr/local/lib/python3.8/concurrent/futures/thread.py\
", line 57, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/app/.venv/lib/python3.8/site-packages/ScoutSuite/providers/aws/facade/cloudtrail.py\", line 36, in <lambda>\n    lambda: client.get_event_selectors(TrailName=
trail['TrailARN'])['EventSelectors'])\nKeyError: 'EventSelectors'\n"
    },
```

**To Reproduce**

FWIW, the command we use is:

```sh
/app/.venv/bin/scout aws --services cloudformation cloudtrail config ec2 elb elbv2 iam rds redshift s3 secretsmanager vpc \
    --max-workers 10 \
    --access-keys \
    --access-key-id OBFUSCATED \
    --secret-access-key OBFUSCATED \
    --session-token OBFUSCATED \
    --no-browser --ruleset godaddy.json
```
As noted above, I have no idea exactly how the offending trail was created, but the relevant API response is provided above.

**Comment by rbailey-godaddy** [comment]
If you are wondering, `godaddy.json` is basically `defaults.json` edited to turn on a few rules that are off by default, and to adjust the arguments of a few others. None of these changes are relevant to CloudTrail probes.

**Comment by bmurphey** [comment]
This bug is causing Scout reports to be inaccurate and say that CloudTrail is not enabled.  Can we get this fix merged in?  I can't use this tool if something as foundational as CloudTrail is that incorrect, and the fix is already there.

**Comment by x4v13r64** [comment]
This is fixed in `develop`, not sure what the timeline was wrt 5.11.
