### ISSUE TITLE
ec2.py Error

### ISSUE THREAD

**Issue by Mani-Selvaraj** [nccgroup/ScoutSuite#1433]
ec2.py L152: Failed to describe EC2 snapshot attributes: An error occurred (InvalidSnapshot.NotFound) when calling the DescribeSnapshotAttribute operation: The snapshot 'snap-02dd0afe6d5a96ec0' does not exist

Can anyone help me with this?

**Comment by fernando-gallego** [comment]
Hi, would you be able to provide:

**Describe the bug**

Please provide:

- A clear and concise description of what the bug is.
- Console output using the `--debug` argument.
- If possible, the errors JSON file generated at the end of execution (the CLI output will provide the path to this file). The file can be sent to <scoutsuite@nccgroup.com> to avoid including sensitive content in the GitHub issue.

**To Reproduce**

Please provide:

- The **exact** CLI parameters used to run Scout Suite.
- Any specific configuration within the cloud account which might have lead to the issue.

**Comment by rbailey-godaddy** [comment]
We see this:
```
Task exception was never retrieved
future: <Task finished name='Task-13629' coro=<EC2Facade._get_and_set_snapshot_attributes() done, defined at /app/.venv/lib/python3.11/site-packages/ScoutSuite/providers/aws/facade/ec2.py:152> exception=TypeError("argument of type 'ClientError' is not iterable")>
Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/ScoutSuite/providers/aws/facade/ec2.py", line 155, in _get_and_set_snapshot_attributes
    snapshot['CreateVolumePermissions'] = await run_concurrently(lambda: ec2_client.describe_snapshot_attribute(
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/ScoutSuite/providers/utils.py", line 27, in run_concurrently
    return await run_function_concurrently(function)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/ScoutSuite/providers/aws/facade/ec2.py", line 155, in <lambda>
    snapshot['CreateVolumePermissions'] = await run_concurrently(lambda: ec2_client.describe_snapshot_attribute(
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/botocore/client.py", line 1017, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSnapshot.NotFound) when calling the DescribeSnapshotAttribute operation: The snapshot 'snap-094715079b66310d5' does not exist.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/ScoutSuite/providers/aws/facade/ec2.py", line 159, in _get_and_set_snapshot_attributes
    if 'NotFound' in e:
       ^^^^^^^^^^^^^^^
TypeError: argument of type 'ClientError' is not iterable
```
