### ISSUE TITLE
GCP - Error 404 Failed to retrieve IAM role definition

### ISSUE THREAD

**Issue by michelaporte** [nccgroup/ScoutSuite#1454]
Hi There,
We are running ScoutSuite on GCP, and we are faced with an issue on one of our projects. Im unsure if this is Google returning a weird error code, however, it fails with the following error

`2022-09-06 15:18:32 runner-afkxgp-4-project-39123159-concurrent-0t5vb7 scout[12] ERROR iam.py L66: Failed to retrieve IAM role definition: <HttpError 404 when requesting https://iam.googleapis.com/v1/roles/storage.objectAdmin_withcond_567e84a61c09552574ae?alt=json returned "The role named roles/storage.objectAdmin_withcond_567e84a61c09552574ae was not found.". Details: "The role named roles/storage.objectAdmin_withcond_567e84a61c09552574ae was not found.">
Traceback (most recent call last):
  File "/root/scoutsuite/lib/python3.9/site-packages/ScoutSuite/providers/gcp/facade/iam.py", line 66, in get_role_definition
    response = await run_concurrently(
  File "/root/scoutsuite/lib/python3.9/site-packages/ScoutSuite/providers/utils.py", line 26, in run_concurrently
    return await run_function_concurrently(function)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/scoutsuite/lib/python3.9/site-packages/ScoutSuite/providers/gcp/facade/iam.py", line 67, in <lambda>
    lambda: iam_client.roles().get(name=role).execute()
  File "/root/scoutsuite/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/root/scoutsuite/lib/python3.9/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)`

This error shows on screen 4-5 times. 

We are using it in a Gitlab Runner.
We are scanning other projects with no errors, just this one, It seems its looking for a IAM which i cannot find or doesn't exist anymore.

**Command run**

`scout gcp --service-account {} --report-dir report-${GCP_PROJECT_VAR} --project-id ${GCP_PROJECT_VAR} --no-browser --services kubernetesengine cloudstorage computeengine iam kms cloudsql --max-workers 1 --max-rate 1 --debug`

ScoutSuite Version: `5.12.0`
Docker Release

Thank you

**Comment by fernando-gallego** [comment]
Hi @michelaporte , which Python version are you running? Could you try with 3.8, in case you are running a different one?

**Comment by michelaporte** [comment]
Hi
We are running the Official docker image from https://github.com/nccgroup/ScoutSuite/blob/master/docker/Dockerfile
But for some reason its running with python3.9
Let me force it to run with 3.8 and get back to you :)
Thanks

**Comment by michelaporte** [comment]
Okay ive just seen something, in this [script](https://github.com/nccgroup/ScoutSuite/blob/master/docker/bin/container-install-prereqs.sh#L32)
You install Python3 which in apt-cache shows its version 3.9 

`(scoutsuite) root@f34b0ff35dd2:~# apt-cache policy python3
python3:
  Installed: 3.9.2-3
  Candidate: 3.9.2-3
  Version table:
 *** 3.9.2-3 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status`

As we're using python3.8 image, ill remove that and try it with Python 3.8

**Comment by michelaporte** [comment]
Update:
Okay this didn't work i still got the same result
So i went to GOOGLE, and they said there are issues with ScoutSuite. Please see their reply

```
We received an update from our Engineering team in regards to your concern, as they mentioned please file a bug with the ScoutSuite team, your software is incorrectly configured. It is not listing the set of enabled APIs.

This can be observed by inspecting the metric which is exceeded, which is ListAvailableRequestsPerMinutePerProject. If the software were configured correctly, it would draw quota from the ListEnabledRequestsPerMinutePerProject. You can refer the ScoutSuite team to the documentation [1], which shows how API calls must be configured to list only the enabled services, namely the filter parameter must be present with state:ENABLED as the argument.

For both the customer and ScoutSuite, the preferred integration for listing the set of enabled services across many projects is with Cloud Asset Inventory. Cloud Asset Inventory allows exporting the state of all projects under the control of an organization in a single RPC call as well as monitoring projects for state changes.

To export all enabled services for a particular project, follow the CAI docs for Listing Assets [2].

The command for enabled APIs would be:
gcloud asset list --project=consumer-project_ID --billing-project=BILLING_consumer-project_ID --asset-types='[serviceusage.googleapis.com/Service](http://serviceusage.googleapis.com/Service)' --snapshot-time=$NOW --content-type='resource' Substituting --project=consumer-project_ID for --organization=ORGANIZATION_ID will dump the same list for an entire org. This can be done through the API as well, and the linked documentation shows how to do that.

[1] https://cloud.google.com/service-usage/docs/list-services#curl_1
[2] https://cloud.google.com/asset-inventory/docs/listing-assets
```
Thanks
