### ISSUE TITLE
Scout Scan unsuccessful

### ISSUE THREAD

**Issue by piyush-sharma140390** [nccgroup/ScoutSuite#1455]
I am trying to execute scout scan for GCP with a simple command 

scout gcp --user-account 

I am using Python3.8 and pip3-8 to install the dependencies.

Scan runs for a while then gets stuck with below error

Task exception was never retrieved
future: <Task finished name='Task-76' coro=<FunctionsV1.fetch_all() done, defined at /home/perf_test_dxpf/venv/lib/python3.8/site-packages/ScoutSuite/providers/gcp/resources/functions/functions_v1.py:12> exception=KeyError('maxInstances')>
Traceback (most recent call last):
  File "/home/perf_test_dxpf/venv/lib/python3.8/site-packages/ScoutSuite/providers/gcp/resources/functions/functions_v1.py", line 15, in fetch_all
    function_id, function = self._parse_function(raw_function)
  File "/home/perf_test_dxpf/venv/lib/python3.8/site-packages/ScoutSuite/providers/gcp/resources/functions/functions_v1.py", line 30, in _parse_function
    function_dict['max_instances'] = raw_function['maxInstances']
KeyError: 'maxInstances'

**Comment by fernando-gallego** [comment]
Hi @piyush-sharma140390 , are you experiencing this issue on version 5.12.0?

**Comment by piyush-sharma140390** [comment]
@fernando-gallego Yes correct , there seems to be some issue in provider.py in the function dealing with cloud function v1

**Comment by fernando-gallego** [comment]
Hi @piyush-sharma140390 , I have updated the functions.py code to handle instances in which a function has no maxItems defined. Could you please try using the "develop" branch and let me know if the error persists?

**Comment by piyush-sharma140390** [comment]
Hello @fernando-gallego : Thanks for your kind response :)
I used python 3.8 and develop branch 
Unfortunately error still persists.

2022-09-15 15:49:16 cs-669757724344-default scout[13533] INFO Launching Scout
2022-09-15 15:49:16 cs-669757724344-default scout[13533] INFO Authenticating to cloud provider
2022-09-15 15:49:17 cs-669757724344-default scout[13533] INFO Gathering data from APIs
2022-09-15 15:49:17 cs-669757724344-default scout[13533] INFO Fetching resources for the Cloud SQL service
2022-09-15 15:49:17 cs-669757724344-default scout[13533] INFO Fetching resources for the Cloud Memorystore service
2022-09-15 15:49:18 cs-669757724344-default scout[13533] INFO Fetching resources for the Cloud Storage service
2022-09-15 15:49:19 cs-669757724344-default scout[13533] INFO Fetching resources for the Compute Engine service
2022-09-15 15:49:19 cs-669757724344-default scout[13533] INFO Fetching resources for the Cloud Functions service
2022-09-15 15:49:20 cs-669757724344-default scout[13533] INFO Fetching resources for the BigQuery service
2022-09-15 15:49:21 cs-669757724344-default scout[13533] INFO Fetching resources for the IAM service
2022-09-15 15:49:21 cs-669757724344-default scout[13533] INFO Fetching resources for the KMS service
2022-09-15 15:49:22 cs-669757724344-default scout[13533] INFO Fetching resources for the Stackdriver Logging service
2022-09-15 15:49:22 cs-669757724344-default scout[13533] INFO Fetching resources for the Stackdriver Monitoring service
2022-09-15 15:49:23 cs-669757724344-default scout[13533] INFO Fetching resources for the Kubernetes Engine service
2022-09-15 15:49:23 cs-669757724344-default scout[13533] INFO Fetching resources for the DNS service
2022-09-15 15:54:03 cs-669757724344-default scout[13533] ERROR buckets.py L44: Failed to retrieve storage bucket ACLs: 403 GET https://storage.googleapis.com/storage/v1/b/vm-config.ace-ripsaw-671.appspot.com/acl?prettyPrint=false: perf.test.dxpf@gmail.com does not have storage.buckets.get access to the Google Cloud Storage bucket.
2022-09-15 15:54:03 cs-669757724344-default scout[13533] ERROR buckets.py L49: Failed to retrieve storage bucket object ACLs: 403 GET https://storage.googleapis.com/storage/v1/b/vm-config.ace-ripsaw-671.appspot.com/defaultObjectAcl?prettyPrint=false: perf.test.dxpf@gmail.com does not have storage.buckets.get access to the Google Cloud Storage bucket.
Task exception was never retrieved
future: <Task finished name='Task-79' coro=<FunctionsV1.fetch_all() done, defined at /home/perf_test_dxpf/ScoutSuite/ScoutSuite/providers/gcp/resources/functions/functions_v1.py:12> exception=KeyError('maxInstances')>
Traceback (most recent call last):
  File "/home/perf_test_dxpf/ScoutSuite/ScoutSuite/providers/gcp/resources/functions/functions_v1.py", line 15, in fetch_all
    function_id, function = self._parse_function(raw_function)
  File "/home/perf_test_dxpf/ScoutSuite/ScoutSuite/providers/gcp/resources/functions/functions_v1.py", line 30, in _parse_function
    **if raw_function['maxInstances']:
KeyError: 'maxInstances'**
















2022-09-15 15:56:07 cs-669757724344-default scout[13533] INFO Running pre-processing engine
2022-09-15 15:56:07 cs-669757724344-default scout[13533] ERROR provider.py L182: Unable to match instances and subnetworks: 'subnetwork'
2022-09-15 15:56:07 cs-669757724344-default scout[13533] INFO Running rule engine
2022-09-15 15:56:07 cs-669757724344-default scout[13533] INFO Applying display filters
2022-09-15 15:56:07 cs-669757724344-default scout[13533] INFO Running post-processing engine
2022-09-15 15:56:08 cs-669757724344-default scout[13533] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_results_gcp-ace-ripsaw-671.js
2022-09-15 15:56:08 cs-669757724344-default scout[13533] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_exceptions_gcp-ace-ripsaw-671.js
2022-09-15 15:56:08 cs-669757724344-default scout[13533] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_errors_gcp-ace-ripsaw-671.json
2022-09-15 15:56:08 cs-669757724344-default scout[13533] INFO Creating scoutsuite-report/gcp-ace-ripsaw-671.html
2022-09-15 15:56:08 cs-669757724344-default scout[13533] INFO Opening the HTML report
file:///home/perf_test_dxpf/ScoutSuite/scoutsuite-report/gcp-ace-ripsaw-671.html
(
**(venv) perf_test_dxpf@cloudshell:~/ScoutSuite (ace-ripsaw-671)$ git status
On branch develop
Your branch is up to date with 'origin/develop'.**

nothing to commit, working tree clean
(venv) perf_test_dxpf@cloudshell:~/ScoutSuite (ace-ripsaw-671)$

**Comment by icraytho** [comment]
This still seems to be an issue. I encountered the same today.

**Comment by fernando-gallego** [comment]
Hi, I have updated the develop branch. Could you try to reproduce the issue?
