### ISSUE TITLE
Instances missing in the results (Azure cli)

### ISSUE THREAD

**Issue by githubnoud** [nccgroup/ScoutSuite#1457]
**Version:**
Windows 10 version 21H2
Python 3.10.4
Azure CLI 2.40.0 (but also tried 2.39, 2.37 and 2.20)
ScoutSuite 5.12 (but also tried 5.11)
Role: reading

**Command:**
python scout.py azure  --subscriptions %%a  --report-name %%a  -f --cli --skip aad rbac securitycenter --no-browser

I'm running ScoutSuite on a subscription with 40 virtual machines, but the result shows none of them in the json under instances_count: 
![image](https://user-images.githubusercontent.com/62704944/189905862-6b7895d8-8d0c-455e-8fa8-898860dd2907.png)
However, the disks (129) are accurately presented in the json. 

Also, when I run ScoutSuite on another subscription, the number of virtual machines (instances_count) and disks are included in the scan:
![image](https://user-images.githubusercontent.com/62704944/189909598-98729002-874a-4592-b42a-19cc0a28b5aa.png)
  
I have been testing this since June with various versions and at different timeslots of the day. No exceptions or errors applicable. 

Any help would be greatly appreciated.

**Comment by fernando-gallego** [comment]
Hi @githubnoud , could you try with [Python 3.8](https://github.com/nccgroup/ScoutSuite/wiki/Setup)?

**Comment by githubnoud** [comment]
> Hi @githubnoud , could you try with [Python 3.8](https://github.com/nccgroup/ScoutSuite/wiki/Setup)?

Thanks for noticing. I deleted 3.10.4 and setup a new Python installation 3.8.0. The result is the same unfortunately. The VMs are still missing

**Comment by githubnoud** [comment]
I ran the --debug option and got the following error:

future: <Task finished name='Task-28' coro=<Instances.fetch_all() done, defined at **C:\Apps\scout12\ScoutSuite\providers\azure\resources\virtualmachines\instances.py:14> exception=AttributeError("'NoneType' object has no attribute 'publisher'")>**
Traceback (most recent call last):
  File "C:\Apps\scout12\ScoutSuite\providers\azure\resources\virtualmachines\instances.py", line 16, in fetch_all
    id, instance = await self._parse_instance(raw_instance)
  File "C:\Apps\scout12\ScoutSuite\providers\azure\resources\virtualmachines\instances.py", line 90, in _parse_instance
    instance_dict['storage_profile']['Publisher'] = raw_instance.storage_profile.image_reference.publisher

**Comment by NikhilKeshwala** [comment]
I'm getting the same error, was this resolved @githubnoud?

**Comment by fernando-gallego** [comment]
Hi @githubnoud , I have just commited a change to the develop branch which should handle this error condition. Could you try to reproduce the issue with the develop branch?
