### ISSUE TITLE
[kubernetes] ERROR __main__.py L237: Initialization failure: 'data'

### ISSUE THREAD

**Issue by bprsyn** [nccgroup/ScoutSuite#1465]
**Describe the bug**

I run this command on AWS EKS:
```
➜  ScoutSuite git:(develop) scout kubernetes --debug
2022-10-05 14:23:40 bprevost-XPS-13-9300 scout[167757] INFO Launching Scout
2022-10-05 14:23:40 bprevost-XPS-13-9300 scout[167757] INFO Authenticating to cloud provider
2022-10-05 14:23:41 bprevost-XPS-13-9300 scout[167757] INFO GET /version
2022-10-05 14:23:42 bprevost-XPS-13-9300 scout[167757] INFO GET /api
2022-10-05 14:23:42 bprevost-XPS-13-9300 scout[167757] INFO GET /api/v1
2022-10-05 14:23:42 bprevost-XPS-13-9300 scout[167757] INFO GET /api/v1/componentstatuses
2022-10-05 14:23:42 bprevost-XPS-13-9300 scout[167757] INFO GET /api/v1/configmaps
2022-10-05 14:23:42 bprevost-XPS-13-9300 scout[167757] INFO GET /api/v1/endpoints
2022-10-05 14:23:42 bprevost-XPS-13-9300 scout[167757] INFO GET /api/v1/events
2022-10-05 14:23:42 bprevost-XPS-13-9300 scout[167757] INFO GET /api/v1/limitranges
2022-10-05 14:23:42 bprevost-XPS-13-9300 scout[167757] INFO GET /api/v1/namespaces
2022-10-05 14:23:42 bprevost-XPS-13-9300 scout[167757] INFO GET /api/v1/nodes
2022-10-05 14:23:42 bprevost-XPS-13-9300 scout[167757] INFO GET /api/v1/persistentvolumeclaims
2022-10-05 14:23:42 bprevost-XPS-13-9300 scout[167757] INFO GET /api/v1/persistentvolumes
2022-10-05 14:23:42 bprevost-XPS-13-9300 scout[167757] INFO GET /api/v1/pods
2022-10-05 14:23:42 bprevost-XPS-13-9300 scout[167757] INFO GET /api/v1/podtemplates
2022-10-05 14:23:42 bprevost-XPS-13-9300 scout[167757] INFO GET /api/v1/replicationcontrollers
2022-10-05 14:23:42 bprevost-XPS-13-9300 scout[167757] INFO GET /api/v1/resourcequotas
2022-10-05 14:23:42 bprevost-XPS-13-9300 scout[167757] INFO GET /api/v1/secrets
2022-10-05 14:23:42 bprevost-XPS-13-9300 scout[167757] ERROR __main__.py L237: Initialization failure: 'data'
Traceback (most recent call last):
  File "/home/bprevost/Projets/synalabs/ScoutSuite/venv/lib/python3.10/site-packages/ScoutSuite-5.12.0-py3.10.egg/ScoutSuite/__main__.py", line 237, in _run
    cloud_provider = get_provider(provider=provider,
  File "/home/bprevost/Projets/synalabs/ScoutSuite/venv/lib/python3.10/site-packages/ScoutSuite-5.12.0-py3.10.egg/ScoutSuite/providers/__init__.py", line 38, in get_provider
    provider_instance = provider_object(profile=profile,
  File "/home/bprevost/Projets/synalabs/ScoutSuite/venv/lib/python3.10/site-packages/ScoutSuite-5.12.0-py3.10.egg/ScoutSuite/providers/kubernetes/provider.py", line 59, in __init__
    super().__init__(report_dir, timestamp, resources, skipped_resources, result_format)
  File "/home/bprevost/Projets/synalabs/ScoutSuite/venv/lib/python3.10/site-packages/ScoutSuite-5.12.0-py3.10.egg/ScoutSuite/providers/base/provider.py", line 41, in __init__
    self.services = self.services_config(self.credentials)
  File "/home/bprevost/Projets/synalabs/ScoutSuite/venv/lib/python3.10/site-packages/ScoutSuite-5.12.0-py3.10.egg/ScoutSuite/providers/kubernetes/services.py", line 29, in __init__
    core_resources = facade.core.get_resources()
  File "/home/bprevost/Projets/synalabs/ScoutSuite/venv/lib/python3.10/site-packages/ScoutSuite-5.12.0-py3.10.egg/ScoutSuite/providers/kubernetes/facade/core.py", line 36, in get_resources
    for key in resources[i]['data']:
KeyError: 'data'
```

I found one secret without data key, created by ArgoCD (installed with Helm chart):
```
apiVersion: v1
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: argo
    meta.helm.sh/release-namespace: argo
  creationTimestamp: "2022-09-13T13:21:58Z"
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/instance: argo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-4.9.4
  name: argocd-notifications-controller-secret
  namespace: argo
  resourceVersion: "257581"
  uid: c064745a-9008-4782-bfc7-2ecccfbcac4d
type: Opaque
```

**Comment by liyun-li** [comment]
Interesting! I will work on a pull request :)

**Comment by liyun-li** [comment]
@bprsyn: Did the PR fix your bug? If so please close it.

**Comment by liyun-li** [comment]
I think it's resolved
