### ISSUE TITLE
Unguarded references to optional CloudFormation stack attributes

### ISSUE THREAD

**Issue by rbailey-godaddy** [nccgroup/ScoutSuite#1478]
**Describe the bug**

AWS CloudFormation stack enumeration assumes attributes `EnableTerminationProtection` and `NotificationARNs` exist for every stack, when they do not. The result is something like this:

```
Task exception was never retrieved
future: <Task finished name='Task-1100' coro=<Stacks.fetch_all() done, defined at /app/.venv/lib/python3.10/site-packages/ScoutSuite/providers/aws/resources/cloudformation/stacks.py:13> exception=KeyError('EnableTerminationProtection')>
Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/ScoutSuite/providers/aws/resources/cloudformation/stacks.py", line 16, in fetch_all
    name, stack = self._parse_stack(raw_stack)
  File "/app/.venv/lib/python3.10/site-packages/ScoutSuite/providers/aws/resources/cloudformation/stacks.py", line 24, in _parse_stack
    raw_stack['termination_protection'] = raw_stack['EnableTerminationProtection']
KeyError: 'EnableTerminationProtection'
```
The result is that information about all stacks not processed before the error is encountered is lost. In my test environment, information on ~40 stacks was returned prior to this fix, and ~225 stacks after applying this PR.

I noticed this problem when integrating 5.12.0, but it looks like it has existed for some time.

**To Reproduce**

I don't guarantee this will work, but I suspect any CloudFormation stack which does not enable Termination Protection and/or which does not have any notifications configured will likely trigger the problem.

**Comment by fernando-gallego** [comment]
PR merged into develop.
