### ISSUE TITLE
Why are python versions later than 3.8 not supported?

### ISSUE THREAD

**Issue by rbailey-godaddy** [nccgroup/ScoutSuite#1480]
**Is your feature request related to a problem? Please describe.**

https://pypi.org/project/ScoutSuite/ says that python versions 3.6, 3.7, and 3.8 are supported. Is the ommission of later, faster versions an oversight, or is there a fundamental problem I've missed?

**Describe the solution you'd like**

Please add at least python 3.10 (and 3.11?) to the support list. I have run ScoutSuite 5.12.0 against AWS using python 3.10.8 and it seems to work fine.

**Describe alternatives you've considered**

* Run against python 3.10 even though it is not officially supported
* Run against python 3.8 until **** freezes over

**Comment by x64-latacora** [comment]
> oversight

Yes, they just need to be added to https://github.com/nccgroup/ScoutSuite/blob/master/setup.py#L58-L61 for pip to mention more recent versions.

**Comment by Vovcharaa** [comment]
Python 3.11 not supported with error: 
``` 
scout[97539] ERROR __main__.py L211: Initialization failure: global flags not at the start of the expression at position 6
Traceback (most recent call last):
  File "/Users/vovchara/Desktop/audit/venv/lib/python3.11/site-packages/ScoutSuite/__main__.py", line 211, in _run
    cloud_provider = get_provider(provider=provider,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vovchara/Desktop/audit/venv/lib/python3.11/site-packages/ScoutSuite/providers/__init__.py", line 36, in get_provider
    provider_object = get_provider_object(provider)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vovchara/Desktop/audit/venv/lib/python3.11/site-packages/ScoutSuite/providers/__init__.py", line 10, in get_provider_object
    provider_module = __import__(f'ScoutSuite.providers.{provider}.provider', fromlist=[provider_class])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vovchara/Desktop/audit/venv/lib/python3.11/site-packages/ScoutSuite/providers/aws/provider.py", line 5, in <module>
    from ScoutSuite.providers.aws.services import AWSServicesConfig
  File "/Users/vovchara/Desktop/audit/venv/lib/python3.11/site-packages/ScoutSuite/providers/aws/services.py", line 1, in <module>
    from ScoutSuite.providers.aws.facade.base import AWSFacade
  File "/Users/vovchara/Desktop/audit/venv/lib/python3.11/site-packages/ScoutSuite/providers/aws/facade/base.py", line 3, in <module>
    from ScoutSuite.providers.aws.facade.acm import AcmFacade
  File "/Users/vovchara/Desktop/audit/venv/lib/python3.11/site-packages/ScoutSuite/providers/aws/facade/acm.py", line 3, in <module>
    from ScoutSuite.providers.aws.facade.utils import AWSFacadeUtils
  File "/Users/vovchara/Desktop/audit/venv/lib/python3.11/site-packages/ScoutSuite/providers/aws/facade/utils.py", line 5, in <module>
    from ScoutSuite.providers.utils import run_concurrently
  File "/Users/vovchara/Desktop/audit/venv/lib/python3.11/site-packages/ScoutSuite/providers/utils.py", line 139, in <module>
    re.compile("(p8e-)(?i)[a-z0-9]{32}"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 6
```

**Comment by fernando-gallego** [comment]
This one has been addressed and should no longer trigger any errors for Python 3.11, changes have been merged into the develop branch and will be shipped to master in the next release.
