### ISSUE TITLE
Error when installing ScoutSuite from Wiki instructions macos

### ISSUE THREAD

**Issue by hybrezz54** [nccgroup/ScoutSuite#1494]
Hi, I get the following issue when trying to install ScoutSuite on macOS version 12.6.2 running Python 3.9.6 and PIP 21.2.4. I've tried running this several times and in a virtual environment and still get the same error. Is there a known workaround to this?

```      
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/Users/hamzahc/guardian/include -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers -c /var/folders/w2/1ctlcj0x56l7t3zxwf1b8c040000gs/T/tmpq9d2_j4r/a.c -o None/var/folders/w2/1ctlcj0x56l7t3zxwf1b8c040000gs/T/tmpq9d2_j4r/a.o
      /var/folders/w2/1ctlcj0x56l7t3zxwf1b8c040000gs/T/tmpq9d2_j4r/a.c:2:10: fatal error: 'Python.h' file not found
      #include <Python.h>
               ^~~~~~~~~~
      1 error generated.
      
      Could not find <Python.h>. This could mean the following:
        * You're on Ubuntu and haven't run `apt-get install python3-dev`.
        * You're on RHEL/Fedora and haven't run `yum install python3-devel` or
          `dnf install python3-devel` (make sure you also have redhat-rpm-config
          installed)
        * You're on Mac OS X and the usual Python framework was somehow corrupted
          (check your environment variables or try re-installing?)
        * You're on Windows and your Python installation was somehow corrupted
          (check your environment variables or try re-installing?)
      Traceback (most recent call last):
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 186, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
        File "/private/var/folders/w2/1ctlcj0x56l7t3zxwf1b8c040000gs/T/pip-install-4ht91ou0/grpcio_c35d07ccb99c4ffda57f9db5df1dda4f/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
          _classic_spawn(self, command)
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py", line 1007, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/usr/bin/clang' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/private/var/folders/w2/1ctlcj0x56l7t3zxwf1b8c040000gs/T/pip-install-4ht91ou0/grpcio_c35d07ccb99c4ffda57f9db5df1dda4f/src/python/grpcio/commands.py", line 280, in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
          self._build_extensions_serial()
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
          self.build_extension(ext)
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 549, in build_extension
          objects = self.compiler.compile(
        File "/private/var/folders/w2/1ctlcj0x56l7t3zxwf1b8c040000gs/T/pip-install-4ht91ou0/grpcio_c35d07ccb99c4ffda57f9db5df1dda4f/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
          multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 364, in map
          return self._map_async(func, iterable, mapstar, chunksize).get()
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 771, in get
          raise self._value
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
          result = (True, func(*args, **kwds))
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
          return list(map(*args))
        File "/private/var/folders/w2/1ctlcj0x56l7t3zxwf1b8c040000gs/T/pip-install-4ht91ou0/grpcio_c35d07ccb99c4ffda57f9db5df1dda4f/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/private/var/folders/w2/1ctlcj0x56l7t3zxwf1b8c040000gs/T/pip-install-4ht91ou0/grpcio_c35d07ccb99c4ffda57f9db5df1dda4f/src/python/grpcio/commands.py", line 263, in new_compile
          return old_compile(obj, src, ext, cc_args, extra_postargs,
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 188, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/clang' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/w2/1ctlcj0x56l7t3zxwf1b8c040000gs/T/pip-install-4ht91ou0/grpcio_c35d07ccb99c4ffda57f9db5df1dda4f/setup.py", line 535, in <module>
          setuptools.setup(
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/Users/hamzahc/guardian/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/private/var/folders/w2/1ctlcj0x56l7t3zxwf1b8c040000gs/T/pip-install-4ht91ou0/grpcio_c35d07ccb99c4ffda57f9db5df1dda4f/src/python/grpcio/commands.py", line 283, in build_extensions
          support.diagnose_build_ext_error(self, error, formatted_exception)
        File "/private/var/folders/w2/1ctlcj0x56l7t3zxwf1b8c040000gs/T/pip-install-4ht91ou0/grpcio_c35d07ccb99c4ffda57f9db5df1dda4f/src/python/grpcio/support.py", line 117, in diagnose_build_ext_error
          diagnostic(build_ext, error)
        File "/private/var/folders/w2/1ctlcj0x56l7t3zxwf1b8c040000gs/T/pip-install-4ht91ou0/grpcio_c35d07ccb99c4ffda57f9db5df1dda4f/src/python/grpcio/support.py", line 76, in diagnose_compile_error
          _expect_compile(build_ext.compiler, c_check, message)
        File "/private/var/folders/w2/1ctlcj0x56l7t3zxwf1b8c040000gs/T/pip-install-4ht91ou0/grpcio_c35d07ccb99c4ffda57f9db5df1dda4f/src/python/grpcio/support.py", line 68, in _expect_compile
          raise commands.CommandError(
      commands.CommandError: Diagnostics found a compilation environment issue:
      
      Could not find <Python.h>. This could mean the following:
        * You're on Ubuntu and haven't run `apt-get install python3-dev`.
        * You're on RHEL/Fedora and haven't run `yum install python3-devel` or
          `dnf install python3-devel` (make sure you also have redhat-rpm-config
          installed)
        * You're on Mac OS X and the usual Python framework was somehow corrupted
          (check your environment variables or try re-installing?)
        * You're on Windows and your Python installation was somehow corrupted
          (check your environment variables or try re-installing?)
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> grpcio
```

**Comment by chr4ss12** [comment]
I can see python3.9 in your path, that's not suppported, 3.6, 3.7 or 3.8.

https://github.com/nccgroup/ScoutSuite/wiki/Setup
