### ISSUE TITLE
Azure RBAC cli "Failed to retrieve roles: __init__() got an unexpected keyword argument 'user_agent'"

### ISSUE THREAD

**Issue by zachfey** [nccgroup/ScoutSuite#1502]
When running the Azure RBAC service using CLI authentication (`scout azure --cli --services rbac`) I get the errors:

```
rbac.py L21: Failed to retrieve roles: __init__() got an unexpected keyword argument 'user_agent'
rbac.py L30: Failed to retrieve role assignments: __init__() got an unexpected keyword argument 'user_agent'
rbac.py L21: Failed to retrieve roles: __init__() got an unexpected keyword argument 'user_agent'
```

Console Output:
```
2023-03-02 17:23:32 e498d851c8e8 scout[69] INFO Launching Scout
2023-03-02 17:23:32 e498d851c8e8 scout[69] INFO Authenticating to cloud provider
2023-03-02 17:23:34 e498d851c8e8 scout[69] INFO No subscription set, inferring
2023-03-02 17:23:34 e498d851c8e8 scout[69] INFO Running against subscription 60dcd589-4676-487b-9108-c6a0ec8736da
2023-03-02 17:23:35 e498d851c8e8 scout[69] INFO Gathering data from APIs
2023-03-02 17:23:35 e498d851c8e8 scout[69] DEBUG Skipping the Azure Active Directory service
2023-03-02 17:23:35 e498d851c8e8 scout[69] DEBUG Skipping the Security Center service
2023-03-02 17:23:35 e498d851c8e8 scout[69] DEBUG Skipping the SQL Database service
2023-03-02 17:23:35 e498d851c8e8 scout[69] DEBUG Skipping the Storage Accounts service
2023-03-02 17:23:35 e498d851c8e8 scout[69] DEBUG Skipping the Key Vault service
2023-03-02 17:23:35 e498d851c8e8 scout[69] DEBUG Skipping the Network service
2023-03-02 17:23:35 e498d851c8e8 scout[69] DEBUG Skipping the Virtual Machines service
2023-03-02 17:23:35 e498d851c8e8 scout[69] DEBUG Skipping the App Services service
2023-03-02 17:23:35 e498d851c8e8 scout[69] DEBUG Skipping the MySQL Database service
2023-03-02 17:23:35 e498d851c8e8 scout[69] DEBUG Skipping the PostgresSQL Database service
2023-03-02 17:23:35 e498d851c8e8 scout[69] DEBUG Skipping the Logging Monitoring service
2023-03-02 17:23:35 e498d851c8e8 scout[69] INFO Fetching resources for the Azure RBAC service
2023-03-02 17:23:35 e498d851c8e8 scout[69] ERROR rbac.py L21: Failed to retrieve roles: __init__() got an unexpected keyword argument 'user_agent'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ScoutSuite/providers/azure/facade/rbac.py", line 21, in get_roles
    client = self.get_client(subscription_id)
  File "/usr/local/lib/python3.8/site-packages/ScoutSuite/providers/azure/facade/rbac.py", line 14, in get_client
    client = AuthorizationManagementClient(self.credentials.get_credentials(),
TypeError: __init__() got an unexpected keyword argument 'user_agent'
2023-03-02 17:23:35 e498d851c8e8 scout[69] ERROR rbac.py L30: Failed to retrieve role assignments: __init__() got an unexpected keyword argument 'user_agent'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ScoutSuite/providers/azure/facade/rbac.py", line 30, in get_role_assignments
    client = self.get_client(subscription_id)
  File "/usr/local/lib/python3.8/site-packages/ScoutSuite/providers/azure/facade/rbac.py", line 14, in get_client
    client = AuthorizationManagementClient(self.credentials.get_credentials(),
TypeError: __init__() got an unexpected keyword argument 'user_agent'
2023-03-02 17:23:35 e498d851c8e8 scout[69] ERROR rbac.py L21: Failed to retrieve roles: __init__() got an unexpected keyword argument 'user_agent'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ScoutSuite/providers/azure/facade/rbac.py", line 21, in get_roles
    client = self.get_client(subscription_id)
  File "/usr/local/lib/python3.8/site-packages/ScoutSuite/providers/azure/facade/rbac.py", line 14, in get_client
    client = AuthorizationManagementClient(self.credentials.get_credentials(),
TypeError: __init__() got an unexpected keyword argument 'user_agent'
2023-03-02 17:23:35 e498d851c8e8 scout[69] INFO Running pre-processing engine
2023-03-02 17:23:35 e498d851c8e8 scout[69] INFO Running rule engine
2023-03-02 17:23:35 e498d851c8e8 scout[69] DEBUG Loading ruleset /usr/local/lib/python3.8/site-packages/ScoutSuite/providers/azure/rules/rulesets/default.json
2023-03-02 17:23:35 e498d851c8e8 scout[69] DEBUG Processing Azure RBAC rule "No Administering Resource Locks Role" (rbac-administering-resource-locks-assigned.json)
2023-03-02 17:23:35 e498d851c8e8 scout[69] DEBUG Processing Azure RBAC rule "Custom Subscription Owner Role Not Allowed" (rbac-custom-subscription-owner-role-not-allowed.json)
2023-03-02 17:23:35 e498d851c8e8 scout[69] INFO Applying display filters
2023-03-02 17:23:35 e498d851c8e8 scout[69] DEBUG Loading ruleset /usr/local/lib/python3.8/site-packages/ScoutSuite/providers/azure/rules/rulesets/filters.json
2023-03-02 17:23:35 e498d851c8e8 scout[69] INFO Running post-processing engine
2023-03-02 17:23:35 e498d851c8e8 scout[69] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_results_azure-tenant-d9cad9c9-53d2-4ed6-9109-b36162d3c7fc.js
```

Error File:
```
[
    {
        "additional_details": null,
        "exception": "Failed to retrieve roles: __init__() got an unexpected keyword argument 'user_agent'",
        "file": "rbac.py",
        "line": 21,
        "traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/ScoutSuite/providers/azure/facade/rbac.py\", line 21, in get_roles\n    client = self.get_client(subscription_id)\n  File \"/usr/local/lib/python3.8/site-packages/ScoutSuite/providers/azure/facade/rbac.py\", line 14, in get_client\n    client = AuthorizationManagementClient(self.credentials.get_credentials(),\nTypeError: __init__() got an unexpected keyword argument 'user_agent'\n"
    },
    {
        "additional_details": null,
        "exception": "Failed to retrieve role assignments: __init__() got an unexpected keyword argument 'user_agent'",
        "file": "rbac.py",
        "line": 30,
        "traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/ScoutSuite/providers/azure/facade/rbac.py\", line 30, in get_role_assignments\n    client = self.get_client(subscription_id)\n  File \"/usr/local/lib/python3.8/site-packages/ScoutSuite/providers/azure/facade/rbac.py\", line 14, in get_client\n    client = AuthorizationManagementClient(self.credentials.get_credentials(),\nTypeError: __init__() got an unexpected keyword argument 'user_agent'\n"
    },
    {
        "additional_details": null,
        "exception": "Failed to retrieve roles: __init__() got an unexpected keyword argument 'user_agent'",
        "file": "rbac.py",
        "line": 21,
        "traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/ScoutSuite/providers/azure/facade/rbac.py\", line 21, in get_roles\n    client = self.get_client(subscription_id)\n  File \"/usr/local/lib/python3.8/site-packages/ScoutSuite/providers/azure/facade/rbac.py\", line 14, in get_client\n    client = AuthorizationManagementClient(self.credentials.get_credentials(),\nTypeError: __init__() got an unexpected keyword argument 'user_agent'\n"
    }
]

```

This is running on the most recent release, 5.12.0. I believe this is likely related to the recent changes to Authentication

**Comment by zachfey** [comment]
I believe my package dependencies got out of date somehow.
