### ISSUE TITLE
 Failure while running pre-processing engine: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by hacker07UK** [nccgroup/ScoutSuite#1536]
**Describe the bug**

This Bug is related to __main__.py L211: Initialization failure: global flags not at the start of the expression at position 6

I could not able to get past this error even after I pull the request with solution : https://github.com/nccgroup/ScoutSuite/issues/1511 

This seems to work for me : 

- cp -r ScoutSuite ScoutSuite_fixed - create new local version of scout
- cd ScoutSuite_fixed/ScoutSuite/providers
- rm utils.py - remove file causes an error
- wget https://raw.githubusercontent.com/nccgroup/ScoutSuite/8f937535edac9a7a2751905f741d39e777be2e72/ScoutSuite/providers/utils.py - download fixed version
- cd ../..
- python3 scout.py aws - start scout using default configured aws profile
- 
however  just before pre-processing I ended up having this error : 

 ERROR __main__.py L300: Failure while running pre-processing engine: 'NoneType' object is not iterable

It would be great if you could help me get past the original error or this error

**Comment by liyun-li** [comment]
@hacker07UK - Can you rerun scout with `--debug` and paste the error?

**Comment by Drjacky** [comment]
```bash
➜  Scanner scout aws --debug
2023-06-05 09:32:06 MacBook-Pro.local scout[7940] INFO Launching Scout
2023-06-05 09:32:06 MacBook-Pro.local scout[7940] INFO Authenticating to cloud provider
2023-06-05 09:32:06 MacBook-Pro.local scout[7940] ERROR __main__.py L211: Initialization failure: global flags not at the start of the expression at position 6
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/ScoutSuite/__main__.py", line 211, in _run
    cloud_provider = get_provider(provider=provider,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ScoutSuite/providers/__init__.py", line 36, in get_provider
    provider_object = get_provider_object(provider)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ScoutSuite/providers/__init__.py", line 10, in get_provider_object
    provider_module = __import__(f'ScoutSuite.providers.{provider}.provider', fromlist=[provider_class])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ScoutSuite/providers/aws/provider.py", line 5, in <module>
    from ScoutSuite.providers.aws.services import AWSServicesConfig
  File "/opt/homebrew/lib/python3.11/site-packages/ScoutSuite/providers/aws/services.py", line 1, in <module>
    from ScoutSuite.providers.aws.facade.base import AWSFacade
  File "/opt/homebrew/lib/python3.11/site-packages/ScoutSuite/providers/aws/facade/base.py", line 3, in <module>
    from ScoutSuite.providers.aws.facade.acm import AcmFacade
  File "/opt/homebrew/lib/python3.11/site-packages/ScoutSuite/providers/aws/facade/acm.py", line 3, in <module>
    from ScoutSuite.providers.aws.facade.utils import AWSFacadeUtils
  File "/opt/homebrew/lib/python3.11/site-packages/ScoutSuite/providers/aws/facade/utils.py", line 5, in <module>
    from ScoutSuite.providers.utils import run_concurrently
  File "/opt/homebrew/lib/python3.11/site-packages/ScoutSuite/providers/utils.py", line 139, in <module>
    re.compile("(p8e-)(?i)[a-z0-9]{32}"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 6
```

@liyun-li

**Comment by liyun-li** [comment]
Interesting...We will certainly look into it!
