### ISSUE TITLE
EKS : Could not fetch EKS configuration: 'resource'

### ISSUE THREAD

**Issue by LleeTossel** [nccgroup/ScoutSuite#1677]
**Describe the bug**

When using ScoutSuite to audit an EKS cluster, the following error occurs.  

- Console Output: 

```
2024-11-05 11:08:11 localhost.localdomain scout[171226] INFO Fetching resources for the EKS service
'resources'
2024-11-05 11:08:12 localhost.localdomain scout[171226] ERROR services.py L56: Could not fetch EKS configuration: 'resources'
Traceback (most recent call last):
  File "/home/lleetossel/work/git/ScoutSuite/testenv/ScoutSuite/providers/base/services.py", line 56, in _fetch
    await service_config.fetch_all(**method_args)
  File "/home/lleetossel/work/git/ScoutSuite/testenv/ScoutSuite/providers/kubernetes/resources/base.py", line 47, in fetch_all
    self[f'{child_name}_{version}_count'] = len(data[version]['resources'])
                                                ~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'resources'

```

This was tested on multiple clusters all with the same result. 

Python version 3.13

**To Reproduce**

- This is the CLI command used: 
```
python3 ./scout.py kubernetes --no-browser --report-dir ./report/kubernetes --cluster-provider eks --max-rate 10 --debug
```
- The role used had full access to all EKS actions for the cluster.

**Comment by liyun-li** [comment]
k8s made quite a few changes to its api and i will need to fix it. stay tuned! (it's gonna be a slow fix from our end so PRs are appreciated)

**Comment by liyun-li** [comment]
in the meantime try running the tool without `-c eks`
