### ISSUE TITLE
Failed to describe RDS snapshot attributes

### ISSUE THREAD

**Issue by heydonovan** [nccgroup/ScoutSuite#454]
I'm using the latest version from the master branch:

```
(venv) bash-5.0$ python scout.py aws --profile scout --regions us-east-1
2019-06-21 13:30:48 scout[44868] INFO Launching Scout
2019-06-21 13:30:48 scout[44868] INFO Authenticating to cloud provider
2019-06-21 13:30:49 scout[44868] INFO Gathering data from APIs
2019-06-21 13:30:49 scout[44868] INFO Fetching resources for the Lambda service
2019-06-21 13:30:49 scout[44868] INFO Fetching resources for the CloudFormation service
2019-06-21 13:30:49 scout[44868] INFO Fetching resources for the CloudTrail service
2019-06-21 13:30:49 scout[44868] INFO Fetching resources for the CloudWatch service
2019-06-21 13:30:49 scout[44868] INFO Fetching resources for the Config service
2019-06-21 13:30:50 scout[44868] INFO Fetching resources for the Direct Connect service
2019-06-21 13:30:50 scout[44868] INFO Fetching resources for the EC2 service
2019-06-21 13:30:50 scout[44868] INFO Fetching resources for the EFS service
2019-06-21 13:30:50 scout[44868] INFO Fetching resources for the ElastiCache service
2019-06-21 13:30:51 scout[44868] INFO Fetching resources for the ELB service
2019-06-21 13:30:51 scout[44868] INFO Fetching resources for the ELBv2 service
2019-06-21 13:30:51 scout[44868] INFO Fetching resources for the EMR service
2019-06-21 13:30:51 scout[44868] INFO Fetching resources for the IAM service
2019-06-21 13:30:51 scout[44868] INFO Fetching resources for the RDS service
2019-06-21 13:30:52 scout[44868] INFO Fetching resources for the RedShift service
2019-06-21 13:30:52 scout[44868] INFO Fetching resources for the Route53 service
2019-06-21 13:30:52 scout[44868] INFO Fetching resources for the S3 service
2019-06-21 13:30:52 scout[44868] INFO Fetching resources for the SES service
2019-06-21 13:30:53 scout[44868] INFO Fetching resources for the SNS service
2019-06-21 13:30:53 scout[44868] INFO Fetching resources for the SQS service
2019-06-21 13:30:53 scout[44868] INFO Fetching resources for the VPC service
2019-06-21 13:31:33 scout[44868] ERROR rds.py L74: Failed to describe RDS snapshot attributes: An error occurred (Throttling) when calling the DescribeDBSnapshotAttributes operation (reached max retries: 4): Rate exceeded
2019-06-21 13:31:37 scout[44868] ERROR rds.py L74: Failed to describe RDS snapshot attributes: An error occurred (Throttling) when calling the DescribeDBSnapshotAttributes operation (reached max retries: 4): Rate exceeded
2019-06-21 13:31:40 scout[44868] ERROR rds.py L74: Failed to describe RDS snapshot attributes: An error occurred (Throttling) when calling the DescribeDBSnapshotAttributes operation (reached max retries: 4): Rate exceeded
2019-06-21 13:31:40 scout[44868] ERROR rds.py L74: Failed to describe RDS snapshot attributes: An error occurred (Throttling) when calling the DescribeDBSnapshotAttributes operation (reached max retries: 4): Rate exceeded
2019-06-21 13:31:40 scout[44868] ERROR rds.py L74: Failed to describe RDS snapshot attributes: An error occurred (Throttling) when calling the DescribeDBSnapshotAttributes operation (reached max retries: 4): Rate exceeded
2019-06-21 13:31:41 scout[44868] ERROR rds.py L74: Failed to describe RDS snapshot attributes: An error occurred (Throttling) when calling the DescribeDBSnapshotAttributes operation (reached max retries: 4): Rate exceeded
2019-06-21 13:31:42 scout[44868] ERROR rds.py L74: Failed to describe RDS snapshot attributes: An error occurred (Throttling) when calling the DescribeDBSnapshotAttributes operation (reached max retries: 4): Rate exceeded
2019-06-21 13:31:43 scout[44868] ERROR rds.py L74: Failed to describe RDS snapshot attributes: An error occurred (Throttling) when calling the DescribeDBSnapshotAttributes operation (reached max retries: 4): Rate exceeded
2019-06-21 13:31:43 scout[44868] ERROR rds.py L74: Failed to describe RDS snapshot attributes: An error occurred (Throttling) when calling the DescribeDBSnapshotAttributes operation (reached max retries: 4): Rate exceeded
2019-06-21 13:31:44 scout[44868] ERROR rds.py L74: Failed to describe RDS snapshot attributes: An error occurred (Throttling) when calling the DescribeDBSnapshotAttributes operation (reached max retries: 4): Rate exceeded
2019-06-21 13:31:45 scout[44868] ERROR rds.py L74: Failed to describe RDS snapshot attributes: An error occurred (Throttling) when calling the DescribeDBSnapshotAttributes operation (reached max retries: 4): Rate exceeded
2019-06-21 13:31:47 scout[44868] ERROR rds.py L74: Failed to describe RDS snapshot attributes: An error occurred (Throttling) when calling the DescribeDBSnapshotAttributes operation (reached max retries: 4): Rate exceeded
2019-06-21 13:31:50 scout[44868] ERROR rds.py L74: Failed to describe RDS snapshot attributes: An error occurred (Throttling) when calling the DescribeDBSnapshotAttributes operation (reached max retries: 4): Rate exceeded
2019-06-21 13:31:53 scout[44868] ERROR rds.py L74: Failed to describe RDS snapshot attributes: An error occurred (Throttling) when calling the DescribeDBSnapshotAttributes operation (reached max retries: 4): Rate exceeded
2019-06-21 13:31:54 scout[44868] ERROR rds.py L74: Failed to describe RDS snapshot attributes: An error occurred (Throttling) when calling the DescribeDBSnapshotAttributes operation (reached max retries: 4): Rate exceeded
2019-06-21 13:31:56 scout[44868] ERROR rds.py L74: Failed to describe RDS snapshot attributes: An error occurred (Throttling) when calling the DescribeDBSnapshotAttributes operation (reached max retries: 4): Rate exceeded
2019-06-21 13:31:59 scout[44868] ERROR rds.py L74: Failed to describe RDS snapshot attributes: An error occurred (Throttling) when calling the DescribeDBSnapshotAttributes operation (reached max retries: 4): Rate exceeded
2019-06-21 13:32:00 scout[44868] ERROR rds.py L74: Failed to describe RDS snapshot attributes: An error occurred (Throttling) when calling the DescribeDBSnapshotAttributes operation (reached max retries: 4): Rate exceeded
Task exception was never retrieved
future: <Task finished coro=<Snapshots.fetch_all() done, defined at /Users/heydonovan/ScoutSuite/ScoutSuite/providers/aws/resources/rds/snapshots.py:11> exception=KeyError('Attributes',)>
Traceback (most recent call last):
  File "/Users/heydonovan/ScoutSuite/ScoutSuite/providers/aws/resources/rds/snapshots.py", line 14, in fetch_all
    name, resource = self._parse_snapshot(raw_snapshot)
  File "/Users/heydonovan/ScoutSuite/ScoutSuite/providers/aws/resources/rds/snapshots.py", line 24, in _parse_snapshot
    snapshot['attributes'] = raw_snapshot['Attributes']
KeyError: 'Attributes'
2019-06-21 13:32:07 scout[44868] INFO Matching EC2 instances and IAM roles
2019-06-21 13:32:07 scout[44868] INFO Processing CloudTrail config
2019-06-21 13:32:07 scout[44868] INFO Running rule engine
2019-06-21 13:32:12 scout[44868] INFO Applying display filters
2019-06-21 13:32:18 scout[44868] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_results_aws-scout.js
2019-06-21 13:32:18 scout[44868] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_exceptions_aws-scout.js
2019-06-21 13:32:18 scout[44868] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_errors_aws-scout.json
2019-06-21 13:32:18 scout[44868] INFO Creating scoutsuite-report/aws-scout.html
2019-06-21 13:32:18 scout[44868] INFO Opening the HTML report
```

**Comment by j4v** [comment]
@heydonovan this isn't a Scout error per se but rather that the API calls are exceeding your account's quota. I recommend trying to run it with a lower `--max-workers` count (e.g. 3) and see if that solves it.

**Comment by j4v** [comment]
Closing, handling rate limiting is being worked on as part of https://github.com/nccgroup/ScoutSuite/issues/91. 

Feel free to try out the https://github.com/nccgroup/ScoutSuite/pull/461 branch.
