### ISSUE TITLE
'NoneType' object has no attribute 'get_caller_identity'

### ISSUE THREAD

**Issue by pcpolice** [nccgroup/ScoutSuite#47]
Hi All,

I'm not a programmer by any means and this is all new. I only realised there is a newer version available instead of the Scout2 deprecated package. I have successfully installed it using

`pip install ScoutSuite`

Run the application:
`Scout --provider aws --profile <profile name>`

The application starts doing its thing and then:
    Error: could not fetch directconnect configuration.
    'NoneType' object has no attribute 'get_caller_identity'
    
    Error: could not fetch elasticache configuration.
    'NoneType' object has no attribute 'get_caller_identity'
    
    Error: could not fetch route53 configuration.
    'NoneType' object has no attribute 'get_caller_identity'
    
    Error: could not fetch sns configuration.
    'NoneType' object has no attribute 'get_caller_identity'
    Traceback (most recent call last):
      File "c:\python27\Scripts\Scout-script.py", line 11, in <module>
        load_entry_point('ScoutSuite==4.0.5', 'console_scripts', 'Scout')()
      File "c:\python27\lib\site-packages\ScoutSuite\__main__.py", line 101, in main
        cloud_provider.fetch(regions=args.regions)
      File "c:\python27\lib\site-packages\ScoutSuite\providers\base\provider.py", line 99, in fetch
        self.services = report.jsrw.to_dict(self.services)
      File "c:\python27\lib\site-packages\ScoutSuite\output\js.py", line 77, in to_dict
        return json.loads(json.dumps(config, separators=(',', ': '), cls=Scout2Encoder))
      File "c:\python27\lib\json\__init__.py", line 251, in dumps
        sort_keys=sort_keys, **kw).encode(obj)
      File "c:\python27\lib\json\encoder.py", line 207, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "c:\python27\lib\json\encoder.py", line 270, in iterencode
        return _iterencode(o, 0)
    MemoryError

Not too sure what's going on. 

Is this an issue on my end or something else?

Thanks.

**Comment by pcpolice** [comment]
After building in Windows, I didn't have error.
