### ISSUE TITLE
AssumeRole with credential_source = Ec2InstanceMetadata gives AccessDenied with Scout v5.2

### ISSUE THREAD

**Issue by saurabh0mishra** [nccgroup/ScoutSuite#481]
### scout command:

> python3 scout.py aws --profile infosec-xxxx --force --no-browser --report-dir ../new_reports --ruleset default --debug

### I get the following error:

```
2019-07-27 12:33:49 ip-10-xxx-xxx-xxx scout[1291] INFO Launching Scout
2019-07-27 12:33:49 ip-10-xxx-xxx-xxx scout[1291] INFO Authenticating to cloud provider
2019-07-27 12:33:50 ip-10-xxx-xxx-xxx scout[1291] ERROR __main__.py L153: Authentication failure: An error occurred (AccessDenied) when calling the AssumeRole operation: Access denied
Traceback (most recent call last):
  File "/home/ubuntu/new_scout_5.2/ScoutSuite/ScoutSuite/providers/aws/authentication_strategy.py", line 20, in authenticate
    sts_client.get_caller_identity()
  File "/home/ubuntu/new_scout_5.2/scout_5.2_venv/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/new_scout_5.2/scout_5.2_venv/lib/python3.6/site-packages/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "/home/ubuntu/new_scout_5.2/scout_5.2_venv/lib/python3.6/site-packages/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/ubuntu/new_scout_5.2/scout_5.2_venv/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/ubuntu/new_scout_5.2/scout_5.2_venv/lib/python3.6/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/ubuntu/new_scout_5.2/scout_5.2_venv/lib/python3.6/site-packages/botocore/endpoint.py", line 116, in create_request
    operation_name=operation_model.name)
  File "/home/ubuntu/new_scout_5.2/scout_5.2_venv/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/ubuntu/new_scout_5.2/scout_5.2_venv/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/ubuntu/new_scout_5.2/scout_5.2_venv/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/ubuntu/new_scout_5.2/scout_5.2_venv/lib/python3.6/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/home/ubuntu/new_scout_5.2/scout_5.2_venv/lib/python3.6/site-packages/botocore/signers.py", line 149, in sign
    auth = self.get_auth_instance(**kwargs)
  File "/home/ubuntu/new_scout_5.2/scout_5.2_venv/lib/python3.6/site-packages/botocore/signers.py", line 229, in get_auth_instance
    frozen_credentials = self._credentials.get_frozen_credentials()
  File "/home/ubuntu/new_scout_5.2/scout_5.2_venv/lib/python3.6/site-packages/botocore/credentials.py", line 518, in get_frozen_credentials
    self._refresh()
  File "/home/ubuntu/new_scout_5.2/scout_5.2_venv/lib/python3.6/site-packages/botocore/credentials.py", line 413, in _refresh
    self._protected_refresh(is_mandatory=is_mandatory_refresh)
  File "/home/ubuntu/new_scout_5.2/scout_5.2_venv/lib/python3.6/site-packages/botocore/credentials.py", line 429, in _protected_refresh
    metadata = self._refresh_using()
  File "/home/ubuntu/new_scout_5.2/scout_5.2_venv/lib/python3.6/site-packages/botocore/credentials.py", line 566, in fetch_credentials
    return self._get_cached_credentials()
  File "/home/ubuntu/new_scout_5.2/scout_5.2_venv/lib/python3.6/site-packages/botocore/credentials.py", line 576, in _get_cached_credentials
    response = self._get_credentials()
  File "/home/ubuntu/new_scout_5.2/scout_5.2_venv/lib/python3.6/site-packages/botocore/credentials.py", line 698, in _get_credentials
    return client.assume_role(**kwargs)
  File "/home/ubuntu/new_scout_5.2/scout_5.2_venv/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/new_scout_5.2/scout_5.2_venv/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: Access denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/new_scout_5.2/ScoutSuite/ScoutSuite/__main__.py", line 153, in _run
    programmatic_execution=programmatic_execution)
  File "/home/ubuntu/new_scout_5.2/ScoutSuite/ScoutSuite/providers/aws/authentication_strategy.py", line 25, in authenticate
    raise AuthenticationException(e)
ScoutSuite.providers.base.authentication_strategy.AuthenticationException: An error occurred (AccessDenied) when calling the AssumeRole operation: Access denied
```
### AWS Config
[profile infosec-xxx]
metadata_service_num_attempts = 5
region=ap-southeast-1
role_arn=arn:aws:iam::55XXXXXXXXXX12:role/security-role
aws_external_id=UXXXXXXXXXX1
credential_source=Ec2InstanceMetadata

### scout v4.2.post5 is running fine

> python3 Scout.py aws --profile infosec-xxxx --force --no-browser --report-dir ../new_reports --ruleset default --debug

### scout v4.2.post5 output
`Role's credentials have expired on 2019-07-26 12:13:25+00:00
Connecting to AWS sts...
Fetching CloudFormation config...
             regions             stacks
                4/16              45/47`

**I also tried to run scout from branch** `experimental/handle-aws-rate-limiting` **as this branch has different code for authentication_strategy.py but still getting the same error.**

**Comment by j4v** [comment]
Does the CLI for `infosec-xxxx` run without any errors?

**Comment by saurabh0mishra** [comment]
Didn't try CLI but scout v4.2 is running fine.
I'll check with CLI and will let you know.
Thanks!

**Comment by saurabh0mishra** [comment]
@j4v To run the commands from CLI for other aws accounts, I get the sts token first for the account using below command:
`aws sts assume-role --role-arn "arn:aws:iam::5XXXXXXXXXX2:role/xxxx-security-XXXX" --role-session-name "Temp-Session" --external-id UIXXXXXXXXX1`

Then I add the AccessKeyId, SecretAccessKey, and SessionToken into the credentials file and then I can get the resource info from CLI for 5XXXXXXXXXX2 aws account. 
After adding credentials into the ~/.aws/credentials file, `aws s3 ls` gives me the list of s3 buckets for 5XXXXXXXXXX2 account.

**Comment by j4v** [comment]
I'm not sure what the issue is then. Scout now uses boto3 directly (hence the difference with v4.2 which used a custom implementation). If it's running with the CLI, it should run with Scout. 

Your 2 options are:
- Get the temporary tokens as you describe and use that nammed profile
- Setup the config/credentials file to do the role assumption seamlessly (see https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#assume-role-provider).

**Comment by saurabh0mishra** [comment]
@j4v found the issue. It is because of aws_external_id. 
It should be external_id only.

**AWS Config**

```
[profile infosec-xxx]
metadata_service_num_attempts = 5
region=ap-southeast-1
role_arn=arn:aws:iam::55XXXXXXXXXX12:role/security-role
external_id=UXXXXXXXXXX1
credential_source=Ec2InstanceMetadata
```
