### ISSUE TITLE
Bug/Azure Errors with MSI Authentication

### ISSUE THREAD

**Issue by sidewinder31** [nccgroup/ScoutSuite#485]
Trying to run ScoutSuite on an Azure environment in a Linux VM using the `--msi` switch and **Reader** role assigned.

OS: Ubuntu 18.04.2 LTS
Kernel Version: 4.18.0-1025-azure

The script throws below errors while testing for storage accounts:

```2019-07-31 17:27:48 TestVM scout[1905] INFO Fetching resources for the Storage Accounts service
2019-07-31 17:27:48 TestVM scout[1905] ERROR securitycenter.py L13: Failed to retrieve pricings: 'PricingList' object is not iterable
Traceback (most recent call last):
  File "/home/pt/venv/lib/python3.6/site-packages/ScoutSuite/providers/azure/facade/securitycenter.py", line 13, in get_pricings
    lambda: list(self._client.pricings.list())
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pt/venv/lib/python3.6/site-packages/ScoutSuite/providers/azure/facade/securitycenter.py", line 13, in <lambda>
    lambda: list(self._client.pricings.list())
TypeError: 'PricingList' object is not iterable
2019-07-31 17:27:53 TestVM scout[1905] ERROR storageaccounts.py L30: Failed to retrieve blob containers: 'ListContainerItemPaged' object has no attribute 'value'
Traceback (most recent call last):
  File "/home/pt/venv/lib/python3.6/site-packages/ScoutSuite/providers/azure/facade/storageaccounts.py", line 30, in get_blob_containers
    lambda: list(self._client.blob_containers.list(resource_group_name, storage_account_name).value)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pt/venv/lib/python3.6/site-packages/ScoutSuite/providers/azure/facade/storageaccounts.py", line 30, in <lambda>
    lambda: list(self._client.blob_containers.list(resource_group_name, storage_account_name).value)
AttributeError: 'ListContainerItemPaged' object has no attribute 'value'
2019-07-31 17:27:53 TestVM scout[1905] ERROR storageaccounts.py L30: Failed to retrieve blob containers: 'ListContainerItemPaged' object has no attribute 'value'
Traceback (most recent call last):
  File "/home/pt/venv/lib/python3.6/site-packages/ScoutSuite/providers/azure/facade/storageaccounts.py", line 30, in get_blob_containers
    lambda: list(self._client.blob_containers.list(resource_group_name, storage_account_name).value)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pt/venv/lib/python3.6/site-packages/ScoutSuite/providers/azure/facade/storageaccounts.py", line 30, in <lambda>
    lambda: list(self._client.blob_containers.list(resource_group_name, storage_account_name).value)
AttributeError: 'ListContainerItemPaged' object has no attribute 'value'
2019-07-31 17:27:53 TestVM scout[1905] ERROR storageaccounts.py L30: Failed to retrieve blob containers: 'ListContainerItemPaged' object has no attribute 'value'
Traceback (most recent call last):
  File "/home/pt/venv/lib/python3.6/site-packages/ScoutSuite/providers/azure/facade/storageaccounts.py", line 30, in get_blob_containers
    lambda: list(self._client.blob_containers.list(resource_group_name, storage_account_name).value)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pt/venv/lib/python3.6/site-packages/ScoutSuite/providers/azure/facade/storageaccounts.py", line 30, in <lambda>
    lambda: list(self._client.blob_containers.list(resource_group_name, storage_account_name).value)
AttributeError: 'ListContainerItemPaged' object has no attribute 'value'
2019-07-31 17:27:53 TestVM scout[1905] ERROR storageaccounts.py L30: Failed to retrieve blob containers: 'ListContainerItemPaged' object has no attribute 'value'
Traceback (most recent call last):
  File "/home/pt/venv/lib/python3.6/site-packages/ScoutSuite/providers/azure/facade/storageaccounts.py", line 30, in get_blob_containers
    lambda: list(self._client.blob_containers.list(resource_group_name, storage_account_name).value)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pt/venv/lib/python3.6/site-packages/ScoutSuite/providers/azure/facade/storageaccounts.py", line 30, in <lambda>
    lambda: list(self._client.blob_containers.list(resource_group_name, storage_account_name).value)
AttributeError: 'ListContainerItemPaged' object has no attribute 'value'
2019-07-31 17:27:53 TestVM scout[1905] ERROR storageaccounts.py L30: Failed to retrieve blob containers: 'ListContainerItemPaged' object has no attribute 'value'
Traceback (most recent call last):
  File "/home/pt/venv/lib/python3.6/site-packages/ScoutSuite/providers/azure/facade/storageaccounts.py", line 30, in get_blob_containers
    lambda: list(self._client.blob_containers.list(resource_group_name, storage_account_name).value)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pt/venv/lib/python3.6/site-packages/ScoutSuite/providers/azure/facade/storageaccounts.py", line 30, in <lambda>
    lambda: list(self._client.blob_containers.list(resource_group_name, storage_account_name).value)
AttributeError: 'ListContainerItemPaged' object has no attribute 'value'
2019-07-31 17:27:53 TestVM scout[1905] ERROR storageaccounts.py L30: Failed to retrieve blob containers: 'ListContainerItemPaged' object has no attribute 'value'
Traceback (most recent call last):
  File "/home/pt/venv/lib/python3.6/site-packages/ScoutSuite/providers/azure/facade/storageaccounts.py", line 30, in get_blob_containers
    lambda: list(self._client.blob_containers.list(resource_group_name, storage_account_name).value)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pt/venv/lib/python3.6/site-packages/ScoutSuite/providers/azure/facade/storageaccounts.py", line 30, in <lambda>
    lambda: list(self._client.blob_containers.list(resource_group_name, storage_account_name).value)
AttributeError: 'ListContainerItemPaged' object has no attribute 'value'
2019-07-31 17:27:53 TestVM scout[1905] ERROR storageaccounts.py L30: Failed to retrieve blob containers: 'ListContainerItemPaged' object has no attribute 'value'
Traceback (most recent call last):
  File "/home/pt/venv/lib/python3.6/site-packages/ScoutSuite/providers/azure/facade/storageaccounts.py", line 30, in get_blob_containers
    lambda: list(self._client.blob_containers.list(resource_group_name, storage_account_name).value)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pt/venv/lib/python3.6/site-packages/ScoutSuite/providers/azure/facade/storageaccounts.py", line 30, in <lambda>
    lambda: list(self._client.blob_containers.list(resource_group_name, storage_account_name).value)
AttributeError: 'ListContainerItemPaged' object has no attribute 'value'
2019-07-31 17:27:53 TestVM scout[1905] ERROR storageaccounts.py L30: Failed to retrieve blob containers: 'ListContainerItemPaged' object has no attribute 'value'
Traceback (most recent call last):
  File "/home/pt/venv/lib/python3.6/site-packages/ScoutSuite/providers/azure/facade/storageaccounts.py", line 30, in get_blob_containers
    lambda: list(self._client.blob_containers.list(resource_group_name, storage_account_name).value)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pt/venv/lib/python3.6/site-packages/ScoutSuite/providers/azure/facade/storageaccounts.py", line 30, in <lambda>
    lambda: list(self._client.blob_containers.list(resource_group_name, storage_account_name).value)
AttributeError: 'ListContainerItemPaged' object has no attribute 'value'
2019-07-31 17:27:53 TestVM scout[1905] ERROR storageaccounts.py L30: Failed to retrieve blob containers: 'ListContainerItemPaged' object has no attribute 'value'
Traceback (most recent call last):
  File "/home/pt/venv/lib/python3.6/site-packages/ScoutSuite/providers/azure/facade/storageaccounts.py", line 30, in get_blob_containers
    lambda: list(self._client.blob_containers.list(resource_group_name, storage_account_name).value)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pt/venv/lib/python3.6/site-packages/ScoutSuite/providers/azure/facade/storageaccounts.py", line 30, in <lambda>
    lambda: list(self._client.blob_containers.list(resource_group_name, storage_account_name).value)
AttributeError: 'ListContainerItemPaged' object has no attribute 'value'
2019-07-31 17:27:53 TestVM scout[1905] ERROR storageaccounts.py L30: Failed to retrieve blob containers: 'ListContainerItemPaged' object has no attribute 'value'
Traceback (most recent call last):
  File "/home/pt/venv/lib/python3.6/site-packages/ScoutSuite/providers/azure/facade/storageaccounts.py", line 30, in get_blob_containers
    lambda: list(self._client.blob_containers.list(resource_group_name, storage_account_name).value)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pt/venv/lib/python3.6/site-packages/ScoutSuite/providers/azure/facade/storageaccounts.py", line 30, in <lambda>
    lambda: list(self._client.blob_containers.list(resource_group_name, storage_account_name).value)
AttributeError: 'ListContainerItemPaged' object has no attribute 'value'
2019-07-31 17:27:53 TestVM scout[1905] INFO Running rule engine
```

**Comment by j4v** [comment]
Thanks, could you please run the `develop` branch? I think many of these should already have been resolved.

**Comment by sidewinder31** [comment]
> Thanks, could you please run the `develop` branch? I think many of these should already have been resolved.

Here is what I got running from the `develop` branch:

```
2019-08-02 20:11:26 TestVM scout[51390] INFO Launching Scout
2019-08-02 20:11:26 TestVM scout[51390] INFO Authenticating to cloud provider
2019-08-02 20:11:26 TestVM scout[51390] INFO No subscription set, inferring ID
2019-08-02 20:11:26 TestVM scout[51390] INFO Running against the [[Redacted]] subscription
Traceback (most recent call last):
  File "scout.py", line 8, in <module>
    sys.exit(run_from_cli())
  File "/home/pt/ScoutSuite/ScoutSuite/__main__.py", line 62, in run_from_cli
    programmatic_execution=False)
  File "/home/pt/ScoutSuite/ScoutSuite/__main__.py", line 103, in run
    result = loop.run_until_complete(_run(**locals()))  # pass through all the parameters
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/pt/ScoutSuite/ScoutSuite/__main__.py", line 183, in _run
    credentials=credentials)
  File "/home/pt/ScoutSuite/ScoutSuite/providers/__init__.py", line 47, in get_provider
    **kwargs)
  File "/home/pt/ScoutSuite/ScoutSuite/providers/azure/provider.py", line 32, in __init__
    services, skipped_services, result_format)
  File "/home/pt/ScoutSuite/ScoutSuite/providers/base/provider.py", line 45, in __init__
    self.services = self.services_config(self.credentials)
  File "/home/pt/ScoutSuite/ScoutSuite/providers/azure/services.py", line 37, in __init__
    facade = AzureFacade(credentials)
  File "/home/pt/ScoutSuite/ScoutSuite/providers/azure/facade/base.py", line 37, in __init__
    self.graphrbac = GraphRBACFacade(credentials.graphrbac_credentials, credentials.tenant_id)
  File "/home/pt/ScoutSuite/ScoutSuite/providers/azure/facade/graphrbac.py", line 9, in __init__
    self._client = GraphRbacManagementClient(credentials, tenant_id=tenant_id)
  File "/home/pt/ScoutSuite/venv/lib/python3.6/site-packages/azure/graphrbac/graph_rbac_management_client.py", line 96, in __init__
    self.config = GraphRbacManagementClientConfiguration(credentials, tenant_id, base_url)
  File "/home/pt/ScoutSuite/venv/lib/python3.6/site-packages/azure/graphrbac/graph_rbac_management_client.py", line 47, in __init__
    raise ValueError("Parameter 'tenant_id' must not be None.")
ValueError: Parameter 'tenant_id' must not be None.
```

**Comment by j4v** [comment]
thanks @sidewinder31, will look into it ASAP.

**Comment by j4v** [comment]
@sidewinder31 looks like there's an issue in how we support a specific authentication scenario. Could you provide a redacted example of how you're running the CLI (`python scout.py azure`...) and is there anything unusual on your scenario (cross-tenant auth, etc.)?

**Comment by j4v** [comment]
This should now be fixed in `develop`.
