### ISSUE TITLE
sqlite3 error for all versions of Python 3.5-3.7

### ISSUE THREAD

**Issue by ofello** [nccgroup/ScoutSuite#499]
Apologies if this is due to my ignorance, but I've tried installing Python 3.5, 3.6, and 3.7 (multiple minor releases too) while following directions in the common build problems, the README, etc. 

I should note, previously, I was able to get it up and running.

I'm running CentOS 7 and I continue to get the following error, no matter what I've tried to fix it:

Traceback (most recent call last):
  File "/root/venv/bin/scout", line 6, in <module>
    from ScoutSuite.__main__ import run_from_cli
  File "/root/venv/lib/python3.7/site-packages/ScoutSuite/__main__.py", line 10, in <module>
    from ScoutSuite.core.exceptions import RuleExceptions
  File "/root/venv/lib/python3.7/site-packages/ScoutSuite/core/exceptions.py", line 3, in <module>
    from ScoutSuite.output.result_encoder import JavaScriptEncoder
  File "/root/venv/lib/python3.7/site-packages/ScoutSuite/output/result_encoder.py", line 8, in <module>
    from sqlitedict import SqliteDict
  File "/root/venv/lib/python3.7/site-packages/sqlitedict.py", line 29, in <module>
    import sqlite3
  File "/usr/local/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

**Comment by j4v** [comment]
@ofello can you provide the exact steps you use(d) to install Scout? Looks like a local installation issue, not seeing any issues on our side.

**Comment by j4v** [comment]
Closing due to lack of feedback.
