### ISSUE TITLE
When a target_obj[p] doesn't exist, Scout raises a not required exception

### ISSUE THREAD

**Issue by menendezjaume** [nccgroup/ScoutSuite#561]
Hi there, 

We're currently using ScoutSuite to check the compliance of some of our environments, and we believe we've found a potential bug.

**What version of Python are you using?**
Python 3.6.8

**What operating system and processor architecture are you using?**
Operating System: Ubuntu 18.04.3 LTS
Kernel: Linux 4.15.0-66-generic
Architecture: x86-64

**What did you do?**
Run ScoutSuite against GCP where we host a CloudSQL without the root user.
Our results file looks something like:
```
scoutsuite_results =
{
    "account_id": "project-name",
    "all_projects": false,
    "environment": "default",
    "folder_id": null,
    "last_run": {
    },
    "metadata": {
    },
    "organization_id": null,
    "project_id": "project-name",
    "provider_code": "gcp",
    "provider_name": "Google Cloud Platform",
    "result_format": "json",
    "service_list": [
    ],
    "services": {
        "cloudsql": {
            "filters": {
            },
            "findings": {
            },
            "instances_count": 1,
            "projects": {
                "project-name": {
                    "instances": {
                        "db-id-1": {
                            "authorized_networks": [],
                            "automatic_backup_enabled": true,
                            "backups": {
                            },
                            "backups_count": 2,
                            "database_version": "POSTGRES_9_6",
                            "has_failover_replica": false,
                            "id": "db-id-1",
                            "is_failover_replica": false,
                            "last_backup_timestamp": [
                                "somerandomdate",
                            ],
                            "log_enabled": null,
                            "name": "db-name",
                            "private_ip": "10.0.0.1",
                            "project_id": "project-name",
                            "public_ip": null,
                            "ssl_required": false,
                            "users": {
                                "postgres": {
                                    "host": "",
                                    "name": "postgres"
                                },
                                "person": {
                                    "host": "",
                                    "name": "person"
                                }
                            },
                            "users_count": 2
                        }
                    },
                    "instances_count": 1
                }
            }
        }
    }
}
```

**What did you expect to see?**
A clean output as there isn't a match with any rule (not that it marked it as a match, but marked the run as "with errors" and finished with exit code 200.

**What did you see instead?**
py errors when checking whether the user root (as determined in the rule `cloudsql-allows-root-login-from-any-host.json`) wasn't found:
```
$ scout gcp --project-id project -s gcp_creds.json --debug --no-browser
YYYY-MM-DD HH:03:16 user-at-a-computer scout[25198] INFO Launching Scout
(...)
YYYY-MM-DD HH:05:23 user-at-a-computer scout[25198] INFO Running rule engine
YYYY-MM-DD HH:05:23 user-at-a-computer scout[25198] DEBUG Loading ruleset /some-path/lib/python3.6/site-packages/ScoutSuite/providers/gcp/rules/rulesets/default.json
YYYY-MM-DD HH:05:23 user-at-a-computer scout[25198] DEBUG Processing Cloud Resource Manager rule[cloudresourcemanager-gmail-accounts-used.json]: "Gmail accounts in use"
(...)
YYYY-MM-DD HH:05:23 user-at-a-computer scout[25198] DEBUG Processing Cloud SQL rule[cloudsql-allows-root-login-from-any-host.json]: "Instance allows root login from any host"
YYYY-MM-DD HH:05:23 user-at-a-computer scout[25198] ERROR browser.py L96: 'root'
Traceback (most recent call last):
  File "/some-path/lib/python3.6/site-packages/ScoutSuite/providers/base/configs/browser.py", line 96, in get_value_at
    target_obj = target_obj[p]
KeyError: 'root'
YYYY-MM-DD HH:05:23 user-at-a-computer scout[25198] ERROR browser.py L96: 'host'
Traceback (most recent call last):
  File "/some-path/lib/python3.6/site-packages/ScoutSuite/providers/base/configs/browser.py", line 96, in get_value_at
    target_obj = target_obj[p]
KeyError: 'host'
YYYY-MM-DD HH:05:23 user-at-a-computer scout[25198] ERROR browser.py L96: 'root'
Traceback (most recent call last):
  File "/some-path/lib/python3.6/site-packages/ScoutSuite/providers/base/configs/browser.py", line 96, in get_value_at
    target_obj = target_obj[p]
KeyError: 'root'
YYYY-MM-DD HH:05:23 user-at-a-computer scout[25198] ERROR browser.py L96: 'host'
Traceback (most recent call last):
  File "/some-path/lib/python3.6/site-packages/ScoutSuite/providers/base/configs/browser.py", line 96, in get_value_at
    target_obj = target_obj[p]
KeyError: 'host'
YYYY-MM-DD HH:05:23 user-at-a-computer scout[25198] ERROR browser.py L96: 'root'
Traceback (most recent call last):
  File "/some-path/lib/python3.6/site-packages/ScoutSuite/providers/base/configs/browser.py", line 96, in get_value_at
    target_obj = target_obj[p]
KeyError: 'root'
YYYY-MM-DD HH:05:23 user-at-a-computer scout[25198] ERROR browser.py L96: 'host'
Traceback (most recent call last):
  File "/some-path/lib/python3.6/site-packages/ScoutSuite/providers/base/configs/browser.py", line 96, in get_value_at
    target_obj = target_obj[p]
KeyError: 'host'
YYYY-MM-DD HH:05:23 user-at-a-computer scout[25198] DEBUG Processing Cloud SQL rule[cloudsql-instance-backups-disabled.json]: "Instance with automatic backups disabled"
(...))
YYYY-MM-DD HH:05:23 user-at-a-computer scout[25198] INFO Creating scoutsuite-report/gcp-project.html
YYYY-MM-DD HH:05:23 user-at-a-computer scout[25198] INFO Opening the HTML report
```
**Proposal**
After debugging it, I believe this would be solved if perhaps we checked whether the child object exists here:
https://github.com/nccgroup/ScoutSuite/blob/76c59ad5183b5ebbb7b52f557b8b620984c873b0/ScoutSuite/providers/base/configs/browser.py#L95-L97
Happy to create a PR for this once you've confirmed it.

**Comment by j4v** [comment]
Thanks @menendezjaume, my guess is the rule doesn't validate the field exists.

**Comment by menendezjaume** [comment]
That makes sense, @j4v. 
Is there any way the rule can validate the fields prior to checking their params? I've been playing locally with this `ScoutSuite/providers/gcp/rules/findings/cloudsql-allows-root-login-from-any-host.json` but haven't managed to check whether the user root exists and if not, stop there. 
Hopefully, I'll be wrong, but if not we'll have to change the logic of `ScoutSuite/ScoutSuite/providers/base/configs/browser.py`.

**Comment by j4v** [comment]
@menendezjaume this is typically done with the `notEmpty` condition. I've added the condition to `cloudsql-allows-root-login-from-any-host.json` in the `develop` branch, could you please confirm this resolved your issue?

**Comment by j4v** [comment]
Closing, will reopen if fix did not resolve the issue.

**Comment by menendezjaume** [comment]
Still happening. In fact it happens once more (for your newly created line). See output below:
```
YYYY-MM-DD HH:MM:SS user-at-a-computer scout[15189] ERROR browser.py L96: 'root'
Traceback (most recent call last):
  File ".../ScoutSuite/ScoutSuite/providers/base/configs/browser.py", line 96, in get_value_at
    target_obj = target_obj[p]
KeyError: 'root'
YYYY-MM-DD HH:MM:SS user-at-a-computer scout[15189] ERROR browser.py L96: 'root'
Traceback (most recent call last):
  File ".../ScoutSuite/ScoutSuite/providers/base/configs/browser.py", line 96, in get_value_at
    target_obj = target_obj[p]
KeyError: 'root'
YYYY-MM-DD HH:MM:SS user-at-a-computer scout[15189] ERROR browser.py L96: 'host'
Traceback (most recent call last):
  File ".../ScoutSuite/ScoutSuite/providers/base/configs/browser.py", line 96, in get_value_at
    target_obj = target_obj[p]
KeyError: 'host'
YYYY-MM-DD HH:MM:SS user-at-a-computer scout[15189] ERROR browser.py L96: 'root'
Traceback (most recent call last):
  File ".../ScoutSuite/ScoutSuite/providers/base/configs/browser.py", line 96, in get_value_at
    target_obj = target_obj[p]
KeyError: 'root'
YYYY-MM-DD HH:MM:SS user-at-a-computer scout[15189] ERROR browser.py L96: 'host'
Traceback (most recent call last):
  File ".../ScoutSuite/ScoutSuite/providers/base/configs/browser.py", line 96, in get_value_at
    target_obj = target_obj[p]
KeyError: 'host'
YYYY-MM-DD HH:MM:SS user-at-a-computer scout[15189] ERROR browser.py L96: 'root'
Traceback (most recent call last):
  File ".../ScoutSuite/ScoutSuite/providers/base/configs/browser.py", line 96, in get_value_at
    target_obj = target_obj[p]
KeyError: 'root'
YYYY-MM-DD HH:MM:SS user-at-a-computer scout[15189] ERROR browser.py L96: 'host'
Traceback (most recent call last):
  File ".../ScoutSuite/ScoutSuite/providers/base/configs/browser.py", line 96, in get_value_at
    target_obj = target_obj[p]
KeyError: 'host'
```

**Comment by j4v** [comment]
my bad, it should have been `withKey`, not `notEmpty`. Please test again?
