### ISSUE TITLE
INFO Hitting API rate limiting, will retry in 

### ISSUE THREAD

**Issue by lvarallo** [nccgroup/ScoutSuite#564]
Will be great to fix/document how to circumnavigate those for big accounts

2019-11-05 10:15:05 lvarallo-ws1 scout[145308] INFO Hitting API rate limiting, will retry in 15s
2019-11-05 10:15:06 lvarallo-ws1 scout[145308] INFO Hitting API rate limiting, will retry in 15s
2019-11-05 10:15:06 lvarallo-ws1 scout[145308] INFO Hitting API rate limiting, will retry in 15s
2019-11-05 10:17:59 lvarallo-ws1 asyncio[145308] ERROR Task exception was never retrieved
future: <Task finished coro=<IAMFacade._get_and_set_inline_policies() done, defined at C:\GitHub_backup\Appoggio\ScoutSuite\ScoutSuite\providers\aws\facade\iam.py:187> exception=TypeError('string indices must be integers')>
Traceback (most recent call last):
  File "C:\GitHub_backup\Appoggio\ScoutSuite\ScoutSuite\providers\aws\facade\iam.py", line 220, in _get_and_set_inline_policies
    policy_document)
  File "C:\GitHub_backup\Appoggio\ScoutSuite\ScoutSuite\providers\aws\facade\iam.py", line 228, in _normalize_statements
    if type(statement[action_string]) != list:
TypeError: string indices must be integers
2019-11-05 10:17:59 lvarallo-ws1 scout[145308] ERROR services.py L58: Could not fetch iam configuration: 'PolicyDocument'
2019-11-05 10:18:34 lvarallo-ws1 scout[145308] INFO Hitting API rate limiting, will retry in 15s
2019-11-05 10:18:36 lvarallo-ws1 scout[145308] INFO Hitting API rate limiting, will retry in 15s

**Comment by j4v** [comment]
As noted in the output, if API limiting is hit then Scout will backoff incrementally in order to complete the execution.

In case this has an adverse effect (e.g. on other ops happening within the account), you can leverage the `--max-rate` option to limit how many API requests are made per second.

Not sure there's anything to "fix" at this point, AWS rate limiting is just not very well implemented / easy to handle.

**Comment by klauern** [comment]
One thing that could be improved would be to output where the rate limiting is occurring.  You could have rate limiting be in play for any of the services that it's making requests out to, such as KMS, SES, EMR, EC2, what-have-you, and the log will tell you nothing actionable.

**Comment by j4v** [comment]
@klauern this is mostly because the management of the rate limiting is provider-agnostic, and not mixed with AWS-specific code. 

As all API calls are queued through an asyncio event loop, there's currently no way to target specific AWS services.

Closing this for now, nothing concrete to work on.
