### ISSUE TITLE
Strange AWS security group breaks EC2 scans

### ISSUE THREAD

**Issue by par-texx** [nccgroup/ScoutSuite#593]
Had a strange issue.
Somehow CDK created a security group with the following settings:
Type: Custom ICMP
Protocol: 252
Port Range: 86
Destination: Custom 255.255.255.255/32
![BadSG](https://user-images.githubusercontent.com/8822931/71115396-0ec43100-218f-11ea-9a51-ac3648063db0.png)

Obviously that's not a correct AWS security group, but it somehow got created.

During a scan, this is the error message we get:

```
2019-12-18 09:57:08 DESKTOP- scout[16880] INFO Hitting API rate limiting, will retry in 30s 
2019-12-18 09:57:14 DESKTOP- asyncio[16880] ERROR Task exception was never retrieved
future: <Task finished coro=<SecurityGroups.fetch_all() done, defined at c:\users\******\python\scoutsuite\venv\lib\site-packages\ScoutSuite\providers\aws\resources\ec2\securitygroups.py:15> exception=KeyError('252')>
Traceback (most recent call last):
  File "c:\users\******\python\scoutsuite\venv\lib\site-packages\ScoutSuite\providers\aws\resources\ec2\securitygroups.py", line 18, in fetch_all
    name, resource = self._parse_security_group(raw_security_groups)
  File "c:\users\******\python\scoutsuite\venv\lib\site-packages\ScoutSuite\providers\aws\resources\ec2\securitygroups.py", line 38, in _parse_security_group
    raw_security_group['IpPermissionsEgress'])
  File "c:\users\******\python\scoutsuite\venv\lib\site-packages\ScoutSuite\providers\aws\resources\ec2\securitygroups.py", line 60, in _parse_security_group_rules
    rule['FromPort'])]
KeyError: '252'
2019-12-18 09:57:39 DESKTOP- scout[16880] ERROR browser.py L96: 'sg-1**************' 
2019-12-18 09:57:39 DESKTOP- scout[16880] ERROR browser.py L96: 'name' 
2019-12-18 09:57:39 DESKTOP- scout[16880] ERROR browser.py L96: 'sg-2**************' 
2019-12-18 09:57:39 DESKTOP- scout[16880] ERROR browser.py L96: 'name' 
2019-12-18 09:57:39 DESKTOP- scout[16880] ERROR browser.py L96: 'sg-2**************' 
2019-12-18 09:57:39 DESKTOP- scout[16880] ERROR browser.py L96: 'name' 
2019-12-18 09:57:39 DESKTOP- scout[16880] ERROR browser.py L96: 'sg-2**************' 
2019-12-18 09:57:39 DESKTOP- scout[16880] ERROR browser.py L96: 'name' 
2019-12-18 09:57:39 DESKTOP- scout[16880] ERROR browser.py L96: 'sg-3**************' 
2019-12-18 09:57:39 DESKTOP- scout[16880] ERROR browser.py L96: 'name' 
2019-12-18 09:57:39 DESKTOP- scout[16880] ERROR browser.py L96: 'sg-2**************' 
2019-12-18 09:57:39 DESKTOP- scout[16880] ERROR browser.py L96: 'name' Traceback (most recent call last): File "C:\Program Files\Python37\Lib\runpy.py", line 193, in _run_module_as_main "__main__", mod_spec) Traceback (most recent call last):
  File "C:\Program Files\Python37\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\******\Python\scoutsuite\venv\Scripts\scout.exe\__main__.py", line 7, in <module>
  File "c:\users\******\python\scoutsuite\venv\lib\site-packages\ScoutSuite\__main__.py", line 70, in run_from_cli
    programmatic_execution=False)
  File "c:\users\******\python\scoutsuite\venv\lib\site-packages\ScoutSuite\__main__.py", line 119, in run
    result = loop.run_until_complete(_run(**locals()))  # pass through all the parameters
  File "C:\Program Files\Python37\Lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "c:\users\******\python\scoutsuite\venv\lib\site-packages\ScoutSuite\__main__.py", line 251, in _run
    ip_ranges, ip_ranges_name_key)
  File "c:\users\******\python\scoutsuite\venv\lib\site-packages\ScoutSuite\providers\aws\provider.py", line 85, in preprocessing
    self._add_security_group_data_to_elbv2()
  File "c:\users\******\python\scoutsuite\venv\lib\site-packages\ScoutSuite\providers\aws\provider.py", line 151, in _add_security_group_data_to_elbv2
    elbv2_config['regions'][region]['vpcs'][vpc]['lbs'][lb], i, 'ingress')
  File "c:\users\******\python\scoutsuite\venv\lib\site-packages\ScoutSuite\providers\aws\provider.py", line 128, in check_security_group_rules
    for protocol in lb['security_groups'][index]['rules'][traffic_type]['protocols']:
KeyError: 'rules'`

```

**Comment by j4v** [comment]
Thanks, will look into it.

**Comment by atomray** [comment]
FYI - it looks like AWS's CDK is going to be generating this egress rule by design - it's meant to be bogus, a general purpose way to prevent the default 0.0.0.0/0 rule from being created.

**Comment by j4v** [comment]
@atomray is this for any SG created with CDK?

**Comment by atomray** [comment]
For any group where you don't want the default all traffic egress - here's a link to the code
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ec2/lib/security-group.ts#L496

So I think you're going to start seeing this a lot in AWS VPCs going forward

**Comment by j4v** [comment]
@atomray I've pushed a fix to https://github.com/nccgroup/ScoutSuite/tree/bugfix/593, could you please test? It's resolving the issue on my end.
