### ISSUE TITLE
Task exception was never retrieved Error

### ISSUE THREAD

**Issue by ckennard** [nccgroup/ScoutSuite#628]
Here is what I get when I attempt to run an Azure CLI report.

> scout azure --cli
2020-01-28 17:26:27 kali scout[23479] INFO Launching Scout
2020-01-28 17:26:27 kali scout[23479] INFO Authenticating to cloud provider
2020-01-28 17:26:27 kali scout[23479] INFO Gathering data from APIs
2020-01-28 17:26:27 kali scout[23479] INFO Fetching resources for the Security Center service
2020-01-28 17:26:27 kali scout[23479] INFO Fetching resources for the SQL Database service
2020-01-28 17:26:27 kali scout[23479] INFO Fetching resources for the Storage Accounts service
2020-01-28 17:26:27 kali scout[23479] INFO Fetching resources for the Key Vault service
2020-01-28 17:26:27 kali scout[23479] INFO Fetching resources for the Graph RBAC service
2020-01-28 17:26:27 kali scout[23479] INFO Fetching resources for the Network service
2020-01-28 17:26:27 kali scout[23479] INFO Fetching resources for the Virtual Machines service
Task exception was never retrieved
future: <Task finished coro=<NetworkInterfaces.fetch_all() done, defined at /usr/local/lib/python3.7/dist-packages/ScoutSuite/providers/azure/resources/network/network_interfaces.py:6> exception=AttributeError("'NoneType' object has no attribute 'id'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ScoutSuite/providers/azure/resources/network/network_interfaces.py", line 8, in fetch_all
    id, network_interface = self._parse_network_interface(raw_network_interface)
  File "/usr/local/lib/python3.7/dist-packages/ScoutSuite/providers/azure/resources/network/network_interfaces.py", line 31, in _parse_network_interface
    network_interface_dict['network_security_group'] = get_non_provider_id(raw_network_interface.network_security_group.id)
AttributeError: 'NoneType' object has no attribute 'id'

I still successfully get a report. Running in Kali fully updated.

**Comment by j4v** [comment]
Thanks, it must not be handling a specific case.

**Comment by j4v** [comment]
Looks like you're running an outdated version of Scout Suite. The latest code already handles this case (https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/azure/resources/network/network_interfaces.py#L37).
