### ISSUE TITLE
Bug in ami.py

### ISSUE THREAD

**Issue by rracterr** [nccgroup/ScoutSuite#635]
```
 asyncio[6175] ERROR Task exception was never retrieved
future: <Task finished coro=<AmazonMachineImages.fetch_all() done, defined at /home/ec2-user/ScoutSuite/ScoutSuite/providers/aws/resources/ec2/ami.py:10> exception=KeyError('Name')>
Traceback (most recent call last):
  File "/home/ec2-user/ScoutSuite/ScoutSuite/providers/aws/resources/ec2/ami.py", line 13, in fetch_all
    name, resource = self._parse_image(raw_image)
  File "/home/ec2-user/ScoutSuite/ScoutSuite/providers/aws/resources/ec2/ami.py", line 18, in _parse_image
    raw_image['name'] = raw_image['Name']
KeyError: 'Name'
```

**Comment by j4v** [comment]
Looks like the querying is unsafe. I'd think all AMIs would have a value for that field but it's an easy fix.

**Comment by j4v** [comment]
Closing, this should now be fixed in `develop`.
