### ISSUE TITLE
GCP: Data parsing errors for CloudStorage Buckets and GCE Disks

### ISSUE THREAD

**Issue by rtomlinson-latacora** [nccgroup/ScoutSuite#673]
Errors:

```
2020-03-16` 17:43:42 renzo-latacora-work asyncio[17820] ERROR Task exception was never retrieved
future: <Task finished coro=<Instances.fetch_all() done, defined at /home/user/Documents/scoutsuite/LatacoraScoutSuite/ScoutSuite/ScoutSuite/providers/gcp/resources/gce/instances.py:17> exception=KeyError('source')>
Traceback (most recent call last):
  File "/home/user/Documents/scoutsuite/LatacoraScoutSuite/ScoutSuite/ScoutSuite/providers/gcp/resources/gce/instances.py", line 22, in fetch_all
    self[instance_id]['disks'].fetch_all()
  File "/home/user/Documents/scoutsuite/LatacoraScoutSuite/ScoutSuite/ScoutSuite/providers/gcp/resources/gce/instance_disks.py", line 12, in fetch_all
    disk_id, disk = self._parse_disk(raw_disk)
  File "/home/user/Documents/scoutsuite/LatacoraScoutSuite/ScoutSuite/ScoutSuite/providers/gcp/resources/gce/disks.py", line 11, in _parse_disk
    disk_dict['source_url'] = raw_disk['source']
KeyError: 'source'
```

```
020-03-16 17:03:11 renzo-latacora-work asyncio[17820] ERROR Task exception was never retrieved
future: <Task finished coro=<Buckets.fetch_all() done, defined at /home/user/Documents/scoutsuite/LatacoraScoutSuite/ScoutSuite/ScoutSuite/providers/gcp/resources/cloudstorage/buckets.py:11> exception=KeyError('bucketPolicyOnly')>
Traceback (most recent call last):
  File "/home/user/Documents/scoutsuite/LatacoraScoutSuite/ScoutSuite/ScoutSuite/providers/gcp/resources/cloudstorage/buckets.py", line 14, in fetch_all
    bucket_id, bucket = self._parse_bucket(raw_bucket)
  File "/home/user/Documents/scoutsuite/LatacoraScoutSuite/ScoutSuite/ScoutSuite/providers/gcp/resources/cloudstorage/buckets.py", line 27, in _parse_bucket
    bucket_dict['uniform_bucket_level_access'] = raw_bucket.iam_configuration['bucketPolicyOnly']['enabled']
KeyError: 'bucketPolicyOnly'
```

**Additional context**

Will push up some basic changes. Proposed solution is to provide defaults if values are not found in the raw resource responses.

The `bucketPolicyOnly` bug is odd because I've found that sometimes `bucketPolicyOnly` is the only key in the bucket config dictionary and other times `uniformBucketLevelAccess` is the only key. I'm not sure what causes that or if those two values will ever be different since I believe they are effectively describing the same thing.

**Comment by rtomlinson-latacora** [comment]
https://github.com/nccgroup/ScoutSuite/pull/674

**Comment by rtomlinson-latacora** [comment]
Closing pull request due to some local changes that we saved to master

**Comment by rtomlinson-latacora** [comment]
https://github.com/nccgroup/ScoutSuite/pull/675

**Comment by j4v** [comment]
@rtomlinson-latacora reviewed https://github.com/nccgroup/ScoutSuite/pull/675 & made some small changes. Could you please test and confirm the issue is resolved in `develop`?

**Comment by rtomlinson-latacora** [comment]
Re-ran with changes from develop and appears to be working as expected. Closing this issue. Thanks.
