### ISSUE TITLE
Failure gettting kms:GetKeyRotationStatus from AWS KMS managed keys

### ISSUE THREAD

**Issue by FnTm** [nccgroup/ScoutSuite#697]
ScoutSuite 5.8.0 tries to do `kms:GetKeyRotationStatus` on AWS managed key. AWS doesn't grant access to this API call to anyone, including the account owner. 

ScoutSuite 5.7.0, without this functionality, still works as expected.

```
scout --provider aws --no-browser --regions us-east-1 --exceptions jobs/scout_report/exceptions-aws-default.json
2020-04-02 11:44:04 <redactedHost> scout[56607] INFO Launching Scout
2020-04-02 11:44:04 <redactedHost> scout[56607] INFO Authenticating to cloud provider
2020-04-02 11:44:07 <redactedHost> scout[56607] INFO Gathering data from APIs
2020-04-02 11:44:07 <redactedHost> scout[56607] INFO Fetching resources for the ACM service
2020-04-02 11:44:07 <redactedHost> scout[56607] INFO Fetching resources for the Lambda service
2020-04-02 11:44:08 <redactedHost> scout[56607] INFO Fetching resources for the CloudFormation service
2020-04-02 11:44:09 <redactedHost> scout[56607] INFO Fetching resources for the CloudTrail service
2020-04-02 11:44:09 <redactedHost> scout[56607] INFO Fetching resources for the CloudWatch service
2020-04-02 11:44:10 <redactedHost> scout[56607] INFO Fetching resources for the Config service
2020-04-02 11:44:10 <redactedHost> scout[56607] INFO Fetching resources for the Direct Connect service
2020-04-02 11:44:11 <redactedHost> scout[56607] INFO Fetching resources for the EC2 service
2020-04-02 11:44:11 <redactedHost> scout[56607] INFO Fetching resources for the EFS service
2020-04-02 11:44:12 <redactedHost> scout[56607] INFO Fetching resources for the ElastiCache service
2020-04-02 11:44:12 <redactedHost> scout[56607] INFO Fetching resources for the ELB service
2020-04-02 11:44:13 <redactedHost> scout[56607] INFO Fetching resources for the ELBv2 service
2020-04-02 11:44:13 <redactedHost> scout[56607] INFO Fetching resources for the EMR service
2020-04-02 11:44:14 <redactedHost> scout[56607] INFO Fetching resources for the IAM service
2020-04-02 11:44:14 <redactedHost> scout[56607] INFO Fetching resources for the KMS service
2020-04-02 11:44:14 <redactedHost> scout[56607] INFO Fetching resources for the RDS service
2020-04-02 11:44:15 <redactedHost> scout[56607] INFO Fetching resources for the RedShift service
2020-04-02 11:44:16 <redactedHost> scout[56607] INFO Fetching resources for the Route53 service
2020-04-02 11:44:16 <redactedHost> scout[56607] INFO Fetching resources for the S3 service
2020-04-02 11:44:17 <redactedHost> scout[56607] INFO Fetching resources for the SES service
2020-04-02 11:44:17 <redactedHost> scout[56607] INFO Fetching resources for the SNS service
2020-04-02 11:44:18 <redactedHost> scout[56607] INFO Fetching resources for the SQS service
2020-04-02 11:44:18 <redactedHost> scout[56607] INFO Fetching resources for the VPC service
2020-04-02 11:44:19 <redactedHost> scout[56607] INFO Fetching resources for the Secrets Manager service
2020-04-02 11:44:48 <redactedHost> scout[56607] ERROR kms.py L41: Failed to get KMS key rotation: An error occurred (AccessDeniedException) when calling the GetKeyRotationStatus operation: User: arn:aws:sts::<redactedAccountID>:assumed-role/<redactedRoleName>/<redactedRoleId> is not authorized to perform: kms:GetKeyRotationStatus on resource: arn:aws:kms:us-east-1:<redactedAccountID>:key/<redactedKeyId>
2020-04-02 11:44:57 <redactedHost> scout[56607] INFO Running rule engine
2020-04-02 11:45:09 <redactedHost> scout[56607] INFO Applying display filters
2020-04-02 11:45:09 <redactedHost> scout[56607] INFO Applying exceptions
2020-04-02 11:45:09 <redactedHost> scout[56607] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_results_aws-<redactedAccountID>.js
2020-04-02 11:45:10 <redactedHost> scout[56607] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_exceptions_aws-<redactedAccountID>.js
2020-04-02 11:45:10 <redactedHost> scout[56607] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_errors_aws-<redactedAccountID>.json
2020-04-02 11:45:10 <redactedHost> scout[56607] INFO Creating scoutsuite-report/aws-<redactedAccountID>.html
```

This is the only  relevant change from the output above, when run with the `--debug` option

```
Traceback (most recent call last):
  File "<redactedPath>env/lib/python3.7/site-packages/ScoutSuite/providers/aws/facade/kms.py", line 41, in _get_and_set_key_rotation_status
    lambda: client.get_key_rotation_status(KeyId=key['KeyId']))
  File "<redactedPath>env/lib/python3.7/site-packages/ScoutSuite/providers/utils.py", line 24, in run_concurrently
    return await run_function_concurrently(function)
  File "<redactedPath>/.pyenv/versions/3.7.2/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "<redactedPath>env/lib/python3.7/site-packages/ScoutSuite/providers/aws/facade/kms.py", line 41, in <lambda>
    lambda: client.get_key_rotation_status(KeyId=key['KeyId']))
  File "<redactedPath>env/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "<redactedPath>env/lib/python3.7/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the GetKeyRotationStatus operation: User: arn:aws:sts::<redacted>:assumed-role/<redacted>/<redacted> is not authorized to perform: kms:GetKeyRotationStatus on resource: arn:aws:kms:us-east-1:<redacted>:key/<redacted>
```

**To Reproduce**
- Use ScoutSuite 5.8.0 on an account that uses AWS managed KMS key

**Additional context**

**Comment by j4v** [comment]
This has now been solved in the `develop` branch. We're only pulling rotation for customer managed CMKs, as otherwise it is enabled by default and not changeable.
