### ISSUE TITLE
ec2-instance-with-open-nacls bug

### ISSUE THREAD

**Issue by ramimac** [nccgroup/ScoutSuite#790]
**Describe the bug**

When the Scout AWS is run with `--services ec2`, errors are observed with ec2-instance-with-open-nacls.

**To Reproduce**

`python3 scout.py aws --services ec2 --access-key-id {KEY} --secret-access-key {SECRET} --debug`

Run against sadcloud (with only var=all_ec2_findings)

**Additional context**

These errors don't occur if services aren't specified.

**Errors**

When run on `develop`:

> 2020-06-12 13:57:22 rami scout[584272] INFO Launching Scout
2020-06-12 13:57:22 rami scout[584272] INFO Authenticating to cloud provider
2020-06-12 13:57:24 rami scout[584272] INFO Gathering data from APIs
2020-06-12 13:57:24 rami scout[584272] DEBUG Skipping the Credentials service
...
2020-06-12 13:57:24 rami scout[584272] INFO Fetching resources for the EC2 service
2020-06-12 13:57:31 rami scout[584272] INFO Running rule engine
2020-06-12 13:57:31 rami scout[584272] DEBUG Loading ruleset /home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/providers/aws/rules/rulesets/default.json
2020-06-12 13:57:31 rami scout[584272] DEBUG Processing EC2 rule "Publicly Accessible AMI" (ec2-ami-public.json)
...
2020-06-12 13:57:32 rami scout[584272] INFO Applying display filters
2020-06-12 13:57:32 rami scout[584272] DEBUG Loading ruleset /home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/providers/aws/rules/rulesets/filters.json
2020-06-12 13:57:32 rami scout[584272] DEBUG Processing EC2 rule "Public instance with open NACLs" (ec2-instance-with-open-nacls.json)
2020-06-12 13:57:32 rami scout[584272] ERROR browser.py L107: Unable to get "regions" from target object {'findings': {}, 'filters': {}}: 'regions'
Traceback (most recent call last):
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/providers/base/configs/browser.py", line 107, in get_value_at
    target_obj = target_obj[p]
KeyError: 'regions'
2020-06-12 13:57:32 rami scout[584272] ERROR processingengine.py L51: Failed to process rule defined in ec2-instance-with-open-nacls.json: replace() argument 2 must be str, not None
Traceback (most recent call last):
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/processingengine.py", line 51, in run
    cloud_provider.services[service][self.ruleset.rule_type][rule.key]['items'] = recurse(
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/utils.py", line 59, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/utils.py", line 59, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/utils.py", line 66, in recurse
    results = results + recurse(all_info, split_current_info, split_target_path, split_current_path,
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/utils.py", line 59, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/utils.py", line 66, in recurse
    results = results + recurse(all_info, split_current_info, split_target_path, split_current_path,
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/utils.py", line 59, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/utils.py", line 66, in recurse
    results = results + recurse(all_info, split_current_info, split_target_path, split_current_path,
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/utils.py", line 59, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/utils.py", line 66, in recurse
    results = results + recurse(all_info, split_current_info, split_target_path, split_current_path,
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/utils.py", line 39, in recurse
    if pass_conditions(all_info, current_path, copy.deepcopy(config.conditions)):
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/conditions.py", line 38, in pass_conditions
    path_to_value = fix_path_string(all_info, current_path, path_to_value)
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/conditions.py", line 282, in fix_path_string
    path_to_value = path_to_value.replace('_GET_VALUE_AT_(%s)' % tmp, dv)
TypeError: replace() argument 2 must be str, not None
2020-06-12 13:57:32 rami scout[584272] DEBUG Processing EC2 rule "Security group whitelists public CIDRs" (ec2-security-group-with-public-cidr-grant.json)
2020-06-12 13:57:32 rami scout[584272] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_results_aws-395822310781.js

When run on `master`:

> 2020-06-12 14:01:15 rami scout[584337] DEBUG Loading ruleset /home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/providers/aws/rules/rulesets/filters.json
2020-06-12 14:01:15 rami scout[584337] DEBUG Processing EC2 rule[ec2-instance-with-open-nacls.json]: "Public instance with open NACLs"
2020-06-12 14:01:15 rami scout[584337] ERROR browser.py L96: 'regions'
Traceback (most recent call last):
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/providers/base/configs/browser.py", line 96, in get_value_at
    target_obj = target_obj[p]
KeyError: 'regions'
2020-06-12 14:01:15 rami scout[584337] ERROR browser.py L96: 'us-east-1'
Traceback (most recent call last):
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/providers/base/configs/browser.py", line 96, in get_value_at
    target_obj = target_obj[p]
KeyError: 'us-east-1'
2020-06-12 14:01:15 rami scout[584337] ERROR browser.py L96: 'vpcs'
Traceback (most recent call last):
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/providers/base/configs/browser.py", line 96, in get_value_at
    target_obj = target_obj[p]
KeyError: 'vpcs'
2020-06-12 14:01:15 rami scout[584337] ERROR browser.py L96: 'vpc-09e771ffad68ba7a0'
Traceback (most recent call last):
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/providers/base/configs/browser.py", line 96, in get_value_at
    target_obj = target_obj[p]
KeyError: 'vpc-09e771ffad68ba7a0'
2020-06-12 14:01:15 rami scout[584337] ERROR browser.py L96: 'subnets'
Traceback (most recent call last):
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/providers/base/configs/browser.py", line 96, in get_value_at
    target_obj = target_obj[p]
KeyError: 'subnets'
2020-06-12 14:01:15 rami scout[584337] ERROR browser.py L96: 'subnet-0376bbbc3fe089ba1'
Traceback (most recent call last):
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/providers/base/configs/browser.py", line 96, in get_value_at
    target_obj = target_obj[p]
KeyError: 'subnet-0376bbbc3fe089ba1'
2020-06-12 14:01:15 rami scout[584337] ERROR browser.py L96: 'network_acl'
Traceback (most recent call last):
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/providers/base/configs/browser.py", line 96, in get_value_at
    target_obj = target_obj[p]
KeyError: 'network_acl'
2020-06-12 14:01:15 rami scout[584337] ERROR processingengine.py L51: Failed to process rule defined in ec2-instance-with-open-nacls.json: replace() argument 2 must be str, not dict
Traceback (most recent call last):
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/processingengine.py", line 51, in run
    cloud_provider.services[service][self.ruleset.rule_type][rule.key]['items'] = recurse(
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/utils.py", line 54, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/utils.py", line 54, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/utils.py", line 61, in recurse
    results = results + recurse(all_info, split_current_info, split_target_path, split_current_path,
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/utils.py", line 54, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/utils.py", line 61, in recurse
    results = results + recurse(all_info, split_current_info, split_target_path, split_current_path,
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/utils.py", line 54, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/utils.py", line 61, in recurse
    results = results + recurse(all_info, split_current_info, split_target_path, split_current_path,
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/utils.py", line 54, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/utils.py", line 61, in recurse
    results = results + recurse(all_info, split_current_info, split_target_path, split_current_path,
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/utils.py", line 39, in recurse
    if pass_conditions(all_info, current_path, copy.deepcopy(config.conditions)):
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/conditions.py", line 38, in pass_conditions
    path_to_value = fix_path_string(all_info, current_path, path_to_value)
  File "/home/rami/Documents/Desktop/Development/scoutsuite-develop/ScoutSuite/ScoutSuite/core/conditions.py", line 274, in fix_path_string
    path_to_value = path_to_value.replace('_GET_VALUE_AT_(%s)' % tmp, dv)
TypeError: replace() argument 2 must be str, not dict
2020-06-12 14:01:15 rami scout[584337] DEBUG Processing EC2 rule[ec2-security-group-with-public-cidr-grant.json]: "Security group whitelists public CIDRs"

**Comment by j4v** [comment]
This issue is due to the post-processing done by Scout. During this phase of a job, cross-service checks are performed.

It's in large part legacy code, which mostly works but is quite poorly written / documented. In "most" cases we've added checks to ensure we aren't trying to evaluate missing data, but it's not perfect.

**Comment by j4v** [comment]
Closing, this is fixed in `develop`.
