### ISSUE TITLE
Error in aad.py Azure module 

### ISSUE THREAD

**Issue by dataatsky** [nccgroup/ScoutSuite#821]
**Describe the bug**

Scout version 5.9

When running scout against a specific Azure subscription we get the following error as seen below. Do let us know if you need more information.

- The **exact** CLI parameters used to run Scout Suite.
./scout.py azure --tenant xxx-xxx-xxx-xxx --subscriptions xxx-xxx-xxx-xxx-xxxx --user-account-browser

- Any specific configuration within the cloud account which might have lead to the issue.
Nothing specific

**Additional context**

Output:

```
2020-07-24 03:56:32 ubuntu scout[3614] ERROR aad.py L30: Failed to retrieve user xxx-xxx-xxx-xxx-xxx: Resource 'xxx-xxxx-xxx-xxx-xxx-xx' does not exist or one of its queried reference-property objects are not present.
Traceback (most recent call last):
  File "/home/victor/Documents/scout_59/ScoutSuite/ScoutSuite/providers/azure/facade/aad.py", line 30, in get_user
    return await run_concurrently(lambda: self.get_client().users.get(user_id))
  File "/home/victor/Documents/scout_59/ScoutSuite/ScoutSuite/providers/utils.py", line 24, in run_concurrently
    return await run_function_concurrently(function)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/victor/Documents/scout_59/ScoutSuite/ScoutSuite/providers/azure/facade/aad.py", line 30, in <lambda>
    return await run_concurrently(lambda: self.get_client().users.get(user_id))
  File "/home/victor/.local/lib/python3.6/site-packages/azure/graphrbac/operations/users_operations.py", line 218, in get
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error_py3.GraphErrorException: Resource 'xxx-xxx-xxx-xxx-xxx' does not exist or one of its queried reference-property objects are not present.
Traceback (most recent call last):
  File "./scout.py", line 8, in <module>
    sys.exit(run_from_cli())
  File "/home/victor/Documents/scout_59/ScoutSuite/ScoutSuite/__main__.py", line 77, in run_from_cli
    programmatic_execution=False)
  File "/home/victor/Documents/scout_59/ScoutSuite/ScoutSuite/__main__.py", line 131, in run
    result = loop.run_until_complete(_run(**locals()))  # pass through all the parameters
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/victor/Documents/scout_59/ScoutSuite/ScoutSuite/__main__.py", line 258, in _run
    await cloud_provider.fetch(regions=regions, excluded_regions=excluded_regions)
  File "/home/victor/Documents/scout_59/ScoutSuite/ScoutSuite/providers/base/provider.py", line 81, in fetch
    await self.services.fetch(self.service_list, regions, excluded_regions)
  File "/home/victor/Documents/scout_59/ScoutSuite/ScoutSuite/providers/azure/services.py", line 78, in fetch
    await self.aad.fetch_additional_users(user_list)
  File "/home/victor/Documents/scout_59/ScoutSuite/ScoutSuite/providers/azure/resources/aad/base.py", line 26, in fetch_additional_users
    await additional_users.fetch_additional_users(user_list)
  File "/home/victor/Documents/scout_59/ScoutSuite/ScoutSuite/providers/azure/resources/aad/users.py", line 17, in fetch_additional_users
    id, user = await self._parse_user(raw_user)
  File "/home/victor/Documents/scout_59/ScoutSuite/ScoutSuite/providers/azure/resources/aad/users.py", line 22, in _parse_user
    user_dict['id'] = raw_user.object_id
AttributeError: 'list' object has no attribute 'object_id'

```

**Comment by j4v** [comment]
This is something we've been tracking for the past few days, but we've only seen it for service principals, and it was related to a lack of privileges. Is it possible the principal you're running Scout with doesn't have sufficient privileges?

**Comment by dataatsky** [comment]
Yes it could be possible, I will check the permissions and let you know the result.

**Comment by dataatsky** [comment]
Hello,

Permissions are set to reader for the whole subscription. We have checked this in version 5.8.1 and it does not happen.

**Comment by j4v** [comment]
Closing, this is fixed in `master`.

**Comment by ammarsajid** [comment]
(venv) ammar-sajid@scout-suite:~$ scout --version
Scout Suite 5.9.1
The managed identity service principal has the following roles
- Directory.Read.All Graph API permissions
- Reader + Website contributor role on the subscription level

When running scout using msi authentication then we get the same error as shown below.

Command:
(venv) ammar-sajid@scout-suite:~$ scout azure --msi --subscriptions "xxxxxxx-xxxx-xxxxxxxxx-xxxxxxx"

Output:
2020-08-05 14:21:07 scout-suite scout[5728] INFO Launching Scout
2020-08-05 14:21:07 scout-suite scout[5728] INFO Authenticating to cloud provider
2020-08-05 14:21:07 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:07 scout-suite scout[5728] INFO Running against subscription xxxxxxx-xxxx-xxxxxxxxx-xxxxxxx
**2020-08-05 14:21:07 scout-suite scout[5728] ERROR provider.py L59: Unable to define report name: 'tenant_id'**
2020-08-05 14:21:07 scout-suite scout[5728] INFO Gathering data from APIs
2020-08-05 14:21:07 scout-suite scout[5728] INFO Fetching resources for the Azure Active Directory service
2020-08-05 14:21:07 scout-suite scout[5728] INFO Fetching resources for the Azure RBAC service
2020-08-05 14:21:07 scout-suite scout[5728] INFO Fetching resources for the Security Center service
2020-08-05 14:21:07 scout-suite scout[5728] INFO Fetching resources for the SQL Database service
2020-08-05 14:21:07 scout-suite scout[5728] INFO Fetching resources for the Storage Accounts service
2020-08-05 14:21:07 scout-suite scout[5728] INFO Fetching resources for the Key Vault service
2020-08-05 14:21:07 scout-suite scout[5728] INFO Fetching resources for the Network service
2020-08-05 14:21:07 scout-suite scout[5728] INFO Fetching resources for the Virtual Machines service
2020-08-05 14:21:07 scout-suite scout[5728] INFO Fetching resources for the App Services service
2020-08-05 14:21:07 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:07 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:07 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:07 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:07 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:07 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
**2020-08-05 14:21:07 scout-suite scout[5728] ERROR aad.py L23: Failed to retrieve users: 'tenant_id'
2020-08-05 14:21:07 scout-suite scout[5728] ERROR aad.py L37: Failed to retrieve groups: 'tenant_id'
2020-08-05 14:21:07 scout-suite scout[5728] ERROR aad.py L54: Failed to retrieve service principals: 'tenant_id'
2020-08-05 14:21:07 scout-suite scout[5728] ERROR aad.py L61: Failed to retrieve applications: 'tenant_id'**
2020-08-05 14:21:07 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:07 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:07 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:07 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:07 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:08 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:08 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:08 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:08 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:08 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:08 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:08 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:08 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:08 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:08 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:08 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:08 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:08 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:08 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:08 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:08 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:08 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:08 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:08 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:08 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:08 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:08 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:09 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:09 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:09 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:09 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:09 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:09 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:09 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:09 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:09 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:09 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:09 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:09 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:09 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:09 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:09 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:09 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:09 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:09 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:09 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:10 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:11 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:12 scout-suite msrestazure.azure_active_directory[5728] INFO MSI: token is found in cache.
2020-08-05 14:21:13 scout-suite scout[5728] ERROR aad.py L30: Failed to retrieve user 2a5c1b25-daec-46ae-a3d8-ac21c3006113: 'tenant_id'
2020-08-05 14:21:13 scout-suite scout[5728] ERROR aad.py L30: Failed to retrieve user xxxxxxx-xxxx-xxxxxxxxx-xxxxxxx: 'tenant_id'
2020-08-05 14:21:13 scout-suite scout[5728] ERROR aad.py L30: Failed to retrieve user xxxxxxx-xxxx-xxxxxxxxx-xxxxxxx: 'tenant_id'
2020-08-05 14:21:13 scout-suite scout[5728] ERROR aad.py L30: Failed to retrieve user xxxxxxx-xxxx-xxxxxxxxx-xxxxxxx: 'tenant_id'
2020-08-05 14:21:13 scout-suite scout[5728] ERROR aad.py L30: Failed to retrieve user xxxxxxx-xxxx-xxxxxxxxx-xxxxxxx: 'tenant_id'
2020-08-05 14:21:13 scout-suite scout[5728] ERROR aad.py L30: Failed to retrieve user xxxxxxx-xxxx-xxxxxxxxx-xxxxxxx: 'tenant_id'
2020-08-05 14:21:13 scout-suite scout[5728] ERROR aad.py L30: Failed to retrieve user xxxxxxx-xxxx-xxxxxxxxx-xxxxxxx: 'tenant_id'
2020-08-05 14:21:13 scout-suite scout[5728] ERROR aad.py L30: Failed to retrieve user xxxxxxx-xxxx-xxxxxxxxx-xxxxxxx: 'tenant_id'
2020-08-05 14:21:13 scout-suite scout[5728] ERROR aad.py L30: Failed to retrieve user xxxxxxx-xxxx-xxxxxxxxx-xxxxxxx: 'tenant_id'
2020-08-05 14:21:13 scout-suite scout[5728] ERROR aad.py L30: Failed to retrieve user xxxxxxx-xxxx-xxxxxxxxx-xxxxxxx: 'tenant_id'
2020-08-05 14:21:13 scout-suite scout[5728] ERROR aad.py L30: Failed to retrieve user xxxxxxx-xxxx-xxxxxxxxx-xxxxxxx: 'tenant_id'
2020-08-05 14:21:13 scout-suite scout[5728] ERROR aad.py L30: Failed to retrieve user xxxxxxx-xxxx-xxxxxxxxx-xxxxxxx: 'tenant_id'
2020-08-05 14:21:13 scout-suite scout[5728] ERROR aad.py L30: Failed to retrieve user xxxxxxx-xxxx-xxxxxxxxx-xxxxxxx: 'tenant_id'
2020-08-05 14:21:13 scout-suite scout[5728] ERROR aad.py L30: Failed to retrieve user xxxxxxx-xxxx-xxxxxxxxx-xxxxxxx: 'tenant_id'
2020-08-05 14:21:13 scout-suite scout[5728] ERROR aad.py L30: Failed to retrieve user xxxxxxx-xxxx-xxxxxxxxx-xxxxxxx: 'tenant_id'
2020-08-05 14:21:13 scout-suite scout[5728] ERROR aad.py L30: Failed to retrieve user xxxxxxx-xxxx-xxxxxxxxx-xxxxxxx: 'tenant_id'
2020-08-05 14:21:13 scout-suite scout[5728] ERROR aad.py L30: Failed to retrieve user xxxxxxx-xxxx-xxxxxxxxx-xxxxxxx: 'tenant_id'
2020-08-05 14:21:13 scout-suite scout[5728] ERROR aad.py L30: Failed to retrieve user xxxxxxx-xxxx-xxxxxxxxx-xxxxxxx: 'tenant_id'
2020-08-05 14:21:13 scout-suite scout[5728] ERROR aad.py L30: Failed to retrieve user xxxxxxx-xxxx-xxxxxxxxx-xxxxxxx: 'tenant_id'
2020-08-05 14:21:16 scout-suite scout[5728] INFO Running pre-processing engine
2020-08-05 14:21:16 scout-suite scout[5728] INFO Running rule engine
2020-08-05 14:21:16 scout-suite scout[5728] INFO Applying display filters
2020-08-05 14:21:16 scout-suite scout[5728] INFO Running post-processing engine
2020-08-05 14:21:16 scout-suite scout[5728] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_results_azure.js
2020-08-05 14:21:17 scout-suite scout[5728] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_exceptions_azure.js
2020-08-05 14:21:17 scout-suite scout[5728] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_errors_azure.json
2020-08-05 14:21:17 scout-suite scout[5728] INFO Creating scoutsuite-report/azure.html
2020-08-05 14:21:17 scout-suite scout[5728] INFO Opening the HTML report




And if we provide --tenant parameter then it errors out like this
CLI Command:
(venv) ammar-sajid@scout-suite:~$ scout azure --msi --tenant "xxxxxxx-xxxx-xxxxxxxxx-xxxxxxx" --subscriptions "xxxxxxx-xxxx-xxxxxxxxx-xxxxxxx"


Output:
usage: scout [-h] [-v] {aws,gcp,azure,aliyun,oci} ...
scout: error: --tenant can only be set when using --user-account-browser or --service-principal authentication

- Please let me know if there is any additional information required

**Comment by j4v** [comment]
@ammarsajid I don't see what your bug has to do with this issue, I've opened it as https://github.com/nccgroup/ScoutSuite/issues/831.

**Comment by j4v** [comment]
> Closing, this is fixed in master.

Forgot to do this.
