### ISSUE TITLE
Amazon SQS Access policy with StringLike condition will fail ScoutSuite 

### ISSUE THREAD

**Issue by svanhool** [nccgroup/ScoutSuite#825]
When ScoutSuite scans the following SQS Access policy with StringLike condition it will produce errors:

```javascript
{
  "Version": "2008-10-17",
  "Id": "PublicationPolicy",
  "Statement": [
    {
      "Sid": "s3publication",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "sqs:SendMessage",
      "Resource": "arn:aws:sqs:eu-west-1:12345:sqs-stream",
      "Condition": {
        "StringLike": {
          "aws:SourceArn": "arn:aws:s3:::s3-bucket"
        }
      }
    }
  ]
}

```
**Console output:**
```console
DEBUG Processing SQS rule "SendMessage Authorized to All Principals" (sqs-queue-world-policy.json)
 browser.py L107: Unable to get "StringEquals" from target object {'StringLike': {'aws:SourceArn': 'arn:aws:s3:::s3-bucket'}}: 'StringEquals'
Traceback (most recent call last):
  File ".../python3.8/site-packages/ScoutSuite/providers/base/configs/browser.py", line 107, in get_value_at
    target_obj = target_obj[p]
KeyError: 'StringEquals'
ERROR conditions.py L45: Unable to process testcase 'withoutKey' on value 'None', interpreted as False: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "..../python3.8/site-packages/ScoutSuite/core/conditions.py", line 45, in pass_conditions
    res = pass_condition(target_obj, test_name, test_values)
  File "..../python3.8/site-packages/ScoutSuite/core/conditions.py", line 119, in pass_condition
    result = a not in b
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by j4v** [comment]
Thanks for raising, this is now fixed in `develop`.
