### ISSUE TITLE
"'Disk' object has no attribute 'unique_id'" when run against Azure

### ISSUE THREAD

**Issue by djcater** [nccgroup/ScoutSuite#886]
**Describe the bug**
When running ScoutSuite 5.10.0 against an Azure tenant, I get the following error (with `--debug` although the error also appears without it):
```
2020-10-06 22:17:22 ubuntu scout[50784] INFO Launching Scout
2020-10-06 22:17:22 ubuntu scout[50784] INFO Authenticating to cloud provider
2020-10-06 22:17:22 ubuntu scout[50784] INFO To authenticate to the Resource Manager API, use a web browser to access https://microsoft.com/devicelogin and enter the XXXXXX code.
2020-10-06 22:17:33 ubuntu scout[50784] INFO To authenticate to the Azure AD Graph API, use a web browser to access https://microsoft.com/devicelogin and enter the XXXXXX code.
2020-10-06 22:17:45 ubuntu scout[50784] INFO Running against 2 subscriptions
2020-10-06 22:17:45 ubuntu scout[50784] INFO Gathering data from APIs
2020-10-06 22:17:45 ubuntu scout[50784] DEBUG Skipping the Azure Active Directory service
2020-10-06 22:17:45 ubuntu scout[50784] DEBUG Skipping the Azure RBAC service
2020-10-06 22:17:45 ubuntu scout[50784] DEBUG Skipping the Security Center service
2020-10-06 22:17:45 ubuntu scout[50784] DEBUG Skipping the SQL Database service
2020-10-06 22:17:45 ubuntu scout[50784] DEBUG Skipping the Storage Accounts service
2020-10-06 22:17:45 ubuntu scout[50784] DEBUG Skipping the Key Vault service
2020-10-06 22:17:45 ubuntu scout[50784] DEBUG Skipping the Network service
2020-10-06 22:17:45 ubuntu scout[50784] DEBUG Skipping the App Services service
2020-10-06 22:17:45 ubuntu scout[50784] INFO Fetching resources for the Virtual Machines service
2020-10-06 22:17:48 ubuntu asyncio[50784] ERROR Task exception was never retrieved
future: <Task finished name='Task-10' coro=<Disks.fetch_all() done, defined at /home/xxx/ScoutSuite/ScoutSuite/providers/azure/resources/virtualmachines/disks.py:12> exception=AttributeError("'Disk' object has no attribute 'unique_id'")>
Traceback (most recent call last):
  File "/home/xxx/ScoutSuite/ScoutSuite/providers/azure/resources/virtualmachines/disks.py", line 14, in fetch_all
    id, disk = self._parse_disk(raw_disk)
  File "/home/xxx/ScoutSuite/ScoutSuite/providers/azure/resources/virtualmachines/disks.py", line 20, in _parse_disk
    disk_dict['unique_id'] = raw_disk.unique_id
AttributeError: 'Disk' object has no attribute 'unique_id'
2020-10-06 22:18:02 ubuntu scout[50784] INFO Running pre-processing engine
2020-10-06 22:18:02 ubuntu scout[50784] INFO Running rule engine
```
Exceptions JS file:
```
exceptions =
{}
```
**To Reproduce**
This comes from the `virtualmachines` service:
```
python scout.py azure --no-browser --report-dir results --timestamp --all-subscriptions --user-account-browser --tenant xxx-xxx-xxx --services virtualmachines --debug
```
When I look in the Azure portal I can't immediately see anything about the disks that would cause this error. They are a mix of "Standard SSD" and "Premium SSD", and they appear to have names, sizes, etc.

**Additional context**
This is running ScoutSuite 5.10.0, set up as follows:
```
$ virtualenv -p python3 venv
$ source venv/bin/activate
$ pip install -r requirements.txt
```
Python version is 3.8.2 on Ubuntu 20.04.

Hope that helps. Thanks.

**Comment by j4v** [comment]
Thanks, https://github.com/nccgroup/ScoutSuite/pull/883 should remediate this.

**Comment by j4v** [comment]
This should be resolved in https://github.com/nccgroup/ScoutSuite/tree/release/5.10.1 and will be released within a week.
