### ISSUE TITLE
'Snapshot' object has no attribute 'disk_size_bytes' in Azure

### ISSUE THREAD

**Issue by djcater** [nccgroup/ScoutSuite#903]
Like #886 but for snapshots instead of disks.

```
Traceback (most recent call last):
  File "/root/scoutsuite/lib/python3.8/site-packages/ScoutSuite/providers/azure/resources/virtualmachines/snapshots.py", line 14, in fetch_all
    id, snapshot = self._parse_snapshot(raw_snapshot)
  File "/root/scoutsuite/lib/python3.8/site-packages/ScoutSuite/providers/azure/resources/virtualmachines/snapshots.py", line 32, in _parse_snapshot
    snapshot_dict['disk_size_bytes'] = raw_snapshot.disk_size_bytes
AttributeError: 'Snapshot' object has no attribute 'disk_size_bytes'
```

**Comment by djcater** [comment]
Nevermind, I only patched `disks.py` and not also `snapshots.py`.
