### ISSUE TITLE
azure.mgmt.monitor error and container still 5.9.1

### ISSUE THREAD

**Issue by b1gdave** [nccgroup/ScoutSuite#907]
This is not a duplicate of [#861](https://github.com/nccgroup/ScoutSuite/issues/861), as I am using the 5.10.0 version.

When running scout 5.10.0 the error `Initialization failure: cannot import name 'MonitorManagementClient' from 'azure.mgmt.monitor'` occurs with Azure.

This is the output when running on my host:

$ ./scout.py -v
Scout Suite 5.10.0
$ ./scout.py azure --user-account-browser --tenant [id] --debug
2020-10-20 09:42:49 kali scout[101887] INFO Launching Scout
2020-10-20 09:42:49 kali scout[101887] INFO Authenticating to cloud provider
2020-10-20 09:42:50 kali scout[101887] INFO To authenticate to the Resource Manager API, use a web browser to access https://microsoft.com/devicelogin and enter the XXX code.
2020-10-20 09:43:07 kali scout[101887] INFO To authenticate to the Azure AD Graph API, use a web browser to access https://microsoft.com/devicelogin and enter the XXX code.
2020-10-20 09:43:18 kali scout[101887] ERROR __main__.py L212: Initialization failure: cannot import name 'MonitorManagementClient' from 'azure.mgmt.monitor' (/usr/lib/python3/dist-packages/azure/mgmt/monitor/__init__.py)
Traceback (most recent call last):
  File "/home/dlenehan/tools/ScoutSuite/ScoutSuite/__main__.py", line 212, in _run
    cloud_provider = get_provider(provider=provider,
  File "/home/dlenehan/tools/ScoutSuite/ScoutSuite/providers/__init__.py", line 36, in get_provider
    provider_object = get_provider_object(provider)
  File "/home/dlenehan/tools/ScoutSuite/ScoutSuite/providers/__init__.py", line 10, in get_provider_object
    provider_module = __import__(f'ScoutSuite.providers.{provider}.provider', fromlist=[provider_class])
  File "/home/dlenehan/tools/ScoutSuite/ScoutSuite/providers/azure/provider.py", line 6, in <module>
    from ScoutSuite.providers.azure.services import AzureServicesConfig
  File "/home/dlenehan/tools/ScoutSuite/ScoutSuite/providers/azure/services.py", line 2, in <module>
    from ScoutSuite.providers.azure.facade.base import AzureFacade
  File "/home/dlenehan/tools/ScoutSuite/ScoutSuite/providers/azure/facade/base.py", line 8, in <module>
    from ScoutSuite.providers.azure.facade.storageaccounts import StorageAccountsFacade
  File "/home/dlenehan/tools/ScoutSuite/ScoutSuite/providers/azure/facade/storageaccounts.py", line 3, in <module>
    from azure.mgmt.monitor import MonitorManagementClient
ImportError: cannot import name 'MonitorManagementClient' from 'azure.mgmt.monitor' (/usr/lib/python3/dist-packages/azure/mgmt/monitor/__init__.py)

**Additional context**
The version of ScoutSuite inside the docker image is still 5.9.1, so it's not possible to rule out environment problems that way.
![scoutsuite-bug](https://user-images.githubusercontent.com/35418920/96595258-649fc300-12e3-11eb-9883-9154c23b7693.png)

**Comment by j4v** [comment]
Two things:
- Did you update your dependencies?
- Could you try out the https://github.com/nccgroup/ScoutSuite/tree/release/5.10.1 branch, see if it resolves the issues?

**Comment by b1gdave** [comment]
I updated dependencies. The 5.10.1 branch seems to work though, so thanks for that pointer!

**Comment by j4v** [comment]
Great, should be released this week.
