### ISSUE TITLE
Newest google-cloud-monitoring lib is not compatible

### ISSUE THREAD

**Issue by kravvcu** [nccgroup/ScoutSuite#918]
**Describe the bug**

The current implementation uses the [project_path](https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/gcp/facade/stackdrivermonitoring.py#L25) class method. This method is available for 1.1.0 version of
the [google-cloud-monitoring](https://github.com/googleapis/python-monitoring/blob/release-v1.1.0/google/cloud/monitoring_v3/gapic/alert_policy_service_client.py#L111) lib. It's [not available](https://github.com/googleapis/python-monitoring/blob/master/google/cloud/monitoring_v3/services/alert_policy_service/client.py#L83)  for 2.0.0 which is the default version installed when installing ScoutSuite with just `pip install ScoutSuite`.

Debug output for installation with the 2.0.0 of the monitoring library:

```
$ scout gcp --debug -s $GOOGLE_APPLICATION_CREDENTIALS --project-id $PROJECT_ID --no-browser  --services stackdrivermonitoring       
2020-11-05 15:45:30 rwauw0025 scout[14943] INFO Launching Scout
2020-11-05 15:45:30 rwauw0025 scout[14943] INFO Authenticating to cloud provider
2020-11-05 15:45:31 rwauw0025 scout[14943] INFO Gathering data from APIs
2020-11-05 15:45:31 rwauw0025 scout[14943] DEBUG Skipping the Credentials service
2020-11-05 15:45:31 rwauw0025 scout[14943] DEBUG Skipping the Cloud SQL service
2020-11-05 15:45:31 rwauw0025 scout[14943] DEBUG Skipping the Cloud Storage service
2020-11-05 15:45:31 rwauw0025 scout[14943] DEBUG Skipping the Compute Engine service
2020-11-05 15:45:31 rwauw0025 scout[14943] DEBUG Skipping the IAM service
2020-11-05 15:45:31 rwauw0025 scout[14943] DEBUG Skipping the KMS service
2020-11-05 15:45:31 rwauw0025 scout[14943] DEBUG Skipping the Stackdriver Logging service
2020-11-05 15:45:31 rwauw0025 scout[14943] INFO Fetching resources for the Stackdriver Monitoring service
2020-11-05 15:45:42 rwauw0025 scout[14943] ERROR stackdrivermonitoring.py L12: Failed to retrieve uptime checks: 'UptimeCheckServiceClient' object has no attribute 'project_path'
Traceback (most recent call last):
  File "/home/users/krawczm5/.virtualenvs/scoutsuite/lib/python3.6/site-packages/ScoutSuite/providers/gcp/facade/stackdrivermonitoring.py", line 12, in get_uptime_checks
    name = client.project_path(project_id)
AttributeError: 'UptimeCheckServiceClient' object has no attribute 'project_path'
2020-11-05 15:45:42 rwauw0025 scout[14943] ERROR stackdrivermonitoring.py L21: Failed to retrieve alert policies: 'AlertPolicyServiceClient' object has no attribute 'project_path'
Traceback (most recent call last):
  File "/home/users/krawczm5/.virtualenvs/scoutsuite/lib/python3.6/site-packages/ScoutSuite/providers/gcp/facade/stackdrivermonitoring.py", line 21, in get_alert_policies
    name = client.project_path(project_id)
AttributeError: 'AlertPolicyServiceClient' object has no attribute 'project_path'
2020-11-05 15:45:42 rwauw0025 scout[14943] INFO Running pre-processing engine
2020-11-05 15:45:42 rwauw0025 scout[14943] INFO Running rule engine
2020-11-05 15:45:42 rwauw0025 scout[14943] DEBUG Loading ruleset /home/users/krawczm5/.virtualenvs/scoutsuite/lib/python3.6/site-packages/ScoutSuite/providers/gcp/rules/rulesets/default.json
2020-11-05 15:45:42 rwauw0025 scout[14943] INFO Applying display filters
2020-11-05 15:45:42 rwauw0025 scout[14943] DEBUG Loading ruleset /home/users/krawczm5/.virtualenvs/scoutsuite/lib/python3.6/site-packages/ScoutSuite/providers/gcp/rules/rulesets/filters.json
2020-11-05 15:45:42 rwauw0025 scout[14943] INFO Running post-processing engine
2020-11-05 15:45:43 rwauw0025 scout[14943] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_results_xxxx
2020-11-05 15:45:43 rwauw0025 scout[14943] INFO Saving data to scoutsuite-report/scoutsuite-xxxx
2020-11-05 15:45:43 rwauw0025 scout[14943] INFO Saving data to scoutsuite-report/scoutsuite-results/xxxx
2020-11-05 15:45:43 rwauw0025 scout[14943] INFO Creating scoutsuite-report/xxxx
```

**To Reproduce**

```
$ pip install ScoutSuite
$ scout gcp --debug -s $GOOGLE_APPLICATION_CREDENTIALS --project-id $PROJECT_ID --no-browser  --services stackdrivermonitoring

# to make it pass
$ pip install google-cloud-monitoring==1.1.0
$ scout gcp --debug -s $GOOGLE_APPLICATION_CREDENTIALS --project-id $PROJECT_ID --no-browser  --services stackdrivermonitoring
```

**Comment by j4v** [comment]
Thanks @kravvcu, will address ASAP.

**Comment by j4v** [comment]
This is fixed in https://github.com/nccgroup/ScoutSuite/tree/release/5.10.2, working to ship a release ASAP.
