### ISSUE TITLE
KeyError with EC2 MetadataOptions

### ISSUE THREAD

**Issue by roman-vynar** [nccgroup/ScoutSuite#929]
Hello,

There is an error:
``` 
File "/opt/scout-venv/lib/python3.6/site-packages/ScoutSuite/providers/aws/resources/ec2/instances.py", line 46, in _parse_instance
    instance['metadata_options'] = raw_instance['MetadataOptions']
KeyError: 'MetadataOptions'
```
with
ScoutSuite==5.10.1   
boto3==1.16.18

<details>
 <summary>Full output:</summary>

```
2020-11-16 14:19:49 hostname scout[14800] INFO Launching Scout
2020-11-16 14:19:49 hostname scout[14800] INFO Authenticating to cloud provider
2020-11-16 14:19:50 hostname scout[14800] INFO Gathering data from APIs
2020-11-16 14:19:50 hostname scout[14800] INFO Fetching resources for the ACM service
2020-11-16 14:19:51 hostname scout[14800] INFO Fetching resources for the Lambda service
2020-11-16 14:19:51 hostname scout[14800] INFO Fetching resources for the CloudFormation service
2020-11-16 14:19:51 hostname scout[14800] INFO Fetching resources for the CloudTrail service
2020-11-16 14:19:52 hostname scout[14800] INFO Fetching resources for the CloudWatch service
2020-11-16 14:19:52 hostname scout[14800] INFO Fetching resources for the Config service
2020-11-16 14:19:52 hostname scout[14800] INFO Fetching resources for the Direct Connect service
2020-11-16 14:19:53 hostname scout[14800] INFO Fetching resources for the DynamoDB service
2020-11-16 14:19:53 hostname scout[14800] INFO Fetching resources for the EC2 service
2020-11-16 14:19:53 hostname scout[14800] INFO Fetching resources for the EFS service
2020-11-16 14:19:54 hostname scout[14800] INFO Fetching resources for the ElastiCache service
2020-11-16 14:19:54 hostname scout[14800] INFO Fetching resources for the ELB service
2020-11-16 14:19:54 hostname scout[14800] INFO Fetching resources for the ELBv2 service
2020-11-16 14:19:55 hostname scout[14800] INFO Fetching resources for the EMR service
2020-11-16 14:19:55 hostname scout[14800] INFO Fetching resources for the IAM service
2020-11-16 14:19:55 hostname scout[14800] INFO Fetching resources for the KMS service
2020-11-16 14:19:55 hostname scout[14800] INFO Fetching resources for the RDS service
2020-11-16 14:19:56 hostname scout[14800] INFO Fetching resources for the RedShift service
2020-11-16 14:19:56 hostname scout[14800] INFO Fetching resources for the Route53 service
2020-11-16 14:19:56 hostname scout[14800] INFO Fetching resources for the S3 service
2020-11-16 14:19:57 hostname scout[14800] INFO Fetching resources for the SES service
2020-11-16 14:19:57 hostname scout[14800] INFO Fetching resources for the SNS service
2020-11-16 14:19:57 hostname scout[14800] INFO Fetching resources for the SQS service
2020-11-16 14:19:58 hostname scout[14800] INFO Fetching resources for the VPC service
2020-11-16 14:19:58 hostname scout[14800] INFO Fetching resources for the Secrets Manager service
2020-11-16 14:21:02 hostname asyncio[14800] ERROR Task exception was never retrieved
future: <Task finished coro=<EC2Instances.fetch_all() done, defined at /opt/scout-venv/lib/python3.6/site-packages/ScoutSuite/providers/aws/resources/ec2/instances.py:14> exception=KeyError('MetadataOptions',)>
Traceback (most recent call last):
  File "/opt/scout-venv/lib/python3.6/site-packages/ScoutSuite/providers/aws/resources/ec2/instances.py", line 17, in fetch_all
    name, resource = await self._parse_instance(raw_instance)
  File "/opt/scout-venv/lib/python3.6/site-packages/ScoutSuite/providers/aws/resources/ec2/instances.py", line 46, in _parse_instance
    instance['metadata_options'] = raw_instance['MetadataOptions']
KeyError: 'MetadataOptions'
2020-11-16 14:21:02 hostname asyncio[14800] ERROR Task exception was never retrieved
future: <Task finished coro=<EC2Instances.fetch_all() done, defined at /opt/scout-venv/lib/python3.6/site-packages/ScoutSuite/providers/aws/resources/ec2/instances.py:14> exception=KeyError('MetadataOptions',)>
Traceback (most recent call last):
  File "/opt/scout-venv/lib/python3.6/site-packages/ScoutSuite/providers/aws/resources/ec2/instances.py", line 17, in fetch_all
    name, resource = await self._parse_instance(raw_instance)
  File "/opt/scout-venv/lib/python3.6/site-packages/ScoutSuite/providers/aws/resources/ec2/instances.py", line 46, in _parse_instance
    instance['metadata_options'] = raw_instance['MetadataOptions']
KeyError: 'MetadataOptions'
2020-11-16 14:21:03 hostname asyncio[14800] ERROR Task exception was never retrieved
future: <Task finished coro=<EC2Instances.fetch_all() done, defined at /opt/scout-venv/lib/python3.6/site-packages/ScoutSuite/providers/aws/resources/ec2/instances.py:14> exception=KeyError('MetadataOptions',)>
Traceback (most recent call last):
  File "/opt/scout-venv/lib/python3.6/site-packages/ScoutSuite/providers/aws/resources/ec2/instances.py", line 17, in fetch_all
    name, resource = await self._parse_instance(raw_instance)
  File "/opt/scout-venv/lib/python3.6/site-packages/ScoutSuite/providers/aws/resources/ec2/instances.py", line 46, in _parse_instance
    instance['metadata_options'] = raw_instance['MetadataOptions']
KeyError: 'MetadataOptions'
2020-11-16 14:21:15 hostname scout[14800] INFO Running pre-processing engine
2020-11-16 14:21:15 hostname scout[14800] INFO Running rule engine
2020-11-16 14:21:21 hostname scout[14800] INFO Applying display filters
2020-11-16 14:21:21 hostname scout[14800] INFO Running post-processing engine
2020-11-16 14:21:21 hostname scout[14800] INFO Saving data to /opt/nginx/reports/scout/report-prod/scoutsuite-results/scoutsuite_results_index.js
2020-11-16 14:21:21 hostname scout[14800] INFO Saving data to /opt/nginx/reports/scout/report-prod/scoutsuite-results/scoutsuite_exceptions_index.js
2020-11-16 14:21:21 hostname scout[14800] INFO Creating /opt/nginx/reports/scout/report-prod/index.html
```
</details>

**Comment by j4v** [comment]
Thanks for raising this @roman-vynar, could you run the https://github.com/nccgroup/ScoutSuite/tree/release/5.10.2 branch and confirm it resolves the issue?

**Comment by roman-vynar** [comment]
I manually applied the fix and it worked, thanks!
